### ISSUE TITLE
FATECLOUD_REPO_URL问题

### ISSUE THREAD

**Issue by majorinche** [FederatedAI/KubeFATE#105]
- name: FATECLOUD_REPO_URL
              value: "http://docker-repo.sonic.com:443/chartrepo/chartrepo"

这个应该是下载chart的吧
现在不用这个，而是直接手动方式kubefate chart upload
cluster.yaml修改好后，那么这里的FATECLOUD_REPO_URL环境变量应该怎么填，

主要问题：发现即使用了手动的方式上传chart后，kubefate还是会去访问FATECLOUD_REPO_URL啊？

**Comment by majorinche** [comment]
chart上传后的版本信息
[root@okd-calico01 kubefate]# kubefate chart ls
UUID                                	NAME	VERSION 	APPVERSION
c97f642b-0834-41b6-8a38-e7de12814368	fate	v1.3.0-a	v1.3.0

**Comment by LaynePeng** [comment]
如果不自己host chart可以不修改，直接用我们这个github的即可。
