### ISSUE TITLE
docker load instruction update

### ISSUE THREAD

**Issue by whyseu** [FederatedAI/KubeFATE#110]
The "docker load fate_<version>-images.tar.gz" instruction in the "https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md" should be update to "docker load --input fate_<version>-images.tar.gz"

**Comment by jiahaoc1993** [comment]
thanks for the correction

**Comment by LaynePeng** [comment]
Close since this is a feedback. And commit as: https://github.com/FederatedAI/KubeFATE/compare/a0c48021552ea2fe3fb4cd754ba1931ef3366d1d...41c30ee8c046f1e35c4b1ebadb8f8960f40067ed . Thanks @whyseu  . And we encourage you can PR this to us. Thanks again.
