### ISSUE TITLE
mysql容器一直处于restarting状态

### ISSUE THREAD

**Issue by hanisacoder** [FederatedAI/KubeFATE#113]
![image](https://user-images.githubusercontent.com/18024317/77537415-03dd1300-6ed9-11ea-9795-a034528072ff.png)
mysql容器一直处于 restart。
查看日志如下：
mysql的容器日志发现报错如下:
![image](https://user-images.githubusercontent.com/18024317/77539323-245a9c80-6edc-11ea-8969-ff09ed25a154.png)
尝试执行docker-compose down 然后执行docker-compose up
mysql容器日志如下:
![image](https://user-images.githubusercontent.com/18024317/77539429-4fdd8700-6edc-11ea-987f-3e5a41e0b88c.png)
我是使用的普通用户用sudo 安装的docker和docker-compose，然后把普通用户加入docker用户组。
用普通用户执行的部署操作。

**Comment by davidlinhl** [comment]
同上，mysql和python两个docker一直在重启

**Comment by xglreal** [comment]
请问问题解决了吗？我也碰到这个问题

**Comment by hanisacoder** [comment]
> 请问问题解决了吗？我也碰到这个问题

解决了，myql没有部署好，我用root用户重新部署，就不会复现上述问题，可能用户跟权限有关系

**Comment by LaynePeng** [comment]
Close issue cuz resolved. Mark "Good first issue" for new comer.
