### ISSUE TITLE
k8s(v1.18.0)集群部署FAET(v1.3)后，如何配置挂载hostpath？

### ISSUE THREAD

**Issue by ORANGECAT-S** [FederatedAI/KubeFATE#117]
hostpath部署参考：https://github.com/rancher/local-path-provisioner
主要执行以下三步：
1、kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
2、kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pvc.yaml
3、kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pod.yaml
其中，localpath、pvc、pod的配置请直接访问以上链接查看。
请问，我应该如何修改以上三个配置文件，以达到本地目录与k8s集群中的FATE共享目录对的效果？
或者是否有其他部署hostpath的更好方式？

本人使用k8s集群部署FATE，仅差这最后一步，若解决，会将部署详细文档分享大家参考。
盼复，非常感谢！！！

**Comment by ORANGECAT-S** [comment]
local-path-storage.yaml配置文件：
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints", "persistentvolumes", "pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
- kind: ServiceAccount
  name: local-path-provisioner-service-account
  namespace: local-path-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
      - name: local-path-provisioner
        image: rancher/local-path-provisioner:v0.0.12
        imagePullPolicy: IfNotPresent
        command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt/local-path-provisioner"]
                }
                ]
        }

**Comment by ORANGECAT-S** [comment]
pvc.yaml配置文件：
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

**Comment by ORANGECAT-S** [comment]
pod.yaml配置文件：
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc

**Comment by ORANGECAT-S** [comment]
local-path-storage.yaml配置文件：
请访问： https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

**Comment by jiahaoc1993** [comment]
1. 更换[chart](https://github.com/FederatedAI/KubeFATE/tree/gh-pages/fate/templates)中所有的pvc
2. 上传更新后的chart到kubefate server
3. 部署

**Comment by ORANGECAT-S** [comment]
> 1. 更换[chart](https://github.com/FederatedAI/KubeFATE/tree/gh-pages/fate/templates)中所有的pvc
> 2. 上传更新后的chart到kubefate server
> 3. 部署

您说的chart指的是data-nfs.yaml吗？更换内容都需要更换一些什么呢？有demo吗？

**Comment by LaynePeng** [comment]
No demo by now. The dataset upload and download feature will be ready in v1.4.
