### ISSUE TITLE
docker-copome部署后storage-service无法启动，有core down

### ISSUE THREAD

**Issue by daihw** [FederatedAI/KubeFATE#120]
使用docker-compose方式部署，conf-10000方的 storage-service未启动，进入egg容器后发现有service storage 有core down信息
![image](https://user-images.githubusercontent.com/18308711/79521444-c9a40300-808b-11ea-9b15-0ade2e7e14f1.png)

**Comment by jiahaoc1993** [comment]
参考下wiki
