### ISSUE TITLE
加载模型的时候显示101，然后无法绑定模型，没有很明确的报错信息，该如何排查问题

### ISSUE THREAD

**Issue by WillJiang12** [FederatedAI/KubeFATE#125]
![IMG_6262](https://user-images.githubusercontent.com/64405618/80356511-22557600-88ac-11ea-99ad-1797f07108cf.JPG)
![IMG_6261](https://user-images.githubusercontent.com/64405618/80356533-2a151a80-88ac-11ea-9274-bbe3fb10682f.JPG)
![IMG_6260](https://user-images.githubusercontent.com/64405618/80356544-2c777480-88ac-11ea-882a-fa83cf1e34ca.JPG)
![IMG_6259](https://user-images.githubusercontent.com/64405618/80356556-30a39200-88ac-11ea-9c0c-1003826d384c.JPG)

**Comment by WillJiang12** [comment]
parties.conf——————————————————-
#!/bin/bash

user=root
dir=/data/projects/fate
partylist=(10000 9999) 
partyiplist=(172.16.1.2 172.16.1.1)
servingiplist=(172.16.1.2 172.16.1.1)

# party 1 will host the exchange by default
exchangeip=

generate_config.sh—————————————————

########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

#!/bin/bash

BASEDIR=$(dirname "$0")
cd $BASEDIR
WORKINGDIR=`pwd`
deploy_dir=/home/user/fate

# fetch fate-python image
source ${WORKINGDIR}/.env
source ${WORKINGDIR}/parties.conf

cd ${WORKINGDIR}

GenerateConfig() {
    for ((i=0;i<${#partylist[*]};i++))
    do
        eval version=1.2
        eval java_dir=
        eval source_code_dir=
        eval output_packages_dir=
        eval deploy_packages_dir=
    
        eval party_id=\${partylist[${i}]}
        eval party_ip=\${partyiplist[${i}]}
        eval serving_ip=\${servingiplist[${i}]}
    
        eval processor_port=50000
        eval processor_count=2
        eval venv_dir=/data/projects/python/venv
        eval python_path=${deploy_dir}/python:${deploy_dir}/eggroll/python
        eval data_dir=${deploy_dir}/data-dir
    
        eval egg_ip=(egg)
        eval egg_port=7888
    
        eval meta_service_ip=meta-service
        eval meta_service_port=8590
    
        eval roll_ip=roll
        eval roll_port=8011
    
        eval proxy_ip=proxy
        eval proxy_port=9370
    
        eval fateboard_ip=fateboard
        eval fateboard_port=8081
    
        eval fate_flow_ip=python
        eval fate_flow_grpc_port=9361
        eval fate_flow_http_port=9380
    
        eval storage_service_ip=(egg)
        eval storage_service_port=7778
    
        eval db_ip=mysql
        eval db_user=fate
        eval db_password=fate_dev
        eval db_name=fate
    
        eval node_list=()
    
        eval redis_ip=redis
        eval redis_password=fate_dev
———该配置文件下面都没有改变，主要是把9360改成9361，还有8080改成8081——————

docker-compose.yml：


########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

version: '3'

networks:
  fate-network:

volumes:
  fate_flow_logs:
  shared_dir_examples:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/host/dir/examples
  shared_dir_federatedml:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/host/dir/federatedml

services:
  federation:
    image: "${PREFIX}/federation:${TAG}"
    expose:
      - 9394
    volumes:
      - ./confs/federation/conf:/data/projects/fate/federation/conf
    networks:
      - fate-network

  proxy:
    image: "${PREFIX}/proxy:${TAG}"
    ports:
      - "9370:9370"
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    volumes:
      - ./confs/proxy/conf:/data/projects/fate/proxy/conf
    networks:
      - fate-network

  fateboard:
    image: "${PREFIX}/fateboard:${TAG}"
    ports:
      - "8081:8081"
    volumes:
      - ./confs/fateboard/conf:/data/projects/fate/fateboard/conf
      - fate_flow_logs:/data/projects/fate/python/logs
    networks:
      - fate-network
    depends_on:
      - meta-service
      - python

  roll:
    image: "${PREFIX}/roll:${TAG}"
    expose:
      - 8011
    volumes:
      - ./confs/roll/conf:/data/projects/fate/roll/conf
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    networks:
      - fate-network
    depends_on:
      - meta-service

  egg:
    image: "${PREFIX}/egg:${TAG}"
    expose:
      - 7888
      - 7778
      - "50000-60000"
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: cpp 
      LD_LIBRARY_PATH: $$LD_LIBRARY_PATH:/usr/local/lib:/data/projects/fate/eggroll/storage-service-cxx/third_party/lib
      PYTHONPATH: /data/projects/fate/eggroll/python
      GLOG_log_dir: /data/projects/fate/eggroll/storage-service-cxx/logs
    volumes:
        - ./confs/egg/conf:/data/projects/fate/eggroll/egg/conf
        - ./confs/federatedml/conf/server_conf.json:/data/projects/fate/eggroll/python/eggroll/conf/server_conf.json
        - ./confs/egg/data-dir:/data/projects/fate/data-dir
    networks:
      - fate-network

  python:
    image: "${PREFIX}/python:${TAG}"
    ports:
      - "9361:9361"
      - "9380:9380"
    restart: always
    volumes:
      - shared_dir_federatedml:/data/projects/fate/python/federatedml
      - shared_dir_examples:/data/projects/fate/python/examples
      - ./confs/federatedml/conf:/data/projects/fate/python/arch/conf
      - ./confs/federatedml/conf:/data/projects/fate/python/eggroll/conf
      - ./confs/fate_flow/conf/settings.py:/data/projects/fate/python/fate_flow/settings.py
      - ./confs/fate_flow/conf/server_conf.json:/data/projects/fate/python/arch/conf/server_conf.json
      - fate_flow_logs:/data/projects/fate/python/logs
    depends_on:
      - redis
      - meta-service
      - proxy
      - roll
      - egg
      - mysql
    networks:
      - fate-network
———该配置文件下面都没有改变，主要是把9360改成9361，还有8080改成8081——————

然后就执行generate_config.sh，再然后运行docker_deploy.sh all

**Comment by WillJiang12** [comment]
部署完成后，能正常执行双边模型训练，就在做在线推理前加载这个绑定模块时有报错，不知道是否与我修改了8080和9360的端口号的原因？（因为原9360和8080端口有被使用，所以已经改成8081和9361）

**Comment by LaynePeng** [comment]
建议看一下fateflow的log

**Comment by WillJiang12** [comment]
你指的是哪个log文件，在logs文件夹下面有很多个文件。目前没发现你说的那个报错

**Comment by WillJiang12** [comment]
![IMG_6266](https://user-images.githubusercontent.com/64405618/80436572-0b596700-8932-11ea-8e49-0ff8a071f964.jpg)
![IMG_6265](https://user-images.githubusercontent.com/64405618/80436587-12807500-8932-11ea-9431-b4ce8aca8a5e.jpg)

我看到了类似的。这个有关系吗？

**Comment by WillJiang12** [comment]
![IMG_6266](https://user-images.githubusercontent.com/64405618/80436696-51162f80-8932-11ea-8322-cf7767a93fda.jpg)
![IMG_6265](https://user-images.githubusercontent.com/64405618/80436713-596e6a80-8932-11ea-9f80-90a42d3e2fc9.jpg)


我看到一个类似的，这个有关系吗

**Comment by WillJiang12** [comment]
![IMG_6272](https://user-images.githubusercontent.com/64405618/80437356-f41b7900-8933-11ea-9c79-34d5078ccfa6.JPG)
![IMG_6271](https://user-images.githubusercontent.com/64405618/80437370-f978c380-8933-11ea-92c4-737b845a58ef.JPG)
![IMG_6270](https://user-images.githubusercontent.com/64405618/80437372-faa9f080-8933-11ea-8a6f-32b211024527.JPG)

**Comment by WillJiang12** [comment]
![IMG_6272](https://user-images.githubusercontent.com/64405618/80437416-18775580-8934-11ea-8c52-ed91d92568d4.JPG)
![IMG_6271](https://user-images.githubusercontent.com/64405618/80437431-1c0adc80-8934-11ea-944b-ffe288a0350f.JPG)
![IMG_6270](https://user-images.githubusercontent.com/64405618/80437435-1ca37300-8934-11ea-8b7c-d22b5010e543.JPG)


FYI

**Comment by liyinxin** [comment]
Hi,do you have sloved this problem? i have also meet this problem

**Comment by LaynePeng** [comment]
Close the issue, and please try the latest version: v1.5.0
