### ISSUE TITLE
绑定模型时报错 retcode:100

### ISSUE THREAD

**Issue by learningwang** [FederatedAI/KubeFATE#127]
我用的kubefate,按照
https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md
一步步运行.
到绑定模型这一步时报错
$ python fate_flow_client.py -f bind -c examples/bind_model_service.json
报错内容是
(venv) [root@b8968ce974c3 fate_flow]# python fate_flow_client.py -f bind -c examples/bind_model_service.json
{
    "retcode": 100,
    "retmsg": "<_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"Connect Failed\"\n\tdebug_error_string = \"{\"created\":\"@1588239041.208150875\",\"description\":\"Failed to create subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":2721,\"referenced_errors\":[{\"created\":\"@1588239041.208145968\",\"description\":\"Pick Cancelled\",\"file\":\"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":241,\"referenced_errors\":[{\"created\":\"@1588239041.207990948\",\"description\":\"Connect Failed\",\"file\":\"src/core/ext/filters/client_channel/subchannel.cc\",\"file_line\":689,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1588239041.207960859\",\"description\":\"Failed to connect to remote host: OS Error\",\"errno\":113,\"file\":\"src/core/lib/iomgr/tcp_client_posix.cc\",\"file_line\":210,\"os_error\":\"No route to host\",\"syscall\":\"getsockopt(SO_ERROR)\",\"target_address\":\"ipv4:192.168.216.130:8000\"}]}]}]}\"\n>"
}
能帮我看一下吗,谢谢

**Comment by LaynePeng** [comment]
Duplicate with https://github.com/FederatedAI/KubeFATE/issues/112
