### ISSUE TITLE
将现有的 KubeFate 部署以及应用涉及到的DB 能够适配外部DB

### ISSUE THREAD

**Issue by hanisacoder** [FederatedAI/KubeFATE#128]
在一般公司中不同的DB都是由专门的运维人员在运维，希望将当前的KubeFate中部署以及应用的涉及到的DB(mongdb、redis、mysql)都可以适配到外部的DB，能够不依赖自身容器中的独立DB，并提供相关的配置可选项。

**Comment by LaynePeng** [comment]
Good feature request, will add in v1.4.0-a

**Comment by LaynePeng** [comment]
Fixed and added to v1.4.0
