### ISSUE TITLE
When the python pod is starting, the mysql service sometimes is not yet stared!

### ISSUE THREAD

**Issue by LynnYuanInspur** [FederatedAI/KubeFATE#13]
When the python pod is starting, the mysql service sometimes is not yet stared!, so the python pod always restarting multi times. so i add a initContainer to wating for the mysql server running.

**Comment by davidlinhl** [comment]
![image](https://user-images.githubusercontent.com/29757093/79187552-26ff4080-7e4f-11ea-8381-346cf4f51d0f.png)
a clean install following instructions on centos, seems there are still issues here

**Comment by silvanabc** [comment]
@davidlinhl Did you manage to solve it?
