### ISSUE TITLE
下载miniKube是否需要补充加速说明

### ISSUE THREAD

**Issue by pipi670** [FederatedAI/KubeFATE#130]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

**Desktop (please complete the following information):**

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**
Clear the unexpected response.

**Screenshots**

**Additional context**

**Comment by LaynePeng** [comment]
What is the question?

**Comment by pipi670** [comment]
您好，
发现在部署过程中，包括miniKube在内的一些安装包，提供的默认镜像下载地址，下载时间会非常长，1-2天，并且有时需要多试几次。
我后来是自行找到的国内镜像下载的安装包，过程就非常快。
是想说，我这种网络状况，也可能代表了广大学习者的一种情况，如果目前还没有办法集成部署所需的所有软件包，可能是不是也可以补充说明下。
谢谢！

------------------

杜妮娜 丨产品数据中心
联易融数字科技集团有限公司
手机：13243773166
地址：深圳市南山区科苑南路3099号中国储能大厦36楼



 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Layne Peng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 上午10:59
收件人:&nbsp;"FederatedAI/KubeFATE"<KubeFATE@noreply.github.com&gt;; 
抄送:&nbsp;"pipi670"<dunina@linklogis.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题:&nbsp;Re: [FederatedAI/KubeFATE] 下载miniKube是否需要补充加速说明 (#130)

&nbsp;



 
What is the question?

**Comment by LaynePeng** [comment]
谢谢提醒。这是非常好的建议！可以把具体地址给我们我们添加，或者更好的方法是PR到相关文档。

Sent from iPhone

在 2020年5月14日，上午11:06，pipi670 <notifications@github.com> 写道：

﻿

您好，
发现在部署过程中，包括miniKube在内的一些安装包，提供的默认镜像下载地址，下载时间会非常长，1-2天，并且有时需要多试几次。
我后来是自行找到的国内镜像下载的安装包，过程就非常快。
是想说，我这种网络状况，也可能代表了广大学习者的一种情况，如果目前还没有办法集成部署所需的所有软件包，可能是不是也可以补充说明下。
谢谢！

------------------

杜妮娜 丨产品数据中心
联易融数字科技集团有限公司
手机：13243773166
地址：深圳市南山区科苑南路3099号中国储能大厦36楼





&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Layne Peng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 上午10:59
收件人:&nbsp;"FederatedAI/KubeFATE"<KubeFATE@noreply.github.com&gt;;
抄送:&nbsp;"pipi670"<dunina@linklogis.com&gt;; "Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FederatedAI/KubeFATE] 下载miniKube是否需要补充加速说明 (#130)

&nbsp;




What is the question?

**Comment by pipi670** [comment]
好的，我整理下。
从你们1.0发布到现在，一直关注，加油~~


------------------

杜妮娜 丨产品数据中心
联易融数字科技集团有限公司
手机：13243773166
地址：深圳市南山区科苑南路3099号中国储能大厦36楼



 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Layne Peng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 中午11:14
收件人:&nbsp;"FederatedAI/KubeFATE"<KubeFATE@noreply.github.com&gt;; 
抄送:&nbsp;"pipi670"<dunina@linklogis.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题:&nbsp;Re: [FederatedAI/KubeFATE] 下载miniKube是否需要补充加速说明 (#130)

&nbsp;



 谢谢提醒。这是非常好的建议！可以把具体地址给我们我们添加，或者更好的方法是PR到相关文档。 
 
 Sent from iPhone 
 
 在 2020年5月14日，上午11:06，pipi670 <notifications@github.com&gt; 写道： 
 
 ﻿ 
 
 您好， 
 发现在部署过程中，包括miniKube在内的一些安装包，提供的默认镜像下载地址，下载时间会非常长，1-2天，并且有时需要多试几次。 
 我后来是自行找到的国内镜像下载的安装包，过程就非常快。 
 是想说，我这种网络状况，也可能代表了广大学习者的一种情况，如果目前还没有办法集成部署所需的所有软件包，可能是不是也可以补充说明下。 
 谢谢！ 
 
 ------------------ 
 
 杜妮娜 丨产品数据中心 
 联易融数字科技集团有限公司 
 手机：13243773166 
 地址：深圳市南山区科苑南路3099号中国储能大厦36楼 
 
 
 
 
 
 &amp;nbsp; 
 &amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Layne Peng"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年5月14日(星期四) 上午10:59 
 收件人:&amp;nbsp;"FederatedAI/KubeFATE"<KubeFATE@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"pipi670"<dunina@linklogis.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [FederatedAI/KubeFATE] 下载miniKube是否需要补充加速说明 (#130) 
 
 &amp;nbsp; 
 
 
 
 
 What is the question?

**Comment by LaynePeng** [comment]
Close this issue because no follow-up response.
