### ISSUE TITLE
任务僵死

### ISSUE THREAD

**Issue by Origin-Draven** [FederatedAI/KubeFATE#141]
用 https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md 的方法部署 不知道为什么总是卡死在 intersection 里面
![image](https://user-images.githubusercontent.com/20585352/82428105-97d3f100-9abc-11ea-841e-2a4ff3626af6.png)
![image](https://user-images.githubusercontent.com/20585352/82428124-9e626880-9abc-11ea-8752-2c6cfc299c18.png)
![image](https://user-images.githubusercontent.com/20585352/82428136-a28e8600-9abc-11ea-8516-f1da5410f893.png)

后来发现偶尔也可以到binning 挂掉
![image](https://user-images.githubusercontent.com/20585352/82428204-c18d1800-9abc-11ea-9415-1448de4c59f8.png)

以下是 rollsite 的日志
在 instersection_1 挂掉的时候
![image](https://user-images.githubusercontent.com/20585352/82428276-d9649c00-9abc-11ea-86b1-6ccdac6ea3da.png)

然后隔了20分钟又动了一下，从intersection_1到intersection_0 了
![image](https://user-images.githubusercontent.com/20585352/82428283-dc5f8c80-9abc-11ea-9fd6-227f53ef0499.png)

然后日志再没动过
fatebord 日志也永远停在了这里
![image](https://user-images.githubusercontent.com/20585352/82428434-1a5cb080-9abd-11ea-865a-3f55e490a35b.png)

比对了一下上面
![image](https://user-images.githubusercontent.com/20585352/82428732-863f1900-9abd-11ea-9bc4-7b0e226891b0.png)
发现这个走完intersection就可以成功了

但是经常挂在这，不清楚原因。如果怀疑机器配置原因也可以问。
目前是centos7. docker1.8，docker-compose1.24
补充：
intersection_1 的数据量 7.2k，intersection_0 数据量29.2k，目前 intersection_1 完成概率还是挺高的，intersection_0 很少能完成

测试 toy_example 没问题
![image](https://user-images.githubusercontent.com/20585352/82428162-ad491b00-9abc-11ea-88e6-9b304df29bcc.png)

**Comment by Origin-Draven** [comment]
40001 的 route_table.json
![image](https://user-images.githubusercontent.com/20585352/82433105-8b9f6200-9ac3-11ea-95e7-1c726874f0d3.png)
40002 的 route_table.json
![image](https://user-images.githubusercontent.com/20585352/82433213-b7224c80-9ac3-11ea-9690-e3d4b43896fa.png)

**Comment by Origin-Draven** [comment]
40001 :docker logs --tail 20 --follow  confs-40001_python_1 日志会一直刷新
![image](https://user-images.githubusercontent.com/20585352/82433601-43347400-9ac4-11ea-95ab-5fba0333c77c.png)
40002 : docker logs --tail 20 --follow  confs-40002_python_1 日志会静止在这，有任务的时候才动一下。但是重装几次了，安装包和 40001 一样的。不太理解为什么会这样
![image](https://user-images.githubusercontent.com/20585352/82433617-492a5500-9ac4-11ea-93b4-b5b9210c5eb2.png)

**Comment by Origin-Draven** [comment]
使用 docker logs --tail 20 --follow  confs-40001_python_1 和 docker logs --tail 20 --follow  confs-40002_python_1 查看日志 ，会发现突然一起不动了
![image](https://user-images.githubusercontent.com/20585352/82434913-25680e80-9ac6-11ea-99f4-135d04d78078.png)

**Comment by owlet42** [comment]
查看一下其他模块的logs，nodemanager、clustermanager....

**Comment by Origin-Draven** [comment]
上午重装了一下 fate1.4，重新提交了一个 在binning 里面不动了
40001_python_1 和 40002_python_1
![image](https://user-images.githubusercontent.com/20585352/82518383-debff600-9b51-11ea-9baf-12d96f6da1cc.png)

nodemanager 
![image](https://user-images.githubusercontent.com/20585352/82518877-e46a0b80-9b52-11ea-97aa-0d7452be6f84.png)
![image](https://user-images.githubusercontent.com/20585352/82518843-d4eac280-9b52-11ea-9538-7f16d1ccb5f4.png)


clustermanager
![image](https://user-images.githubusercontent.com/20585352/82518775-aec52280-9b52-11ea-9a2c-d8f8b133207b.png)
![image](https://user-images.githubusercontent.com/20585352/82518806-c1d7f280-9b52-11ea-83d4-2175c7962320.png)



mysql
![image](https://user-images.githubusercontent.com/20585352/82518490-1333b200-9b52-11ea-8556-800f76cd3827.png)

client 
![image](https://user-images.githubusercontent.com/20585352/82518527-29da0900-9b52-11ea-90c9-6392af523114.png)

server-proxy
![image](https://user-images.githubusercontent.com/20585352/82518593-4aa25e80-9b52-11ea-90d2-76a24b69d21a.png)
server-server
![image](https://user-images.githubusercontent.com/20585352/82518631-60178880-9b52-11ea-889d-d51125453529.png)

server-redis
![image](https://user-images.githubusercontent.com/20585352/82518716-8b9a7300-9b52-11ea-8494-8c7e17fca1f0.png)

docker 状态
![image](https://user-images.githubusercontent.com/20585352/82518984-25622000-9b53-11ea-9e68-2c553f797e37.png)
![image](https://user-images.githubusercontent.com/20585352/82519017-3e6ad100-9b53-11ea-89e1-3b4cec832188.png)

其他还需要什么我可以尽力补充

**Comment by Origin-Draven** [comment]
rollsite
![image](https://user-images.githubusercontent.com/20585352/82519179-a5888580-9b53-11ea-9324-ec07b22ac933.png)
![image](https://user-images.githubusercontent.com/20585352/82519222-bb964600-9b53-11ea-9bbb-d06cac872203.png)

**Comment by jiahaoc1993** [comment]
你的exchange好像down了，能否看下原因？

**Comment by Origin-Draven** [comment]
> 你的exchange好像down了，能否看下原因？

上午安装的时候没有使用，exchangeip一栏填得空

**Comment by Origin-Draven** [comment]
重装了系统之后僵死的问题转为超时的问题，移步 https://github.com/FederatedAI/KubeFATE/issues/144
