### ISSUE TITLE
fate1.4 训练模块经常超时 和 predict 模块报错

### ISSUE THREAD

**Issue by Origin-Draven** [FederatedAI/KubeFATE#144]
使用 docker-compose 部署的 fate 的1.4
45 为 guest + exchange
46为 host
使用 examples/federatedml-1.x-examples/hetero_secureboost 中的 test_secureboost_train_dsl.json
和conf 训练自己的数据 （train3w+test7k）

模型训练过程经常报错（训练过程中的超时错误，既有在intersection也有bin也有secureboost）（host侧为主）
![image](https://user-images.githubusercontent.com/20585352/82971913-6f8d4a80-a006-11ea-953e-b3f0d71b1db4.png)
![image](https://user-images.githubusercontent.com/20585352/82971979-8d5aaf80-a006-11ea-825c-be74750e53ac.png)

predict 模块直接报错 （数据类型转换错误）
predict 模块使用train 的数据和test数据均会报错（guest侧）排除了数据集的问题
![image](https://user-images.githubusercontent.com/20585352/82972013-a06d7f80-a006-11ea-86fb-d1eb4bdf5635.png)

**Comment by jiahaoc1993** [comment]
@Origin-Draven 你好，请问训练的数据量有多大呢？能否先尝试下小数据集的训练以排除配置的问题。训练的失败跟硬件和带宽都有关系，大数据量下会更加突出。

**Comment by Origin-Draven** [comment]
> @Origin-Draven 你好，请问训练的数据量有多大呢？能否先尝试下小数据集的训练以排除配置的问题。训练的失败跟硬件和带宽都有关系，大数据量下会更加突出。

数据量训练train29k + test7k，嗯最近我试试 有信息了会同步一下

**Comment by Origin-Draven** [comment]
> @Origin-Draven 你好，请问训练的数据量有多大呢？能否先尝试下小数据集的训练以排除配置的问题。训练的失败跟硬件和带宽都有关系，大数据量下会更加突出。

可能是用的旧版部署包的问题，新的Kubefate部署包就没问题了 谢谢啦

**Comment by VincyChen96** [comment]
> 

请问你用的新的部署包是哪个版本的
