### ISSUE TITLE
FATE1.3 在加载模型的时候出错

### ISSUE THREAD

**Issue by zhanghengjing2** [FederatedAI/KubeFATE#148]
grpc会出现Failed to create subchannel的错误 

machine_learning_model_app.py[line:32] - ERROR: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Name resolution failure"
	debug_error_string = "{"created":"@1591065585.140327488","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1591065585.140324417","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3026,"grpc_status":14}]}"

**Comment by liyinxin** [comment]
Hi do you have solved it ? i also meet this problem.

**Comment by xby8888** [comment]
me, too

**Comment by LaynePeng** [comment]
Close the issue, and please retry with latest version.
