### ISSUE TITLE
重复执行docker_deploy.sh时提示文件覆盖问题

### ISSUE THREAD

**Issue by ChanaLii** [FederatedAI/KubeFATE#154]
版本：
- kubefate-docker-compose-v1.4

1.重复执行`docker_deploy.sh`时提示文件是否覆盖`mv: overwrite ‘/data/projects/fate/serving-8888.tar’? `，手动输入`yes`后程序无日志输出，请问这是什么问题？

![image](https://user-images.githubusercontent.com/20842481/84356542-e6296b00-abf6-11ea-992b-80eed9a8d47b.png)

2.我查看脚本`docker_deploy.sh`的内容，看到196行处，是否应该删除文件`rm -rf $dir/serving-$target_party_id.tar`之后再创建文件夹呢？
![image](https://user-images.githubusercontent.com/20842481/84357209-dd856480-abf7-11ea-984a-7d73f0ebf656.png)

3.我按照`步骤2`修改了`docker_deploy.sh`文件，日志无异常，启动成功
![image](https://user-images.githubusercontent.com/20842481/84358616-fd1d8c80-abf9-11ea-92bb-5cf83f125c44.png)
![image](https://user-images.githubusercontent.com/20842481/84358400-add75c00-abf9-11ea-8495-6be9702bf954.png)
![image](https://user-images.githubusercontent.com/20842481/84358434-b9c31e00-abf9-11ea-98e8-6ddf995de9b5.png)

**Comment by jiahaoc1993** [comment]
Thanks for your feedback, will update according to your suggestion soon
