### ISSUE TITLE
Cannot run toy_example

### ISSUE THREAD

**Issue by chaindreamjet** [FederatedAI/KubeFATE#155]
**What deployment mode you use?  **
1. docker-compose

**What KubeFATE and FATE version you are using?  **
1.4.0

**What OS you are using for docker-compose or Kubernetes? Please also clear the version of OS.  **
Ubuntu 18.04

**To Reproduce**
When following the deployment manual step by step, there is nothing going wrong until I run the run_toy_example.py.
My two machines' private IPs are 172.31.66.120 & 172.31.67.208.
ssh login without key has no problem.
I have no idea what went wrong here.

**What happens?**
No matter how many times I try it, It failed with an unreadable exception, see below.

**Screenshots**
![image](https://user-images.githubusercontent.com/28439833/84371236-e97b2180-ac0b-11ea-93fe-6eaccd7c4563.png)

**Comment by chaindreamjet** [comment]
我按照docker-compose 部署文档做的
前面都很顺利，生成部署文件以及集群部署，看上去都没问题
docker ps 看到的各组件状态也都正常
但是运行不了toy_example
就会报截图上的错误

**Comment by xby8888** [comment]
同样遇到这个错误

**Comment by LaynePeng** [comment]
Vary causes of this error. Close it and please verify with the latest version: v1.5.0

**Comment by rishy** [comment]
I really like the initiative here. But, we shouldn't just close issue a like this without providing any solution and link to issues for fixes.

If this was still open at least someone else could have a look at it and potentially come up with a solution.
