### ISSUE TITLE
k8s部署是否支持无互联网连接的部署？

### ISSUE THREAD

**Issue by JianhuanZeng** [FederatedAI/KubeFATE#181]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
KubeFATE  1.4.0；
FATE 1.4.0;

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - CentOS 7
- 无互联网

**To Reproduce**
安装部署，用kubefate cluster install

**What happen?**
用kubefate cluster install的时候，他会去下载一个东西，然后下不了，就安装集群失败了

**Screenshots**

```

> &{Data:0xc0004960b0 Msg:}&{Uuid:883f6856-0d38-4e5c-bf16-d7c45a6a5fa4 StartTime:2020-07-08 06:04:15.336 +0000 UTC EndTime:2020-07-08 06:04:19.405 +0000 UTC Method:ClusterInstall Result:failed to download "kubefate/fate" (hint: running `helm repo update` may help) ClusterId:f080565e-32d0-45bb-a2e7-9d92ed27da7e Creator:admin SubJobs:[] Status:Failed TimeLimit:1h0m0s}UUID      883f6856-0d38-4e5c-bf16-d7c45a6a5fa4                                          
> StartTime 2020-07-08 06:04:15                                                           
> EndTime   2020-07-08 06:04:19                                                           
> Status    Failed                                                                        
> Creator   admin                                                                         
> ClusterId f080565e-32d0-45bb-a2e7-9d92ed27da7e                                          
> Result    failed to download "kubefate/fate" (hint: running `helm repo update` may help)
> SubJobs   []
```

**Additional context**
正常情况k8s部署不支持无互联网连接的部署吗？

**Comment by owlet42** [comment]
If you need to deploy offline, you need to download and upload the [chart](https://github.com/FederatedAI/KubeFATE/tree/gh-pages/package) file, download the [images ](https://hub.docker.com/search/?q=federatedai&type=image)and distribute them to the k8s node, and then use kubefate cluster install

**Comment by JianhuanZeng** [comment]
thks! where should the chart file upload?

**Comment by JianhuanZeng** [comment]
@owlet42  could you please clarify where the chart file upload? thank u!
