### ISSUE TITLE
Failed to deploy cluster with NFS persistence

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/KubeFATE#183]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
KubeFATE: 1.0.3
FATE: 1.4.0, 1.4.1

**To Reproduce**
Deploy FATE cluster with persistence enabled.
The persistence provisioner is [NFS](quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11) 

**What happen?**
Python container failed to call some nodemanager API

**Comment by jiahaoc1993** [comment]
The reason to cause this failure is clear right now.

Currently the "nodemanager" service uses `shutil.rmtree` to remove the folder no longer used. Usually, this is working well and even no need to handle any error, when it manipulates the local folder. 

However, `shutil.rmtree` will fail to remove remote folder shared by an NFS server in one case, that is, a process tries to remove a folder while another process keeps file under that folder opening.

The opened file will be replaced with a temporary file (with ".nfs" prefix), rather than be removed immediately. And finally the `shutil.rmtree` will throw an exception due to removing a not empty folder. However, in the [latest code](https://github.com/WeBankFinTech/eggroll/blob/master/python/eggroll/core/pair_store/lmdb.py#L170) of "nodemanager", it doesn't handle this exception.

We have reported this issue to the developer of the FATE project, and they will have a patch to fix it in the future.

**Comment by LaynePeng** [comment]
@jiahaoc1993 Has this created issue in FATE?

**Comment by LaynePeng** [comment]
Close as feature added.
