### ISSUE TITLE
Error: cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/KubeFATE#186]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
KubeFATEv1.0.3

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: Centos7

In some cases, when using KubeFATE to deploy FATE on k8s, the job description will prompt "error: cannot re use a name that is still in use". Cluster installation fails, and the same error will be prompted when installing again.

**Comment by owlet42** [comment]
To solve this problem, you need to install helm3, then use `helm list` to view the existing projects, and then use `helm delete` to delete the corresponding projects. 

Then you can use KubeFATE to install FATE again.

**Comment by owlet42** [comment]
#187

**Comment by LaynePeng** [comment]
Close issue cuz fix merged.
