### ISSUE TITLE
Toy Examples Fail ! Error calling to clustermanager:4670 

### ISSUE THREAD

**Issue by JianhuanZeng** [FederatedAI/KubeFATE#190]
**Describe the bug**
when party-7000 running toy examples with the other party-10005,
Error calling to clustermanager:4670
"DNS resolution failed"

**Detail**
[ERROR][2020-07-23 01:01:26,801][MainThread,pid:9,tid:139735875811136][client.py:83.sync_send] - Error calling to clustermanager:4670, command_uri: CommandURI(_uri=v1/cluster-manager/session/getOrCreateSession), req:ErCommandRequest(id=20200723.010126.800, uri=v1/cluster-manager/session/getOrCreateSession, args=[[b'\nAsession_used_by_fate_flow_server_08b1afb2cc8011eaa9db0242c0a70002\x1a\x03NEW2&\n\x1beggroll.session.deploy.mode\x12\x07cluster2(\n#eggroll.session.processors.per.node\x12\x011'], len=1], kwargs=[***, len=0])
Traceback (most recent call last):
File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 71, in sync_send
response = _command_stub.call(request.to_proto())
File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 565, in call
return _end_unary_response_blocking(state, call, False, None)
File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "DNS resolution failed"
debug_error_string = "{"created":"@1595466086.801034424","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3528,"referenced_errors":[{"created":"@1595466086.698403183","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":307,"referenced_errors":[{"created":"@1595466086.698401247","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":358,"grpc_status":14,"referenced_errors":[{"created":"@1595466086.698378311","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":244}]}]}]}"

**Screenshots**
![image](https://user-images.githubusercontent.com/37096176/88246821-3dc6f600-ccce-11ea-9769-09c2583f39b6.png)

**Env **
CentOS 7.6; huawei cloud
Docker version 19.03.12
docker-compose version 1.18.0

**Additional context**
telnet 10005 pass
toy example itself pass
telnet clustermanager 4670 pass

**Comment by JianhuanZeng** [comment]
应该是grpc那里的域名解析的问题，比如和云服务器的冲突，或者grpc连接中断了吗？

**Comment by LaynePeng** [comment]
> 应该是grpc那里的域名解析的问题，比如和云服务器的冲突，或者grpc连接中断了吗？

Thanks for updating. Close and marked for reference.
