### ISSUE TITLE
各组件是否支持arm？

### ISSUE THREAD

**Issue by gaojunjie03** [FederatedAI/KubeFATE#191]
我的机器是ubuntu 18.04 arm aarch64
在启动时（bash docker_deploy.sh all）
只启动了三个组件 并且状态一直在重启中 
查看组件的日志 docker logs ....
显示错误信息： standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by LaynePeng** [comment]
Currently, FATE is not support ARM yet.

**Comment by gaojunjie03** [comment]
> Currently, FATE is not support ARM yet.

Do you have any plans to support arm machines?

**Comment by LaynePeng** [comment]
> > Currently, FATE is not support ARM yet.
> 
> Do you have any plans to support arm machines?

As I know, Webank has some research tests and customizations on ARM in datacenter for better power efficiency. But still in early stage.

**Comment by LaynePeng** [comment]
Close the issue, cuz no support for ARM shortly
