### ISSUE TITLE
是否支持扩展部署节点

### ISSUE THREAD

**Issue by bukexiusi** [FederatedAI/KubeFATE#194]
假设原先按照docker部署的方式部署了三台机器
我现在想部署第四台机器
能不能在原先三台不重新部署的情况下
增加第四台机器的部署？

**Comment by LaynePeng** [comment]
Yes, but it need some config changes and network configurations. We suggest use Kubernetes in production cases, that support scaling easier.

**Comment by LaynePeng** [comment]
Close since has answered and no more questions. Reopen if necessary
