### ISSUE TITLE
[feature request] where is the chart of FATE

### ISSUE THREAD

**Issue by zrss** [FederatedAI/KubeFATE#197]
i can't find the chart of FATE in this repo, but i can find the chart file in release ... i'd like the chart of  FATE as the part of the repo, rather than it just be the release things

**Comment by LaynePeng** [comment]
The chart is hosted by Github page, so you can find it in branch gh-pages: https://github.com/FederatedAI/KubeFATE/tree/gh-pages

> i can't find the chart of FATE in this repo, but i can find the chart file in release ... i'd like the chart of FATE as the part of the repo, rather than it just be the release things

**Comment by zrss** [comment]
@LaynePeng , thx Peng
