### ISSUE TITLE
用docker-compose部署完集群后，在线推理返回的结果和示例不一致

### ISSUE THREAD

**Issue by tdye24** [FederatedAI/KubeFATE#209]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: linux
 - Version: Linux version 4.19.0-6.ucloud (root@9c2c92c4b542) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)) #1 SMP Wed Feb 12 08:20:34 UTC 2020

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 10

**To Reproduce**
按照docker-compose配置教程一步步走下来，前面的步骤以及返回结果均和示例一致，但是最后一步在线推理结果有出入

**What happen?**
最后一步在线推理结果有出入

**Screenshots**
![无标题](https://user-images.githubusercontent.com/38368472/90510383-79e65d00-e18d-11ea-81ae-7bec897ed7a7.png)

**Comment by LaynePeng** [comment]
cool, close this issue cuz new problem new issue created
