### ISSUE TITLE
The difference between load model and bind model

### ISSUE THREAD

**Issue by meijuanwang** [FederatedAI/KubeFATE#210]
I'd like to know the difference between load model and bind model. And where the model stores after tainning? where is the model stored after loading?

**Comment by owlet42** [comment]
KubeFATE is mainly responsible for the deployment of fate. You can get the knowledge of fate model from the source of [FATE](https://github.com/FederatedAI/FATE), or you can open a [FATE issue](https://github.com/FederatedAI/FATE/issues/new/choose).
