### ISSUE TITLE
How do I access the fateboard

### ISSUE THREAD

**Issue by SolinTao** [FederatedAI/KubeFATE#212]
hi, I tested the toy_example. How do I access the fateboard?

**Comment by LaynePeng** [comment]
What platform you're deploying FATE? Docker-compose or Kubernetes?

**Comment by SolinTao** [comment]
> What platform you're deploying FATE? Docker-compose or Kubernetes?

Kubernetes

**Comment by LaynePeng** [comment]
The FATE board should expose with ingress, with http://<party_id>.fateboard.<uri of ingress>. Please refer: https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube.md
