### ISSUE TITLE
用docker-compose做集群部署时，推理阶段发生错误，返回值为107，提示NET ERROR

### ISSUE THREAD

**Issue by tdye24** [FederatedAI/KubeFATE#213]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
KubeFATE 1.3

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - Ubuntu
 - 14.04

**Desktop (please complete the following information):**

**To Reproduce**
按照readme文档中的步骤一步一步走的，前面都和readme中一样，包括每一步该有什么返回值，只有最后一个推理发生107 NET ERROR

**What happen?**
推理阶段发生错误，返回值为107，提示NET ERROR

**Screenshots**
日志（提示的错误看不懂）：
![批注 2020-08-19 215858](https://user-images.githubusercontent.com/38368472/90644775-b8e8e100-e267-11ea-8459-8e651b1567c1.jpg)
推理返回结果：
![批注 2020-08-19 220101](https://user-images.githubusercontent.com/38368472/90644789-bbe3d180-e267-11ea-917f-f339df3022b3.jpg)

**Additional context**

**Comment by tdye24** [comment]
补充一下，我在用Postman和XShell测试推理功能的时候，偶尔有些时候，能正确返回结果，但是大多数时候都会出现107 NET ERROR

**Comment by jiahaoc1993** [comment]
could you please provide the log file of fate serving? maybe you should considerate the networking issues.

**Comment by tdye24** [comment]
> could you please provide the log file of fate serving? maybe you should considerate the networking issues.
Here is the fate-serving-server-error log in the container serving-9999_serving-server_1
![fate-serving-server-error-log](https://user-images.githubusercontent.com/38368472/90754300-4978fd00-e30c-11ea-9275-d162bdf5f9e2.jpg)

**Comment by LaynePeng** [comment]
It seems network connection failed between guest and host.

**Comment by tdye24** [comment]
> It seems network connection failed between guest and host.
有时候就可以正常推理（很少时候），有时候就报这个错误，是不是其他问题呢，比如处理推理请求的时候会不会出现问题？

**Comment by tdye24** [comment]
> It seems network connection failed between guest and host.

It seems network connection failed between guest and host.
有时候就可以正常推理（很少时候），有时候就报这个错误，是不是其他问题呢，比如处理推理请求的时候会不会出现问题？

**Comment by LaynePeng** [comment]
If network problem happening sometime, it probably not a deployment problem. It would be hardware problem: is your env. stable? or software problem, please try fate-serving 2.0. FATE-serving 2.0 will support soon.

**Comment by LaynePeng** [comment]
Close as no more comment and the report for previous version.
