### ISSUE TITLE
processor in session mate is not vaild

### ISSUE THREAD

**Issue by mangolzy** [FederatedAI/KubeFATE#226]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
FATE 1.4.3

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: centos
 - Version [待确认]
 - 16核

**Desktop (please complete the following information):**

**To Reproduce**
单个客户经常在evaluation组件发生这个问题，怀疑与特定机器有关系

**What happen?**

1. fateboard上报错：processor in session mate is not vaild
![image](https://user-images.githubusercontent.com/9247294/91925891-8d0a3880-ed08-11ea-8d90-d304d064c5ad.png)
2. guest 侧 .err文件全部是 /bin/bash: bin/eggroll_boot.sh: No such file or directory
    且确认 /data/projects/fate/eggroll/bin 下 .sh 文件丢失
    
    host 侧
[202009010652392894246.zip](https://github.com/FederatedAI/KubeFATE/files/5159929/202009010652392894246.zip)

![WeChatWorkScreenshot_363f5f9d-b200-4c95-850d-34b0ee94f861](https://user-images.githubusercontent.com/9247294/91928429-95657200-ed0e-11ea-9b88-0e15ca71b00a.png)

3. 重启可以恢复

**Screenshots**

**Additional context**
[fate_flow_schedule.log](https://github.com/FederatedAI/KubeFATE/files/5159883/fate_flow_schedule.log)
[DEBUG.log](https://github.com/FederatedAI/KubeFATE/files/5159886/DEBUG.log)
[ERROR.log](https://github.com/FederatedAI/KubeFATE/files/5159890/ERROR.log)

[202009010652392894246_evaluation_0_guest_33003.zip](https://github.com/FederatedAI/KubeFATE/files/5159893/202009010652392894246_evaluation_0_guest_33003.zip)

[202009010652392894246.zip](https://github.com/FederatedAI/KubeFATE/files/5159930/202009010652392894246.zip)

**Comment by jiahaoc1993** [comment]
Sorry for late reply, I will keep looking at this issue. Meanwhile, if you have any update please let me know.

**Comment by LaynePeng** [comment]
Close as report old version and no more update.
