### ISSUE TITLE
k8s fate-serving无法部署

### ISSUE THREAD

**Issue by wzg-zhuo** [FederatedAI/KubeFATE#230]
kubefate cluster install -f cluster-serving.yaml 后，job一直running，刚部署serving.yaml时候出现这个提示：invalid character '<' looking for beginning of value

**Comment by owlet42** [comment]
@wzg-zhuo 
This bug has been fixed.

Wait for a while and try again to avoid this problem.

**Comment by LaynePeng** [comment]
Close the issue, and please try the latest version released
