### ISSUE TITLE
toy-example不能通过

### ISSUE THREAD

**Issue by tdye24** [FederatedAI/KubeFATE#244]
![remmina_10 11 6 14_10 11 6 14_2020918-145514 515261](https://user-images.githubusercontent.com/38368472/93612630-4dc73180-fa02-11ea-999e-3e439201a1d5.png)
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
KubeFATE1.4.4 FATE-Serving2.0
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
Ubuntu

**Desktop (please complete the following information):**

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**
Clear the unexpected response.

**Screenshots**

**Additional context**

**Comment by owlet42** [comment]
@tdye24 
Please make sure both parties are working properly. Check whether one party is using `python run_toy_example.py 9999 9999 1`or`python run_toy_example.py 10000 10000 1`,

**Comment by yumiaoGitHub** [comment]
> @tdye24
> Please make sure both parties are working properly. Check whether one party is using `python run_toy_example.py 9999 9999 1`or`python run_toy_example.py 10000 10000 1`,
> Check whether the direct firewalls of the two hosts are turned off.

In real-life, the firewalls can't be turned off totally. If we enable firewall while open some ports, which ports should be specified to allow?
thanks~
