### ISSUE TITLE
 _Rendezvous of RPC that terminated StatusCode.UNAVAILABLE

### ISSUE THREAD

**Issue by yyqAlisa** [FederatedAI/KubeFATE#246]
在部署好KubeFate集群后，验证集群基本功能

 docker exec -it confs-10000_python_1 bash

 cd /data/projects/fate/python/examples/toy_example

 python run_toy_example.py 10000 9999 1

` failed to exec task, status:100, stderr is None stdout:{'retcode': 100, 'retmsg': 'rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "io exception"\n\tdebug_error_string = "{"created":"@1601147707.426782344","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"\n>'}`

请问如何解决阿？

**Comment by yyqAlisa** [comment]
[root@node-1 docker-deploy]# docker exec -it confs-10000_python_1 bash
(venv) [root@05a9c195d46b python]# cd /data/projects/fate/python/examples/toy_example
(venv) [root@05a9c195d46b toy_example]# python run_toy_example.py 10000 9999 1
stdout:{
    "retcode": 100,
    "retmsg": "rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"io exception\"\n\tdebug_error_string = \"{\"created\":\"@1601150641.318923659\",\"description\":\"Error received from peer\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1017,\"grpc_message\":\"io exception\",\"grpc_status\":14}\"\n>"
}


Traceback (most recent call last):
  File "run_toy_example.py", line 197, in <module>
    exec_toy_example(runtime_config)
  File "run_toy_example.py", line 161, in exec_toy_example
    jobid = exec_task(dsl_path, runtime_config)
  File "run_toy_example.py", line 91, in exec_task
    "failed to exec task, status:{}, stderr is {} stdout:{}".format(status, stderr, stdout))
ValueError: failed to exec task, status:100, stderr is None stdout:{'retcode': 100, 'retmsg': 'rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "io exception"\n\tdebug_error_string = "{"created":"@1601150641.318923659","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"\n>'}
(venv) [root@05a9c195d46b toy_example]#

**Comment by zolagz** [comment]
yum -y update 

重启之后，在启动KubeFate  再次测试，success！！！

**Comment by LaynePeng** [comment]
> yum -y update
> 
> 重启之后，在启动KubeFate 再次测试，success！！！

Cool, thanks for the updated
