### ISSUE TITLE
集群重启报错：Connection refused, Please check if the fate flow service is started

### ISSUE THREAD

**Issue by liuguangjun12011** [FederatedAI/KubeFATE#247]
stdout:{
    "retcode": 100,
    "retmsg": "Connection refused, Please check if the fate flow service is started"
}

Traceback (most recent call last):
  File "run_toy_example.py", line 197, in <module>
    exec_toy_example(runtime_config)
  File "run_toy_example.py", line 161, in exec_toy_example
    jobid = exec_task(dsl_path, runtime_config)
  File "run_toy_example.py", line 91, in exec_task
    "failed to exec task, status:{}, stderr is {} stdout:{}".format(status, stderr, stdout))
ValueError: failed to exec task, status:100, stderr is None stdout:{'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

重新部署是可以解决
bash docker_deploy.sh all --training
 bash docker_deploy.sh all --serving
这样就可以解决。但是根本原因不知道，求大神告知

**Comment by liuguangjun12011** [comment]
系统环境：ubuntu18.04

**Comment by liuguangjun12011** [comment]
系统环境：ubuntu18.04

**Comment by liuguangjun12011** [comment]
系统环境：ubuntu18.04
目前我尝试分别在两节点 
/data/projects/fate/confs-9999
/data/projects/fate/serving-10000
执行docker-compose restart

再运行python run_toy_example.py 10000 9999 1 没报错了。
我也不知道这样对不对。

**Comment by owlet42** [comment]
@liuguangjun12011 
The startup of fateflow server depends on the initialization of MySQL. When MySQL is initializing, the fateflow server waits for MySQL to complete, and this error will appear.
Just wait for MySQL initialization to complete after deployment, and this error will not occur.

**Comment by LaynePeng** [comment]
Close the expired issue, cuz it has explained.
