### ISSUE TITLE
fateboard点击component无响应

### ISSUE THREAD

**Issue by water3345** [FederatedAI/KubeFATE#250]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
kubefate version=v1.4.3

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: SUSE
 - Version 12.3

**Desktop (please complete the following information):**
 - OS: Window7
 - Browser chrome
 - Version 59.0

**To Reproduce**
使用我方自己的数据跑通secureboost模型，未修改结构只调整了模型训练迭代次数，并成功使用该模型进行预测

**What happen?**
使用fateboard查看模型的参数时，点击对应main graph中component无响应；且点击以往历史记录中其他main graph中的component同样无响应。模型刚完成预测，还可以使用fateboard正常查看，但过了一会就出问题了。

**Screenshots**
![WechatIMG266](https://user-images.githubusercontent.com/55197247/94529231-0b0c2180-026c-11eb-97e3-b01a35d5a3bb.jpeg)

**Additional context**
因为框架中confs-9999_modemange_1产生大量僵尸进程，所以关掉了该container。但是fateboard出问题在关掉该container数小时之后，不知道有没有关联。

**Comment by jiahaoc1993** [comment]
The zombie problem should be wiped out right now. Maybe you can use other browser and try again.
