### ISSUE TITLE
Data loss during the training of huge dataset

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/KubeFATE#251]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
1.4.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: centos
 - Version 7.0

**To Reproduce**
Train with huge dataset

**What happen?**
Scripts under `/data/projects/fate/eggroll/bin` of node manager container will be removed unexpectedly

**Comment by LaynePeng** [comment]
Close as report a old version and no more update.
