### ISSUE TITLE
docker-compose模式下执行Load model不成功

### ISSUE THREAD

**Issue by luyilong2015** [FederatedAI/KubeFATE#256]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.4.5
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: 
 - Version 

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser  chrome
 - Version 

**To Reproduce**
按照https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy所述的步骤，执行到
Load model
$ python fate_flow_client.py -f load -c examples/publish_load_model.json
这一步时，无法执行成功。
**What happen?**
`(venv) [root@63e940d0a135 fate_flow]# python fate_flow_client.py -f load -c examples/publish_load_model.json
{
    "data": {
        "detail": {
            "guest": {
                "9999": {
                    "retcode": 100,
                    "retmsg": "<_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1603097255.546419830\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3528,\"referenced_errors\":[{\"created\":\"@1603097255.546258296\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":399,\"grpc_status\":14}]}\"\n>"
                }
            },
            "host": {
                "10000": {
                    "retcode": 100,
                    "retmsg": "<_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1603097256.638659645\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3528,\"referenced_errors\":[{\"created\":\"@1603097256.638558922\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":399,\"grpc_status\":14}]}\"\n>"
                }
            }
        },
        "guest": {
            "9999": 100
        },
        "host": {
            "10000": 100
        }
    },
    "jobId": "2020101908473449322810",
    "retcode": 101,
    "retmsg": "failed"
}
`
**Screenshots**
![image](https://user-images.githubusercontent.com/30279457/96426037-4a0c1200-122f-11eb-8514-9905232a8bae.png)

**Additional context**

**Comment by cll24** [comment]
同遇到如上问题，请问解决了吗

**Comment by luyilong2015** [comment]
> 同遇到如上问题，请问解决了吗

没有解决，放弃了使用这种安装方式，采用native安装 了。

**Comment by jiahaoc1993** [comment]
please check your iptable policy to make sure these services can access each other.
