### ISSUE TITLE
怎么批量预测啊，还是只能想办法一个个去调用推断服务接口呢？

### ISSUE THREAD

**Issue by Song-xx** [FederatedAI/KubeFATE#260]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What KubeFATE and FATE version you are using?  ** 1.4.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: ubuntu
 - Version 20.04

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 20.04

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**
Clear the unexpected response.

**Screenshots**

**Additional context**

**Comment by jiahaoc1993** [comment]
https://github.com/FederatedAI/FATE/blob/master/python/fate_flow/examples/test_predict_conf.json
