### ISSUE TITLE
{"code":110,"message":"SYSTEM_ERROR"}

### ISSUE THREAD

**Issue by xyc1998** [FederatedAI/KubeFATE#262]
最后一步模型参数绑定完成之后，curl推理的时候报错{"code":110,"message":"SYSTEM_ERROR"}

**Comment by jiahaoc1993** [comment]
please check the log of the serving server

**Comment by jiahaoc1993** [comment]
@xyc1998 we just updated the document a little bit, please check if [this](https://github.com/FederatedAI/KubeFATE/commit/7e50f2da33fbc25cabade298384eff36bddf2587) can help
