### ISSUE TITLE
发现《使用Docker Compose 部署 FATE》的小问题

### ISSUE THREAD

**Issue by furuifr** [FederatedAI/KubeFATE#268]
**What deployment mode you are use?  **
 - docker-compose;

**What KubeFATE and FATE version you are using?  **
 - v1.4.4

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - Ubuntu18.04

**What happen?**

1. 数据集使用错误
截止至2020.11.14的文档中
Host方操作: `$ vi examples/upload_host.json`
```
{
  "file": "examples/data/breast_hetero_host.csv",
  "head": 1,
  "partition": 10,
  "work_mode": 1,
  "namespace": "fate_flow_test_breast",
  "table_name": "breast"
}
```
Guest方操作: `$ vi examples/upload_guest.json`
```
{
  "file": "examples/data/breast_hetero_host.csv",
  "head": 1,
  "partition": 10,
  "work_mode": 1,
  "namespace": "fate_flow_test_breast",
  "table_name": "breast"
}
```
我尝试了两次这样提交任务，发现任务会失败
 ![微信截图_20201114172029](https://user-images.githubusercontent.com/30371036/99144073-b5fe6080-269d-11eb-80f0-2f70df3c6a53.png)
再将Guest方操作的数据集修改后，该问题解决
`$ vi examples/upload_guest.json`
```
{
  "file": "examples/data/breast_hetero_guest.csv",
  "head": 1,
  "partition": 10,
  "work_mode": 1,
  "namespace": "fate_flow_test_breast",
  "table_name": "breast"
}
```

2. 在线测试时，截止至2020.11.14的文档中写的是发送到{SERVING_SERVICE_IP}，并附上实例：
```
$ curl -X POST -H 'Content-Type: application/json' -i 'http://192.168.7.1:8059/federation/v1/inference' --data '{
  "head": {
    "serviceId": "test"
  },
  "body": {
    "featureData": {
      "x0": 0.254879,
      "x1": -1.046633,
      "x2": 0.209656,
      "x3": 0.074214,
      "x4": -0.441366,
      "x5": -0.377645,
      "x6": -0.485934,
      "x7": 0.347072,
      "x8": -0.287570,
      "x9": -0.733474
    },
    "sendToRemoteFeatureData": {
      "id": "123"
    }
  }
}'
```
我依照这个提交后报错：`{"retmsg":"remote rpc exception","retcode":105}`
经过与技术人员交流，此处应该是向guest方发送请求，所以上面代码中的地址应该改为192.168.7.2。经过修改后，正常运行。

**Comment by jiahaoc1993** [comment]
resolve by #269 , thanks for the report
