### ISSUE TITLE
Failed when helm installing for each namespace

### ISSUE THREAD

**Issue by Chenfengldw** [FederatedAI/KubeFATE#27]
When runing:
`helm install --name=fate-10000 --namespace=fate-10000 ./fate-10000/`
got:

> Error: release fate-10000 failed: namespaces "fate-10000" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "fate-10000"

It is because tiller pod do not have the authority to access resources in each namespace?

**Comment by Chenfengldw** [comment]
Following Issue in helm solved this problem, **we should create an account for deploying tiller**
https://github.com/helm/helm/issues/3130#issuecomment-372931407

**Comment by LordGoodman** [comment]
Hi @Chenfengldw, thank you for reporting the issue, we will verify your solution as soon as possible

**Comment by jiahaoc1993** [comment]
Thanks for reporting the issue, now close.
