### ISSUE TITLE
generate_config.sh has issue on 1.5

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#272]
https://github.com/FederatedAI/KubeFATE/blob/ba4531fea01cfeac96977e1404ebd945b1aeb6ac/docker-deploy/generate_config.sh#L271

the folder docker-example-dir-tree and docker-example-dir-tree/proxy/ are no longer exist in kubefate 1.5

**Comment by jiahaoc1993** [comment]
fixed by #273, thanks for the report.
