### ISSUE TITLE
Serving RPC 105 问题

### ISSUE THREAD

**Issue by Paul0M** [FederatedAI/KubeFATE#284]
docker-compose
1.5.0 LTS
 # 一：

IPA: 10001  guest  experiment.breast_hetero_guest
IPB: 10002  host    experiment.breast_hetero_host
IPC: 10003  arbiter
从IPA发起任务

无需训练，直接随意请求推理：curl 发现105报错
仔细看proxy中flow.log 发现：time | IP | hash | **9999** | 105 | 6 | 0 inference | serving-proxy:8869，但是前面parties.conf中设定的是10001-10003

# 二：结论
似乎：serving的时候9999是写死在某个地方了,curl请求时guest只会是9999。所以以9999为guest发起训练和serving则可以走通全流程

将#coordinator=9999，取消注释，改变为对应IP所对应的party_id即可。
https://github.com/FederatedAI/KubeFATE/blob/dfb4a8897181c880f805ccff7970a2bd0c0b5ddc/docker-deploy/serving_template/docker-serving/serving-proxy/conf/application.properties#L17

# 最终解决方法：
修改对应行为
```
sed -i "s/#coordinator=9999/coordinator=${party_id}/g" ./serving-$party_id/confs/serving-proxy/conf/application.properties
```

https://github.com/FederatedAI/KubeFATE/blob/dfb4a8897181c880f805ccff7970a2bd0c0b5ddc/docker-deploy/generate_config.sh#L342

**Comment by jiahaoc1993** [comment]
Thank you for your report ! we will fix soon.

**Comment by KleinXin** [comment]
Same error. I tried to modify files in ./outputs/serving-10000.tar and ./outputs/serving-9999.tar as suggestted by @Paul0M , then re-tar the folders and run `bash` docker_deploy.sh all` .
However, it still cannot do the prediction successfully. The return message is shown below.

`{"retcode":0,"retmsg":"","data":{"modelId":"guest#9999#arbiter-10000#guest-9999#host-10000#model","modelVersion":"202011260931348495152","timestamp":1606383450494},"flag":0}`

Any help is appreciated!

**Comment by jiahaoc1993** [comment]
@KleinXin Which example did you run? Currently the "fate-serving" does not support "pipeline 2.0", please make sure you did not use that to build training pipeline.

**Comment by KleinXin** [comment]
> @KleinXin Which example did you run? Currently the "fate-serving" does not support "pipeline 2.0", please make sure you did not use that to build training pipeline.

Do you mean that I should delete ""dsl_version":"2"" in file `test_hetero_lr_job_conf.json`？

![image](https://user-images.githubusercontent.com/13084622/100415403-08d11280-30b7-11eb-91a5-4b8ac8f56079.png)

**Comment by jiahaoc1993** [comment]
Not only delete such line, you should replace the pipeline with 1.0 version.

**Comment by jiahaoc1993** [comment]
https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README.md#modify-examplestest_hetero_lr_job_confjson

**Comment by KleinXin** [comment]
> Not only delete such line, you should replace the pipeline with 1.0 version.

I tried to delete that line about 1 hour ago, it gave me some error saying that some parameter is missing.

I think it still has some bugs with version 1.5. So I decide to use version 1.4 instead.

**Comment by KleinXin** [comment]
After scrollbacking the version to 1.4.5, online serving test can give a score which seems makes sense. However, it is quite different from the value on webpage which is only about 0.3. Another problem is that 'retmsg' param is still empty. The return information is shown below. Can I continue the experiments with the data of my own?

`{"retcode":0,"retmsg":"","data":{"score":0.999907373088982,"modelId":"guest#9999#arbiter-10000#guest-9999#host-10000#model","modelVersion":"202011270755473191482","timestamp":1606463988595},"flag":0}`

**Comment by dannis97500** [comment]
After update it, FATE1.5.0 inference also have bug. The inference score always 0.0.
`{"retcode":0,"retmsg":"","data":{"score":0.0,"modelId":"guest#9999#arbiter-10000#guest-9999#host-10000#model","modelVersion":"2020112804252183713219","timestamp":1606538030096},"flag":0}`

I test 9999 as guest and 10000 as guest.

**Comment by jiahaoc1993** [comment]
@KleinXin I think you are good to go with your experiments, since that score is for reference only.

**Comment by jiahaoc1993** [comment]
@dannis97500 Did you use pipeline version 2 to define your job?

**Comment by dannis97500** [comment]
@jiahaoc1993 I deploy FATE 1.5.0. I use the version 1 to define the job. [https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy]
But at the end of step, I always get 0 score.
And then I use flow in client can predict batch data, successfully.[DSL version2.0]
In pipeline way, I don't find the right way to do it. Can you give me some advice?
[In pipeline way, I use the way of docker deploy in 3 machine. I have the container named confs-10000_client_1. ]

**Comment by KleinXin** [comment]
> @KleinXin I think you are good to go with your experiments, since that score is for reference only.

I used breast_hetero_guest to run test today. The prediction scores are the same for different ids, so I think the trainning of the model still has some problems.

![image](https://user-images.githubusercontent.com/13084622/100610305-69c44900-334a-11eb-8df4-4d454e1f9c2b.png)

**Comment by jiahaoc1993** [comment]
@dannis97500 just follow our [readme](https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy) it used the pipeline 1.0 to define job.
