### ISSUE TITLE
修改fate主机IP后无法打开fateboard8080界面

### ISSUE THREAD

**Issue by WillJiang12** [FederatedAI/KubeFATE#308]
修改IP后是否还要修改哪些docker的配置？

**Comment by WillJiang12** [comment]
发起集群服务验证时报错如下：
（ shell）python run_toy_example.py  9999 10000 1


stdout:{
    "retcode": 100,
    "retmsg": "Please check if the fate flow server of the other party is started. rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"io exception\"\n\tdebug_error_string = \"{\"created\":\"@1608878771.892744947\",\"description\":\"Error received from peer ipv4:192.167.0.6:9370\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1052,\"grpc_message\":\"io exception\",\"grpc_status\":14}\"\n>"
}

**Comment by owlet42** [comment]
Please specify how to modify it

**Comment by LaynePeng** [comment]
Close as no more update in this thread.
