### ISSUE TITLE
Deploy Port.

### ISSUE THREAD

**Issue by VeasonF** [FederatedAI/KubeFATE#315]
**Is your feature request related to a problem? Please describe.**
When I use docker-deploy kubeFATE on my cluster ,my 8080port is unavailable, so I change the dashboard service to port 8081 by modify the image config and restart my docker and containers, then mysql service is down, it falls to loop of restart, I use "rm -rf *"to solve it, but it may still be some other problems.

**Describe the solution you'd like**
I'd like suggest a changebale port for this service, maybe it could be in parties.conf? Just a suggest, it will be more convenient.

**Comment by LaynePeng** [comment]
I think you should define the ports of service in: https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/generate_config.sh
