### ISSUE TITLE
Exchange Server Load Balance mechanism

### ISSUE THREAD

**Issue by lalalapotter** [FederatedAI/KubeFATE#319]
**Is your feature request related to a problem? Please describe.**
 In actual industrial use, we found that deploying only one exchange server will cause the data of multiple tasks to be forwarded through the single exchange server, resulting in lower performance and possible single point of failure. Therefore, we propose to add the load balancing mechanism of the exchange server on the original basis to avoid the above problems.
**Describe the solution you'd like**
We will submit a proposal to add this feature.
**Describe alternatives you've considered**

**Additional context**

**Comment by lalalapotter** [comment]
@jiahaoc1993 @LaynePeng Please check, thx! :)

**Comment by LaynePeng** [comment]
Ref: https://github.com/FederatedAI/KubeFATE/pull/332
