### ISSUE TITLE
AWS K8S平台部署Kubefate配置自定义域名无效

### ISSUE THREAD

**Issue by moyerlee** [FederatedAI/KubeFATE#336]
我在AWS的EKS（云上K8S服务）上部署了Kubefate，ingress使用云上的负载均衡服务，配置自定义域名，但是使用kubefate 命令创建cluster的时候不生效，还是kubefate.net的域名，导致无法访问fateboard web页面

**Comment by LaynePeng** [comment]
This issue have been fixed in the latest release: [KubeFATE v1.5.0-b](https://github.com/FederatedAI/KubeFATE/releases/tag/v1.5.0-b)

**Comment by moyerlee** [comment]
federatedai/kubefate:v1.3.0 的docker镜像无法拉取

**Comment by LaynePeng** [comment]
v1.5.0-b只有helm chart的更新。按照https://github.com/FederatedAI/KubeFATE/releases/tag/v1.5.0-b 说明那样更改cluster.yaml即可。不需要更新kubefate的服务和CLI。沿用v1.5.0里的即可。kubefate服务及命令行的v1.3.0版本会在v1.5.1一起发布

**Comment by LaynePeng** [comment]
> federatedai/kubefate:v1.3.0 的docker镜像无法拉取

v1.5.0-b只有helm chart的更新。按照https://github.com/FederatedAI/KubeFATE/releases/tag/v1.5.0-b 说明那样更改cluster.yaml即可。不需要更新kubefate的服务和CLI。沿用v1.5.0里的即可。kubefate服务及命令行的v1.3.0版本会在v1.5.1一起发布

**Comment by LaynePeng** [comment]
> > federatedai/kubefate:v1.3.0 的docker镜像无法拉取
> 
> v1.5.0-b只有helm chart的更新。按照https://github.com/FederatedAI/KubeFATE/releases/tag/v1.5.0-b 说明那样更改cluster.yaml即可。不需要更新kubefate的服务和CLI。沿用v1.5.0里的即可。kubefate服务及命令行的v1.3.0版本会在v1.5.1一起发布

也可以单独下载v1.5.0-b中的helm chart使用https://github.com/FederatedAI/KubeFATE/blob/master/docs/Manage_FATE_and_FATE-Serving_Version.md 的方法手动管理版本
