### ISSUE TITLE
ingress address not apply

### ISSUE THREAD

**Issue by JanYunkai** [FederatedAI/KubeFATE#346]
**What deployment mode you are use?  **
 Kuberentes.

**What KubeFATE and FATE version you are using?  **
1.5.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: CentOS
 - Version 7.7

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version  20.04

**To Reproduce**
```
kubectl apply -f kubefate.yaml
kubectl get all,ingress -n kube-fate


NAME                          HOSTS          ADDRESS   PORTS   AGE
ingress.extensions/kubefate   kubefate.net             80      18m
 
```

**What happen?**
ingress can`t apply a address,
```
kubefate version

* kubefate service connection error, Post http://kubefate.net/v1/user/login: dial tcp: lookup kubefate.net on 10.21.137.3:53: no such host
* kubefate commandLine version=v1.2.0
```

**Screenshots**

**Additional context**

**Comment by JanYunkai** [comment]
ignore， my fault

**Comment by wonder2025** [comment]
> ignore， my fault

用的vmware虚拟机部署的，遇到了同样的问题，请问如何解决的呢？

**Comment by JanYunkai** [comment]
> > ignore， my fault
> 
> 用的vmware虚拟机部署的，遇到了同样的问题，请问如何解决的呢？

ingress controller没有导致的，如果采用kubeadmin 安装的集群（rancher安装的话会给你默认安装一个nginx controller）是没有ingress controller 的，你得自己装一个。这个时候ingress就有地址了。
