### ISSUE TITLE
k8s 1.15 ingress 80端口如何配置

### ISSUE THREAD

**Issue by JanYunkai** [FederatedAI/KubeFATE#352]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **

KubeFATE

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: centos
 - Version 7.6
**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version 88

**To Reproduce**

kubefate.net 需要80端口

**What happen?**

ingress 需要一个NodePort Services，否则不会进入就绪状态.
开启NodePort Services 端口是随机的
需要
kubefate.net:30068 才能访问到

能提供一个ingress配置相关的教程，或者修改kubefate调用的url的方法吗
**Screenshots**

```
NAME                          HOSTS          ADDRESS   PORTS   AGE
ingress.extensions/kubefate   kubefate.net             80      79m

* kubefate service connection error, Post http://kubefate.net/v1/user/login: dial tcp xx.xx.xx.xx:80: connect: connection refused
* kubefate commandLine version=v1.2.0


```

**Additional context**

**Comment by JanYunkai** [comment]
安装了ingress-nginx-controller
设置了
hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

问题解决了

**Comment by wonder2025** [comment]
> hostNetwork: true
> dnsPolicy: ClusterFirstWithHostNet

请问这个添加到哪里呢，我添加以后还是报错：
 write udp 192.168.183.130:50651->10.96.0.10:53: write: operation not permitted

**Comment by JanYunkai** [comment]
> > hostNetwork: true
> > dnsPolicy: ClusterFirstWithHostNet
> 
> 请问这个添加到哪里呢，我添加以后还是报错：
> write udp 192.168.183.130:50651->10.96.0.10:53: write: operation not permitted

添加到ingress controller 的deploy.yaml文件里的。我采用的事nginx-ingress

**Comment by JanYunkai** [comment]
deploy.yaml

`

`

> > hostNetwork: true
> > dnsPolicy: ClusterFirstWithHostNet
> 
> 请问这个添加到哪里呢，我添加以后还是报错：
> write udp 192.168.183.130:50651->10.96.0.10:53: write: operation not permitted

如果官方可以提供一个ingress controller的deploy那也是极好的。

**Comment by JanYunkai** [comment]
如果通过jupter上传文件失败，多半是nginx配置的运行文件上传大小，太小导致的。

https://github.com/kubernetes/ingress-nginx/issues/4825

这里可以解决。
