### ISSUE TITLE
kubefate service connection error, invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by vdamojip24** [FederatedAI/KubeFATE#368]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
v1.3.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
Ubuntu 18.04 LTS

**Desktop (please complete the following information):**
 MacOS 10.15.7 

**To Reproduce**
git clone https://github.com/FederatedAI/KubeFATE.git
cd KubeFATE/k8s-deploy
kubectl apply -f ./rbac-config.yaml
kubectl apply -f ./kubefate.yaml
go build -o bin/kubefate kubefate.go
kubefate version

followed commands from this link: https://github.com/FederatedAI/KubeFATE/blob/master/docs/KubeFATE_command_line_user_guide.md

**What happen?**

* kubefate commandLine version=v1.3.0
* kubefate service connection error, invalid character '<' looking for beginning of value

**Screenshots**

k8s@da11-k8s-master:~/KubeFATE/k8s-deploy$ kubefate cluster install -f ./cluster.yaml
invalid character '<' looking for beginning of value
k8s@da11-k8s-master:~/KubeFATE/k8s-deploy$ kubefate version
* kubefate commandLine version=v1.3.0
* kubefate service connection error, invalid character '<' looking for beginning of value

**Additional context**
Our goal is to install kubefate on 3 separate kubernetes clusters in 3 different data centers.

**Comment by asdfsx** [comment]
add kubefate.net to /etc/hosts

```
$ kubectl get ingress -n kube-fate
NAME       HOSTS          ADDRESS          PORTS   AGE
kubefate   kubefate.net   192.168.99.110   80      59m
$ sudo -- sh -c "echo \"192.168.99.110 kubefate.net\"  >> /etc/hosts"

$ ping -c 2 kubefate.net
PING kubefate.net (192.168.99.110): 56 data bytes
64 bytes from 192.168.99.110: icmp_seq=0 ttl=64 time=1.305 ms
64 bytes from 192.168.99.110: icmp_seq=1 ttl=64 time=0.409 ms

--- kubefate.net ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.409/0.857/1.305/0.448 ms
```

**Comment by Oak-Ling** [comment]
We added kubefate.net to /etc/hosts, but now we get this new error:

 

k8s@da11-k8s-master: kubectl get ingress -n kube-fate
NAME       CLASS    HOSTS          ADDRESS   PORTS   AGE
kubefate   <none>   kubefate.net             80      6d1h
k8s@da11-k8s-master:~/KubeFATE$ ping -c 2 kubefate.net
PING kubefate.net (192.168.99.110) 56(84) bytes of data.
^C
--- kubefate.net ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1032ms

 

k8s@da11-k8s-master:~/KubeFATE$ kubefate version
kubefate commandLine version=v1.3.0
kubefate service connection error, Post http://localhost:8080/v1/user/login: dial tcp [::1]:8080: connect: connection refused

 

 

Do we need to install an ingress server?

**Comment by asdfsx** [comment]
1. Install ingress

2. Check which port does ingress export

![image](https://user-images.githubusercontent.com/2292716/111459813-27d2dd80-8756-11eb-98c2-dbea92b6d6b6.png)

3. update `config.yaml`
```
![image](https://user-images.githubusercontent.com/2292716/111459903-476a0600-8756-11eb-9727-1e23ff5a4af4.png)

```

**Comment by mehreentahir16** [comment]
I'm facing the same issue for the same OS specs except that the kubefate commandLine version is v1.4.1. 
I've tried adding kubefate.net to /etc/hosts and the ping is successful but the error remains the same. Any other work around it?

**Comment by sunyinggang** [comment]
@mehreentahir16 我碰到了和你一样的问题，你要先考虑是否已经部署ingress-nginx，如果已经部署ingress-nginx，查看端口映射，然后修改xonfig.yaml文件就可以成功，我说的就是 @asdfsx 提供的方案，这种方案时可行的

**Comment by bob-fly** [comment]
我也碰到了类似的问题，是第一步部署的kubefate的端口不通导致的

**Comment by Cp99nice** [comment]
请问你是怎么解决的

**Comment by gegose** [comment]
If you are trying to access from host machine you could have to create port forwarding:

```shell
$ kubectl port-forward --namespace=ingress-nginx service/ingress-nginx-controller 8080:80
```

**Comment by owlet42** [comment]
Change the log level of `config.yaml` to debug to see more details, check if the native host is configured (ingress URL and IP are written to the host file)

**Comment by jx1239614362** [comment]
I'm facing the same issue 
#### Centos Stream8  
#### kubefate commandLine version is v1.4.3.
I use the method from @asdfsx but the problem still exists
Update config.yaml is useless
#### problem 
    Post "http://localhost:8080/v1/user/login": dial tcp [::1]:8080: connect: connection refused

**Comment by JingChen23** [comment]
Cannot repro the issue with Kubefate v1.5.3 / v1.7.2 / v1.8.0, close the issue now, please feel free to reopen if you could reproduce the issue on the previous 3 versions, thanks.
