### ISSUE TITLE
kubefate linux compatibility issues

### ISSUE THREAD

**Issue by sharelinux** [FederatedAI/KubeFATE#372]
**What deployment mode you are use?  **
- Kuberentes.

**What KubeFATE and FATE version you are using?  **
- KubeFATE v1.3.0
- FATE v1.5.1

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - Using: Kubernetes v1.19.8
 - OS: CentOS Linux release 7.4.1708 (Core)
 - Version: 7.4.1708

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2 (20D64)
 - Browser Chrome 
 - Version: 87.0.4280.88（正式版本）(x86_64)

**To Reproduce**
```sh
mkdir -pv ~/kubefate-k8s
wget -O ~/kubefate-k8s/kubefate-k8s-v1.5.1.tar.gz https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.1/kubefate-k8s-v1.5.1.tar.gz
tar -xvf ~/kubefate-k8s/kubefate-k8s-v1.5.1.tar.gz -C ~/kubefate-k8s
~/kubefate-k8s/kubefate
```

> 错误信息: /root/kubefate-k8s/kubefate: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/kubefate-k8s/kubefate)

- 分析kubefate二进制程序动态库依赖
ldd ~/kubefate-k8s/kubefate
/root/kubefate-k8s/kubefate: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/kubefate-k8s/kubefate)
    linux-vdso.so.1 =>  (0x00007fffb01cc000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fccd2bcf000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007fccd29cb000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fccd25fc000)
    /lib64/ld-linux-x86-64.so.2 (0x0000563883d9f000)

**What happen?**
- Kubefate runs an error and depends on a higher version of glibc.
- kubefate is not compatible with centos version.

**Screenshots**
Screenshot of kubefate phenomenon
![kubefate-issue](http://images.sharelinux.com/kubefate-issue01.png)

**Additional context**
```sh
[root@k8s-node01 ~]# uname -a
Linux k8s-node01 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@k8s-node01 ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by sharelinux** [comment]
### The dependency problem of kubefate has been solved and compiled to a statically compiled binary package.
![kubefate-fixbug](http://images.sharelinux.com/kubefate-fixbug.png)

**Comment by LaynePeng** [comment]
Cool issue. Close it as the PR merged
