### ISSUE TITLE
使用toy_example作测试时，最后出现这个问题，怎么解决呢？

### ISSUE THREAD

**Issue by DuJiahao1996** [FederatedAI/KubeFATE#380]
**What deployment mode you are use?  **
docker-compose1.3

**What KubeFATE and FATE version you are using?  **
两个都没有用

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: linux centos 7

**Desktop (please complete the following information):**
 - OS: centos 7
 - Browser firefox

**To Reproduce**
参照https://blog.csdn.net/qq_42906753/article/details/105139335?spm=1001.2014.3001.5502 的步骤，作toy_example测试时最后出现问题

**What happen?**
一个文档找不到

**Screenshots**
![image](https://user-images.githubusercontent.com/81151060/111965430-b1a4f100-8b30-11eb-97f6-3d24dab6c362.png)

**Comment by FireEaet** [comment]
我也出现了这个问题，不知道是不是python版本问题？

**Comment by heexu976** [comment]
我也是这个，成功了一次，之后一直都失败。

**Comment by JingChen23** [comment]
Well, that blog is a little obsolete, and the version is not a long time supported version, could we try the latest tutorial?

https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube.md

We have limited bandwidth to install that old version and reproduce the issue, please understand.
I will close this issue and feel free to open a new one if the latest tutorial doesn't work, thanks!
