### ISSUE TITLE
looks like "https://federatedai.github.io/KubeFATE/" is not a valid chart repository or cannot be reached: Get "https://federatedai.github.io/KubeFATE/index.yaml": dial tcp 0.0.0.0:443: connect: connection refused

### ISSUE THREAD

**Issue by huyz1117** [FederatedAI/KubeFATE#394]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
kubefate-k8s-v1.3.0-a
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: Ubuntu18.04
 - Version:18.04

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**To Reproduce**
按照[这个教程](https://zhuanlan.zhihu.com/p/140469171)进行k8s部署时，在进行`kubefate cluster install -f ./fate-9999.yaml`这个操作时，通过以下命令`kubefate job ls 88c0eee3-c0a3-48bf-a058-474cf167ae6c`查看时状态为failed,

**What happen?**
使用kubefate cluster install来部署两个fate集群出现错误

**Screenshots**
<img width="607" alt="捕获" src="https://user-images.githubusercontent.com/45112669/113805732-a1794c80-9793-11eb-94c2-a066fbf6ec92.PNG">
<img width="827" alt="捕获1" src="https://user-images.githubusercontent.com/45112669/113805738-a211e300-9793-11eb-88bf-d79aee124609.PNG">
<img width="824" alt="捕获2" src="https://user-images.githubusercontent.com/45112669/113805740-a2aa7980-9793-11eb-8945-53b98d8215b4.PNG">

**Comment by owlet42** [comment]
It seems that you cannot access "github.io", you can deploy a new version, and then use chart upload to manually upload the chart file.
New version of the guide: https://github.com/FederatedAI/KubeFATE/wiki/%E4%BD%BF%E7%94%A8KubeFATE%E5%9C%A8Kubernetes%E4%B8%8A%E9%83%A8%E7%BD%B2%E8%81%94%E9%82%A6%E5%AD%A6%E4%B9%A0%E9%9B%86%E7%BE%A4%EF%BC%88v1.5.0%E7%89%88%E6%9C%AC%EF%BC%89
chart upload: https://github.com/FederatedAI/KubeFATE/blob/master/docs/KubeFATE_command_line_user_guide.md#upload

**Comment by LaynePeng** [comment]
Seems duplicate with https://github.com/FederatedAI/KubeFATE/issues/403 ?

**Comment by huyz1117** [comment]
> Seems duplicate with #403 ?
已解决，是网络问题，谢谢

**Comment by LaynePeng** [comment]
Cool, so I close this issue.
