### ISSUE TITLE
failed to download "kubefate/fate" (hint: running `helm repo update` may help)

### ISSUE THREAD

**Issue by huyz1117** [FederatedAI/KubeFATE#403]
**What deployment mode you are use?  **
 Kuberentes.

**What KubeFATE and FATE version you are using?  **
kubefate:1.4.0
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS:Centos7

**Desktop (please complete the following information):**

**To Reproduce**
在两个k8s（一主两从）集群上使用kubefate部署fate时，在使用`kubefate cluster install -f ./cluster-A.yaml`部署fate时，出现如下错误：`failed to download "kubefate/fate" (hint: running `helm repo update` may help)`。部署过程参考这个[教程](https://blog.csdn.net/qq_42906753/article/details/106254555)

**What happen?**
Clear the unexpected response.

**Screenshots**
错误截图：
<img width="824" alt="捕获" src="https://user-images.githubusercontent.com/45112669/114857845-55757a00-9e1b-11eb-9998-9b0c8417b938.PNG">
cluster.yaml部分代码：
<img width="207" alt="捕获1" src="https://user-images.githubusercontent.com/45112669/114858345-eea49080-9e1b-11eb-8350-36b908bb1fb3.PNG">

**Additional context**

**Comment by huyz1117** [comment]
您好，我在虚拟机上部署两个集群，集群信息如下：
A集群：
<img width="648" alt="A集群" src="https://user-images.githubusercontent.com/45112669/114865252-8dcd8600-9e24-11eb-9497-bf8b44c83489.PNG">
B集群：
<img width="644" alt="B集群" src="https://user-images.githubusercontent.com/45112669/114865281-98881b00-9e24-11eb-8329-3ddddaa1c32a.PNG">
有两个问题请问跟您确认一下：
- 执行`kubefate cluster install -f ./cluster-A.yaml`这句命令是在master节点还是node节点
- 修改`cluster.yaml`文件，其中partyIp是哪台机器的IP
期待您的回复，谢谢！

**Comment by LaynePeng** [comment]
It seems it cannot download the helm chart from official location which in Github. I suggest you try to download and manage it offline. Ref: https://github.com/FederatedAI/KubeFATE/blob/master/docs/Manage_FATE_and_FATE-Serving_Version.md#manage-charts-in-kubefate-manually

**Comment by LaynePeng** [comment]
By the way, we also suggest you upgrade the KubeFATE to the latest one: v1.6.0:
1. Support latest FATE, which a lot enhancement;
2. More bugs fixes in KubeFATE, as well as useful features;
3. Some useful logs added and useful for us to debugs.

**Comment by LaynePeng** [comment]
Because the reporter said it is solved in #394 , I close this as well.
