### ISSUE TITLE
k8s部署，python容器与本机共享目录

### ISSUE THREAD

**Issue by huyz1117** [FederatedAI/KubeFATE#413]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
kubefate commandLine version=v1.4.1
kubefate service version=v1.4.1
FATE=v.16.0
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: Centos
 - Version Centos7

**Desktop (please complete the following information):**

**To Reproduce**
在两个k8s集群上部署fate(使用的是虚拟机)，过程大致参考这个[教程](https://blog.csdn.net/qq_42906753/article/details/106254555?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Edefault-6.baidujs&dist_request_id=1331989.11010.16187952044948821&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Edefault-6.baidujs),现在问题是我想将本机上的数据与python容器共享进行联邦学习建模，请问怎么设置本机与python容器的共享目录

**What happen?**
Clear the unexpected response.

**Screenshots**

**Additional context**

**Comment by owlet42** [comment]
You can create a PV of hostPath,  mount it to python's Pod.
