### ISSUE TITLE
toy example 问题

### ISSUE THREAD

**Issue by wygod** [FederatedAI/KubeFATE#418]
配置： 
    电脑：两台 内存32G 硬盘1T 16核   分别安装virtualbox  操作系统centos 7 内存17G 硬盘500G 8核   

详细描述：两台电脑分别在virtualbox中安装docker, 按照docker_compose教程 启动fate 1.5版本。 免密登陆，可以互相ping通。

parties.conf:

user=root
dir=/data/projects/fate
party_list=(10000 9999)
party_ip_list=(192.168.2.30 192.168.2.31)
serving_ip_list=(192.168.2.30 192.168.2.31)
# computing_backend could be eggroll or spark.
computing_backend=eggroll

运行toy example 出现
python run_toy_example_bak.py 9999 10000 1
 stdout["data"][0]["f_status"]
list index out of range
python run_toy_example_bak.py 10000 9999 1
ValueError: job running time exceed, please check federation or eggroll log

有没有详细验证的路径，日志文件，方便查询问题。

**Comment by wygod** [comment]
主要是应该怎么如何去验证fate是否安装成功？我没有在文档中看到这个步骤，所以不知道如何排查问题，出现在哪里。

**Comment by JingChen23** [comment]
The way to verify that FATE is installed successfully is to run toy_example successfully.

The way to troubleshooting the issue is to check the log of your containers.

Please try if you can reproduce the issue by using Kubefate v1.5.3, v1.7.2 or v1.8.0, if you can, feel free to reopen the issue.
