### ISSUE TITLE
Enable ingress in minikube，why ingress ADDRESS also is empty？

### ISSUE THREAD

**Issue by wangzy0327** [FederatedAI/KubeFATE#420]
**What deployment mode you are use?  **
minikube v1.7.3

**What KubeFATE and FATE version you are using?  **
kubefate: Release: v1.5.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: centos 7.9

Enable ingress in MiniKube:

[wzy@comput5 demo]$ sudo minikube addons enable ingress
* The 'ingress' addon is enabled

I also get:

NAME                            READY   STATUS    RESTARTS   AGE
pod/kubefate-5d97d65947-6f94n   1/1     Running   1          16s
pod/mariadb-69484f8465-25fb6    1/1     Running   0          15s

NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/kubefate   ClusterIP   10.107.220.118   <none>        8080/TCP   15s
service/mariadb    ClusterIP   10.102.14.221    <none>        3306/TCP   15s

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kubefate   1/1     1            1           16s
deployment.apps/mariadb    1/1     1            1           16s

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/kubefate-5d97d65947   1         1         1       16s
replicaset.apps/mariadb-69484f8465    1         1         1       15s

NAME                          HOSTS          ADDRESS   PORTS   AGE
ingress.extensions/kubefate   kubefate.net             80      15s

Ingress ADDRESS is empty

**Comment by owlet42** [comment]
Please check your k8s's pods of ingress-controller are Running.

**Comment by jesseytang** [comment]
@owlet42 同问，问题描述见链接https://github.com/FederatedAI/KubeFATE/issues/367#issuecomment-955140675，能否帮解答一下。

**Comment by JingChen23** [comment]
Close this issue as this should be due to ingress controller not running properly.
