### ISSUE TITLE
k8s部署，nodemanager pvc问题

### ISSUE THREAD

**Issue by zzc443701406** [FederatedAI/KubeFATE#436]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
v1.6.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: ubuntu
 - Version 16.04

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**
配置了nodemanager的pvc和storageclass之后没有生效
不管是手动创建好pvc或者配置storageclass，最终nodemanager的持久化目录都没用使用pvc

**Screenshots**
![image](https://user-images.githubusercontent.com/19464409/122325702-a27de580-cf5d-11eb-84bc-a8e921a32e93.png)
![image](https://user-images.githubusercontent.com/19464409/122325701-a27de580-cf5d-11eb-9cee-541a1e7d57bb.png)

**Additional context**

**Comment by owlet42** [comment]
If existingClaim is configured, storageClass will not work.

**Comment by xf314year** [comment]
感觉existingClaim这个参数无法起作用，client配置里，即使配置了已创建的pvc，实际容器起来后云盘还是没有挂载

**Comment by JingChen23** [comment]
I just checked the code, nodemanager doesn't support existingClaim.

WRT why it doesn't support storage class, still need investifation.

**Comment by JingChen23** [comment]
@xf314year There is a switch in your cluster.yaml file:

`persistence: false`

Have you change this to true?

**Comment by JingChen23** [comment]
We find this bug too, is fixing by #777
