### ISSUE TITLE
docker方式动态扩容节点

### ISSUE THREAD

**Issue by gaojunjie03** [FederatedAI/KubeFATE#439]
能否提供一个docker-compose部署方式的fate集群动态扩容节点的技术文档？我们环境和代码已经适配上了docker-compose方式了不好改动。求提供docker动态扩容的文档

**Comment by owlet42** [comment]
Docker-compose is just an experimental environment, you can complete the expansion yourself.

**Comment by gaojunjie03** [comment]
> Docker-compose is just an experimental environment, you can complete the expansion yourself.

我用改用k8s解决了，谢谢
