### ISSUE TITLE
There is an examples file in the python container but no other files can't be tested below.

### ISSUE THREAD

**Issue by xinfang52013141** [FederatedAI/KubeFATE#44]
There is an examples file in the python container but no other files can't be tested below.

**Comment by jiahaoc1993** [comment]
@xinfang52013141 Did you mean the examples dir is empty?

**Comment by dockerzhang** [comment]
please make sure python container can access github,  the examples dir clone from github when container  to start

**Comment by jiahaoc1993** [comment]
This [PR](https://github.com/FederatedAI/FATE/commit/73b96361200777d0cc3533630eb02ad92b1d9af4) has solved this issue.
