### ISSUE TITLE
请问下面这个问题该怎么解决呢：ValueError: non-printable char found in sid_name ﻿phone_md5, please check.

### ISSUE THREAD

**Issue by zzzzzbbbbb25** [FederatedAI/KubeFATE#447]
K8S，V1.6版本，训练模型的时候，在第一步，DataIO: dataio_0 环节就报错，然后出错内容如下：

File "./fate/python/federatedml/util/abnormal_detection.py", line 97, in check_legal_schema
28
    raise ValueError(f"non-printable char found in sid_name {sid_name}, please check.")
29
ValueError: non-printable char found in sid_name ﻿phone_md5, please check.。

但是在V1.3版本的时候，同样的数据，就没有报这个错误。

**Comment by owlet42** [comment]
Maybe you can issue in here(https://github.com/FederatedAI/FATE/issues)

**Comment by JingChen23** [comment]
This should be fate related issue.

**Comment by JianhuanZeng** [comment]
> Maybe you can issue in here(https://github.com/FederatedAI/FATE/issues)

+1

**Comment by JianhuanZeng** [comment]
+1 the same problem
