### ISSUE TITLE
为什么kubefate配置文件里面不写fqdn 服务域名，而是写ip地址？

### ISSUE THREAD

**Issue by guojiex** [FederatedAI/KubeFATE#453]
**Is your feature request related to a problem? Please describe.**
example 里面的cluster yaml文件里面，party ip全是ip地址。我得先把几个party cluster起起来，然后手动改了这些ip然后update 所有cluster。k8s集群内部不是支持服务直接翻译成域名的吗，为什么要弄的那么原始呢？

**Describe the solution you'd like**
添加externalname可以使pod跨namespace通讯，然后这里直接输dns域名，这样就不需要hardcode ip每次都改来改去

**Describe alternatives you've considered**

**Additional context**

**Comment by owlet42** [comment]
The party IP is for deployment in different k8s clusters.
