### ISSUE TITLE
Error in deploy k8s-deploy with "helm install error" and "go-sqlite3".

### ISSUE THREAD

**Issue by YYangyuan** [FederatedAI/KubeFATE#466]
fate@se5:~/demo$ kubefate cluster install -f ./fate-9999.yaml
fate@se5:~/demo$ kubefate job describe 9f849569-a902-436c-ad41-f4f8056e151f
UUID            9f849569-a902-436c-ad41-f4f8056e151f                                                                   
StartTime       2021-08-16 08:49:47                                                                                    
EndTime         0001-01-01 00:00:00                                                                                    
Duration        34s                                                                                                    
Status          Failed                                                                                                 
Creator         admin                                                                                                  
ClusterId       b1e7f853-8bb7-4c5f-bcd5-9ad0f3947835                                                                   
States          - update job status to Running                                                                         
                - create Cluster in DB Success                                                                         
                - 'helm install error, looks like "https://federatedai.github.io/KubeFATE" is not                      
                  a valid Chart repository or cannot be reached: Get https://federatedai.github.io/KubeFATE/index.yaml:
                  dial tcp: lookup federatedai.github.io on 10.96.0.10:53: server misbehaving'                         
                                                                                                                       
         
fate@se5:~/demo$ kubefate service
2021-08-16T16:52:45+08:00 INF root/KubeFATE/k8s-deploy/pkg/api/service.go:89 > logLevel: info
2021-08-16T16:52:45+08:00 INF root/KubeFATE/k8s-deploy/pkg/api/service.go:90 > api version: v1
2021-08-16T16:52:45+08:00 INF root/KubeFATE/k8s-deploy/pkg/api/service.go:91 > service version: v1.4.1
2021-08-16T16:52:45+08:00 INF root/KubeFATE/k8s-deploy/pkg/api/service.go:92 > DbType: sqlite
2021-08-16T16:52:45+08:00 INF root/KubeFATE/k8s-deploy/pkg/api/service.go:93 > LogNocolor: false
2021-08-16T16:52:45+08:00 INF root/KubeFATE/k8s-deploy/pkg/api/service.go:94 > server: [0.0.0.0:8080]

2021/08/16 16:52:45 /root/KubeFATE/k8s-deploy/pkg/orm/sqlite.go:29
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

2021/08/16 16:52:50 /root/KubeFATE/k8s-deploy/pkg/orm/sqlite.go:29
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

2021/08/16 16:52:55 /root/KubeFATE/k8s-deploy/pkg/orm/sqlite.go:29
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
^C

**Comment by owlet42** [comment]
Please use pod for kubefate service run.
https://github.com/FederatedAI/KubeFATE/tree/v1.6.0/k8s-deploy#initial-a-new-fate-deployment

**Comment by JingChen23** [comment]
1. From the log, seems like you need to check your connection to "https://federatedai.github.io/KubeFATE/index.yaml"
2. `kubefate service` is a useless command as far as I know, and we will figure out how to deal with this command.
