### ISSUE TITLE
Federated schedule error, Please check rollSite and fateflow network connectivity

### ISSUE THREAD

**Issue by yumiaoGitHub** [FederatedAI/KubeFATE#467]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.6.0
wget https://github.com/FederatedAI/KubeFATE/releases/download/v1.6.0/kubefate-docker-compose-v1.6.0.tar.gz

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: Linux
 - Version 18.04

**To Reproduce**
I inactivate the firewall : ufw status(inactive)
After I Deploying FATE to target hosts successfully, I verify the deployment through
$ docker exec -it confs-10000_python_1 bash
$ cd /data/projects/fate/examples/toy_example/
$ python run_toy_example.py 10000 9999 1

**What happen?**

"retmsg": "Federated schedule error, Please check rollSite and fateflow network connectivityrpc request error:

**Screenshots**
![image](https://user-images.githubusercontent.com/17609160/129654094-2ab59930-a122-481f-a29d-0b033ff795cd.png)

**Additional context**

when I test one party, it runs successfully.
$ python run_toy_example.py 9999 9999 1
![image](https://user-images.githubusercontent.com/17609160/129654015-fce14b72-8476-4dc9-8084-e7b6118e09c0.png)

**Comment by yumiaoGitHub** [comment]
再次尝试发现当两台虚拟机处于同一个Virtual Network，并且在party.config中使用private IP 能实现正常通信。
请问一下，FATE网络通信的设计必要条件是处于同一个Virtual Network吗？还是有其它条件？

**Comment by JingChen23** [comment]
> 处于同一个Virtual Network，并且在party.config中使用private IP 能实现正常通信。
> 请问一下，FATE网络通信的设计必要条件是处于同一个Virtual Network吗？还是有其它条件？

My suggestion is to ask this question in the FATE repo by creating an issue, thanks!

**Comment by SnakeCN21** [comment]
> 



> **What deployment mode you are use? **
> 
> 1. docker-compose;
> 
> **What KubeFATE and FATE version you are using? ** 1.6.0 wget https://github.com/FederatedAI/KubeFATE/releases/download/v1.6.0/kubefate-docker-compose-v1.6.0.tar.gz
> 
> **What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS. **
> 
> * OS: Linux
> * Version 18.04
> 
> **To Reproduce** I inactivate the firewall : ufw status(inactive) After I Deploying FATE to target hosts successfully, I verify the deployment through $ docker exec -it confs-10000_python_1 bash $ cd /data/projects/fate/examples/toy_example/ $ python run_toy_example.py 10000 9999 1
> 
> **What happen?**
> 
> "retmsg": "Federated schedule error, Please check rollSite and fateflow network connectivityrpc request error:
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/17609160/129654094-2ab59930-a122-481f-a29d-0b033ff795cd.png)
> 
> **Additional context**
> 
> when I test one party, it runs successfully. $ python run_toy_example.py 9999 9999 1 ![image](https://user-images.githubusercontent.com/17609160/129654015-fce14b72-8476-4dc9-8084-e7b6118e09c0.png)

老哥, 我遇到了和你一摸一样的问题, 请问你的问题后来是怎么解决的?
