### ISSUE TITLE
The log file is not linked to stdout

### ISSUE THREAD

**Issue by zchunhai** [FederatedAI/KubeFATE#483]
https://github.com/FederatedAI/KubeFATE/blob/51290cd14997bf16dcb165c7d9dd7efc9235de73/helm-charts/FATE/templates/nodemanager-module.yaml#L151

When the first log file is archived, the newly generated log file will not be linked to stdout. As below:

```
(app-root) bash-4.2# ls -lth /data/projects/fate/eggroll/logs/eggroll
total 8.0K
-rw-r--r--. 1 root root 2.3K Oct 13 02:01 eggroll.jvm.log
drwxr-xr-x. 3 root root 4.0K Oct  9 02:53 2021
lrwxrwxrwx. 1 root root   11 Oct  8 09:24 eggroll.jvm.err.log -> /dev/stderr
lrwxrwxrwx. 1 root root   11 Oct  8 09:24 eggroll-audit.log -> /dev/stdout
```

**Comment by owlet42** [comment]
I have verified that this problem no longer exists.

![image](https://user-images.githubusercontent.com/21351918/155266601-c6b16b61-01b4-46cd-b375-9e57847cdfc0.png)
