### ISSUE TITLE
ClusterInstall fails due ta a dependency to a legacy version of networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by hkeil** [FederatedAI/KubeFATE#490]
**What deployment mode you are use?  **
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
* kubefate commandLine version=v1.4.1
* kubefate service version=v1.4.1
* kubefate-v1.4.1.docker

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 Red Hat Enterprise Linux Server release 7.9 (Maipo)

**To Reproduce**
exexute ./kubefate cluster install -f ./fate-9999.yaml

**What happen?**
ClusterInstall fails:

./kubefate job ls
UUID                                    CREATOR METHOD          STATUS  STARTTIME           CLUSTERID                               AGE
bfa43abd-ade7-4e60-a737-5883a114dace    admin   ClusterInstall  Failed  2021-11-04 15:22:45 2b2673ff-0652-4688-9aad-0357d639bad5    2m1s
41a5a4c3-b5f7-4a2f-8674-707f890ede8f    admin   ClusterInstall  Failed  2021-11-04 15:22:54 e56b5fb7-7048-41a2-aab5-dda851ecd79d    112s
 
./kubefate job describe bfa43abd-ade7-4e60-a737-5883a114dace
UUID        bfa43abd-ade7-4e60-a737-5883a114dace                                                   
StartTime   2021-11-04 15:22:45                                                                    
EndTime     0001-01-01 00:00:00                                                                    
Duration    2m51s                                                                                  
Status      Failed                                                                                 
Creator     admin                                                                                  
ClusterId   2b2673ff-0652-4688-9aad-0357d639bad5                                                   
States      - update job status to Running                                                         
            - create Cluster in DB Success                                                         
            - 'helm install error, unable to build kubernetes objects from release manifest: unable
              to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"'

**Additional context**
Following https://medium.com/@FateFedAI/build-two-parties-fate-cluster-in-one-linux-machine-with-minikube-a81ecf51059

**Comment by Irob466** [comment]
Seconding this-- Ingress was removed from networking.k8s.io/v1beta1 as of k8s version 1.22 [noted here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingressclass-v122).

I would be able to create a PR to update the templates but I currently do not know how to test locally since the helm charts and templates appear to be pulled from an external repo (https://federatedai.github.io/KubeFATE). 

To make the templates compatible with networking.k8s.io/v1 you would have to update the templates to this format:
```diff
diff --git a/helm-charts/FATE/templates/ingress.yaml b/helm-charts/FATE/templates/ingress.yaml
index dcc07e9..da04be0 100644
--- a/helm-charts/FATE/templates/ingress.yaml
+++ b/helm-charts/FATE/templates/ingress.yaml
@@ -11,7 +11,7 @@
 {{ if .Values.istio.enabled }}
 {{ else }}
 {{ if .Values.modules.fateboard.include }}
-apiVersion: networking.k8s.io/v1beta1
+apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: fateboard
@@ -29,9 +29,11 @@ spec:
     http:
       paths:
       - path: {{ default "/" .path }}
+        pathType: Prefix
         backend:
-          serviceName: fateboard
-          servicePort: 8080
+          service:
+            name: fateboard
+            port: 8080
```

**Comment by owlet42** [comment]
Completed by this PR #495.
