### ISSUE TITLE
notebook和fateboard的域名不正确，缺少9999.

### ISSUE THREAD

**Issue by wozitaoran** [FederatedAI/KubeFATE#493]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **

FATE发布版本: v1.6.1
kubefate服务版本: v1.4.2
kubefate命令行版本: v1.4.2

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: centos
 - Version 7.9

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 10

**To Reproduce**
下载release版的kubefate-k8s-v1.6.1.tar.gz，按照example里的例子安装
`name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.6.1
partyId: 9999
registry: "hub.c.163.com/federatedai"
imageTag: "1.6.1-release"
pullPolicy: 
#imagePullSecrets: 
#- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - fateboard
  - client

backend: eggroll

host:
  fateboard: 9999.fateboard.kubefate.net
  client: 9999.notebook.kubefate.net

rollsite: 
  type: NodePort
  nodePort: 30091
  partyList:
  - partyId: 10000
    partyIp: 192.168.6.72
    partyPort: 30101

python:
  type: NodePort
  httpNodePort: 30097
  grpcNodePort: 30092

servingIp: 192.168.6.72
servingPort: 30095
`

**What happen?**
通过kubefate cluster describe查看集群信息，**notebook和fateboard的域名不正确，缺少9999.**
Info        	dashboard:                              
            	- notebook.kubefate.net                 
            	- fateboard.kubefate.net 
应该是：
Info        	dashboard:                              
            	- 9999.notebook.kubefate.net                 
            	- 9999.fateboard.kubefate.net 

**Screenshots**

**Additional context**

**Comment by owlet42** [comment]
Please refer to this example (https://github.com/FederatedAI/KubeFATE/blob/v1.6.1/k8s-deploy/cluster.yaml).

**Comment by owlet42** [comment]
The latest example has been fixed.
