### ISSUE TITLE
Fate 1.7 support

### ISSUE THREAD

**Issue by HaoXuan40404** [FederatedAI/KubeFATE#497]
Hello, I wanna know when will kubefate support fate 1.7 🍡

**Comment by owlet42** [comment]
We are ready for release and will release it soon. What's the latest code? The master branch,

**Comment by HaoXuan40404** [comment]
So I can use the master branch to build fate 1.7 now?

**Comment by LaynePeng** [comment]
> e master branch to build fate

I guess you mean "installing FATE v1.7.0"? Now we have made the release available officially. You may found it in release page.

**Comment by owlet42** [comment]
https://github.com/FederatedAI/KubeFATE/releases/tag/v1.7.0
