### ISSUE TITLE
toy example 启动  python容器报错

### ISSUE THREAD

**Issue by Xugcs** [FederatedAI/KubeFATE#499]
**What deployment mode you are use?  **
1. docker-compose;

![image](https://user-images.githubusercontent.com/71803018/144167384-6a29457e-e164-481c-8da3-5f7595dfc45c.png)

**Comment by Xugcs** [comment]
docker logs confs-10000_python_1

**Comment by owlet42** [comment]
Please try redeployment after thorough cleaning.

**Comment by JingChen23** [comment]
Please see if you can reproduce the issue with the latest version 1.8.0, BTW, please post the version you used when you create an issue, thanks!
