### ISSUE TITLE
第一次成功，之后都会报错，会影响后续实验么？

### ISSUE THREAD

**Issue by heexu976** [FederatedAI/KubeFATE#500]
<img width="1914" alt="截屏2021-12-07 16 58 25" src="https://user-images.githubusercontent.com/82302269/144998214-d1053c0c-7cf1-4076-89f4-4cc0a489cb7c.png">

**Comment by owlet42** [comment]
Please check if the cluster resources are too small.

**Comment by JingChen23** [comment]
这是跑的哪个测试啊？ @heexu976

**Comment by JingChen23** [comment]
Cannot reproduce this issue in v1.9.0, close the isuue.
