### ISSUE TITLE
nodemanager 使用k8s 部署，如何平均分配再不同节点

### ISSUE THREAD

**Issue by mdzh521** [FederatedAI/KubeFATE#502]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

**Desktop (please complete the following information):**

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**
Clear the unexpected response.

**Screenshots**

**Additional context**

**Comment by owlet42** [comment]
Please use the "nodeSelector" "tolerations" and "affinity".
