### ISSUE TITLE
Eggroll如何使用docker部署多nodemanager

### ISSUE THREAD

**Issue by JasonBian** [FederatedAI/KubeFATE#503]
**What deployment mode you are use?  **
1. docker-compose;

**What FATE version you are using?  **
1.6.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: [CentOS Linux release 7.9.2009 (Core)]
 - docker-compose [docker-compose version 1.27.4, build 40524192]

如果要实现如下部署：
party | partyid |  IP地址 |安装软件 | 服务
-- | -- | -- | -- | -- | -- | --
PartyA | 10000 | 192.168.0.1 |  fate，eggroll，mysql | fate_flow，fateboard，clustermanager，nodemanger，mysql
PartyA | 10000 | 192.168.0.1 | fate,eggroll | nodemanger，rollsite
PartyB | 9999 |  192.168.0.2 |  fate，eggroll，mysql | all

在docker-deploy目录下parties.conf文件中
party_list
party_ip_list
serving_ip_list
参数如何设置

**Comment by owlet42** [comment]
The original intention of the docker-compose deployment mode design is not suitable for this multi-node scenario. You can modify the docker-compose.yaml yourself to adapt, and it will be simpler to use the host network mode.

**Comment by JasonBian** [comment]
> The original intention of the docker-compose deployment mode design is not suitable for this multi-node scenario. You can modify the docker-compose.yaml yourself to adapt, and it will be simpler to use the host network mode.

Ok, Thanks for your answer
