### ISSUE TITLE
每次Ubuntu重启，之前编写的Jupyter notebook文件都会消失

### ISSUE THREAD

**Issue by Cp99nice** [FederatedAI/KubeFATE#504]
![404](https://user-images.githubusercontent.com/52906517/147206598-eb18ba23-7260-4dde-a2e0-ef2fb714769e.png)

**Comment by owlet42** [comment]
Please configure persistence settings
```bash
...
persistence: true
...
```

**Comment by Cp99nice** [comment]
ok, thanks
