### ISSUE TITLE
when I test toy example，it seems that the job is not submitted successfully

### ISSUE THREAD

**Issue by L-coder148** [FederatedAI/KubeFATE#505]
<img width="759" alt="372939795268d9c3509b38b38aa85b8" src="https://user-images.githubusercontent.com/75669641/147716266-d4ba2f01-f9a3-4a33-8c49-35fa5db9f331.png">

**Comment by owlet42** [comment]
Please check the network connectivity between parties, "rollsite" to "rollsite".

**Comment by LaynePeng** [comment]
Any update? @L-coder148

**Comment by JingChen23** [comment]
Close stale issue
