### ISSUE TITLE
Yaml validation for cluster creation

### ISSUE THREAD

**Issue by gegose** [FederatedAI/KubeFATE#517]
**Is your feature request related to a problem? Please describe.**
I have spent some time trying to figure out what was happening with my cluster to then discover that the configuration file had wrong properties. 

**Describe the solution you'd like**
I would like to have at least some kind of warning when you create your cluster about lines in the yaml file not applying or something similar. For example:

```shell
$ kubefate cluster install -f examples/party-9999/cluster-spark-local-pulsar.yaml
WARNING: There are some properties in your config file that will not take any effect (line 24: ...)
```

**Describe alternatives you've considered**
An alternative could be activate some flag for this but I think that it would be better as the default behaviour for the command.

**Comment by LaynePeng** [comment]
So this is a requirement about adding pre-check to cluster.yaml. It is reasonable.

**Comment by JingChen23** [comment]
Hi @gegose , thanks for proposing this feature, we have made it code complete on the develop-1.9.0 branch now, will be released in August.
