### ISSUE TITLE
Solve the warning of potential security vulnerabilities in Github pages

### ISSUE THREAD

**Issue by LaynePeng** [FederatedAI/KubeFATE#519]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What happen?**
Solve the warning of potential security vulnerabilities in Github pages

- [x] #521
- [x] #522

**Comment by LaynePeng** [comment]
- [ ] Solved dependencies issue
- [ ] Package gomodule file

**Comment by stuforfun** [comment]
We can't  solve the dependency issue, but it's a minnor bug, lower the priortity

**Comment by owlet42** [comment]
Done
