### ISSUE TITLE
Support specify ingress class names

### ISSUE THREAD

**Issue by wfangchi** [FederatedAI/KubeFATE#523]
**Is your feature request related to a problem? Please describe.**
When using k8s-deploy mode, the ingresses created by KubeFATE lack the `ingressClassName` field. It makes the ingress being handled by the default ingress class' controller, or the ingress controller that watches ingress without such field, or not handled at all.

**Describe the solution you'd like**
Support specifying the `ingressClassName` field in the yaml file we provided to KubeFATE.

**Describe alternatives you've considered**
I can use the annotation field to specify the ingress class, but it is not the current official way to binding to `IngressClass`

**Additional context**
[Kubernetes official doc](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)

**Comment by JingChen23** [comment]
Job done.
