### ISSUE TITLE
Adjust the file structure of Chart to facilitate the addition of new modules

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/KubeFATE#526]
**Summary**

When a new module or function is to be added or deleted, the current file structure is inconvenient to operate, easy to make mistakes and increase additional workload. 

**Task the outcome**

If the current chart file structure can be changed, the working time of adding functions can be greatly reduced. The organizational structure of chart files will also be clearer.

**How will it work**

The chart corresponding to the function of a module will be placed in the module's own folder, and all functions will be placed in a single file as far as possible. The final result is about this:
```bash
fate
├── Chart.yaml
├── templates
│   ├──core
│   │   ├──fateflow
│   │   │   ├──Deployment.yaml
│   │   │   ├──Server.yaml
│   │   │   ├──Ingress.yaml
│   │   │   ├──Configmap.yaml
│   │   │   ├──PVC.yaml
│   │   │   ├──...
│   │   │   └──_helpers.tpl
│   │   ├──fateboard
│   │   ├──mysql
│   │   └──client
│   ├──backends
│   │   ├──eggroll
│   │   │   ├──nodemanager
│   │   │   ├──clustermanager
│   │   │   └──rollsite
│   │   └──spark
│   │       ├──hdfs
│   │       ├──spark
│   │       ├──rabbitmq
│   │       ├──pulsar
│   │       └──nginx
│   ├──psp.yaml
│   ├──...
│   ├──_helpers.tpl
│   └──NOTES.txt
├── values-template-example.yaml
├── values-template.yaml
└── values.yaml
```

**Comment by JingChen23** [comment]
Done.
