### ISSUE TITLE
Would you please check this problem( task_executor.py", line 118 )? the errlog is uploaded ,thanks

### ISSUE THREAD

**Issue by HelloLadsAndGents** [FederatedAI/KubeFATE#53]
i have followed the steps of docker compose deployment
(https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README.md)

and at the last step:**Verify the Deployment**
 when i execute scripts: 
python run_toy_example.py 10000 9999 1
i got this problem:

**(part of the log)**
Traceback (most recent call last):
File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 118, in run_task
run_object.run(parameters, task_run_args)
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 113, in run
self._init_data()
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 54, in _init_data
self.x = session.parallelize(kvs, include_key=True, partition=self.partition)
File "/data/projects/fate/python/arch/api/utils/profile_util.py", line 31, in _fn
rtn = func(*args, **kwargs)
File "/data/projects/fate/python/arch/api/session.py", line 76, in parallelize
error_if_exist=error_if_exist)
File "/data/projects/fate/python/arch/api/table/eggroll/session_impl.py", line 69, in parallelize
error_if_exist=error_if_exist)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 410, in parallelize
_table = self._create_table(create_table_info)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 444, in _create_table
count = self.eggroll_session._gc_table.get(info.storageLocator.name)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 214, in get
return _EggRoll.get_instance().get(self, k, use_serialize=use_serialize)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 571, in get
operand = self.kv_stub.get(kv_pb2.Operand(key=k), metadata=_get_meta(_table))
File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "172.18.0.8:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at 

[err_20191128.log](https://github.com/FederatedAI/KubeFATE/files/3899739/err_20191128.log)

**Comment by jiahaoc1993** [comment]
@HelloLadsAndGents It seems your `storage-service` is not working properly, please go to `egg` container can check the logs located at "/data/projects/fate/eggroll/storage-service-cxx/logs/"

**Comment by HelloLadsAndGents** [comment]
hello 
i had searched this dir but found that all two logs are empty

![egg_log](https://user-images.githubusercontent.com/25575793/69796822-a6c2a080-1209-11ea-819a-49b38363c6a5.jpg)

**Comment by HelloLadsAndGents** [comment]
hello
i had searched this dir but found all two logs are empty
Are there any other ways to find out where the problem is
![pic](https://user-images.githubusercontent.com/25575793/69797323-6e6f9200-120a-11ea-9e34-75e89d0ecd2c.jpg)

**Comment by jiahaoc1993** [comment]
@HelloLadsAndGents It seems your "storage service" is failed to start. You can start it manually to address the problem. To start the "storage service", please use the following command:
```
./storage-service -p 7778 -d /data/projects/fate/data-dir
```
According to the output, you may have different solutions. For more details please check out our [wiki page](https://github.com/FederatedAI/KubeFATE/wiki)

**Comment by HelloLadsAndGents** [comment]
Thanks ,it does help, i follow your steps:

cd /data/projects/fate/eggroll/storage-service-cxx
./storage-service -p 7778 -d /data/projects/fate/data-dir

and i got the info:
Illegal instruction (core dumped)

then i check your wiki page(https://github.com/FederatedAI/KubeFATE/wiki/KubeFATE) and i found：
The storage-service of egg service requires CPU instruction set like avx2 etc. Please make sure your CPU supports these instructions otherwise the storage-service will fail to start with the following error:

**i think it is because of our nodes' CPU does not support instruction set like avx2**
and i'm wondering are there any solutions to solve this kind of problme ?

and i suggest you guys can put requirements for CPU in pages like this:
https://github.com/FederatedAI/FATE/tree/master/cluster-deploy

thanks again

**Comment by jiahaoc1993** [comment]
@HelloLadsAndGents will do, I appreciate your feedback. Let's close the issue now.
