### ISSUE TITLE
mysql communication error

### ISSUE THREAD

**Issue by JasonBian** [FederatedAI/KubeFATE#531]
kubefate v1.7.0

使用1w的数据进行boost训练可以正常执行，使用25w数据训练报连接mysql错误

![image](https://user-images.githubusercontent.com/3529844/155467022-da7bca49-8331-4a44-9810-096492d1acaf.png)

**Comment by LaynePeng** [comment]
Will verify. Cloud you provide more details, k8s or compose? hardware? and do you have more other logs?

**Comment by JasonBian** [comment]
I slove this problem;because leak of resource
