### ISSUE TITLE
查询kubefate version 报错:kubefate service connection error

### ISSUE THREAD

**Issue by jx1239614362** [FederatedAI/KubeFATE#532]
[root@fate demo]# kubefate version
* kubefate commandLine version=v1.4.2
* kubefate service connection error, resp.StatusCode=404, error: 

我用的是k8s安装kubefate，但是在查询kubefate version时出现了如上的错误，在安装时我先安装k8s，然后安装kubefate 1.7.0 和Harbor。
kubefate.net是可以ping通的，但是为什么会报404的错误？

**Comment by oceanqdu** [comment]
我也遇到了这个问题，
```
2022-07-26T11:19:32+08:00 DBG ../../origin/KubeFATE/k8s-deploy/pkg/cli/version.go:61 > Request Type=GET url=http://example.com/v1/version
* kubefate service connection error, Post "http://example.com/v1/user/login": dial tcp 10.0.2.15:80: connect: connection refused

```
请问您解决了吗

**Comment by JingChen23** [comment]
@oceanqdu 方便展示一下你的ingress配置，service配置，以及kubefate的config.yaml文件的内容吗？

**Comment by oceanqdu** [comment]
@JingChen23 非常感谢您的回复，我刚刚已经解决了这个问题，在config.yaml文件种默认的是serviceurl: example.com
我查找了对应的端口映射
![image](https://user-images.githubusercontent.com/49178688/180933082-0b6face3-1efc-440c-8b51-ccd302090ffb.png)
然后修改了config.yaml文件成功解决了这个问题，
![image](https://user-images.githubusercontent.com/49178688/180932913-8a0f51a7-49d8-4336-92e5-45d3ea965f91.png)
