### ISSUE TITLE
如何通过FATE实现多个参与方的神经网络模型训练

### ISSUE THREAD

**Issue by jjmmmmmm** [FederatedAI/KubeFATE#535]
通过fate1.6.0可以实现双参与方的神经网络模型训练，但是，如果有多个参与方拥有数据，但是这些数据都不能公开，这些参与方想进行横向联邦学习，如何通过FATE事项超过三个及以上的参与方进行神经网络模型训练呢？

**Comment by owlet42** [comment]
You can refer to these examples: 
https://github.com/FederatedAI/FATE/tree/master/examples/dsl/v2/homo_nn#readme

**Comment by LaynePeng** [comment]
It seems a FATE's issue, has you raised issue in FATE?
