### ISSUE TITLE
运行boosting 模型报错

### ISSUE THREAD

**Issue by JasonBian** [FederatedAI/KubeFATE#536]
![image](https://user-images.githubusercontent.com/3529844/155688246-59a69265-9292-4cd1-b092-3d295050c042.png)

job配置信息：

![image](https://user-images.githubusercontent.com/3529844/155688498-19bc677f-b164-4218-85fd-387967d1807d.png)

硬件配置：
2台 ：4core，8G Memory

**Comment by JingChen23** [comment]
I can infer nothing from the above log, if you can still reproduce the issue, I would suggest you to create an issue in the FATE repo to involve the experts, thanks.

Close the issue, feel free to open if you have any concern, thanks.
