### ISSUE TITLE
运行皮尔逊系数例子时，日志报No module named '_md5'错误

### ISSUE THREAD

**Issue by Cp99nice** [FederatedAI/KubeFATE#537]
**What deployment mode you are use?  **
docker-compose;

**What KubeFATE and FATE version you are using?  ** KubeFATE v1.4.1   FATE v1.6.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: ubuntu
 - Version  20.04

![微信图片_20220228205911](https://user-images.githubusercontent.com/52906517/155987462-816d8a43-ae82-4644-b871-df554e04f020.png)

**Comment by Cp99nice** [comment]
修改Python容器中的naming.py后还是有这个问题
![be6fca9876317aaaf8e0324e75cf9ea](https://user-images.githubusercontent.com/52906517/156159984-23c0423e-aad4-4744-9065-d35580646436.png)

**Comment by owlet42** [comment]
FATE version 1.7+ solves this problem, please use a newer version.
