### ISSUE TITLE
Online inference gets inconsistent results with prediction job.

### ISSUE THREAD

**Issue by windyalsy** [FederatedAI/KubeFATE#543]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
KubeFate 1.4.2

I trained an offline model using hetero logistic regression components for default credit classification. Then submit prediction job and obtain proper results. However, I tried online inference and responses confused me. At first, online inference gave different classification probabilities for the same guest inputs with above-mentioned prediction jobs. Besides, I found that "id" in "sendToRemoteFeatureData" is not working and It seemed intersection based on "id" failed. 

Is there any methods to locate mistakes?

**Comment by LaynePeng** [comment]
This is more like a FATE issue. And KubeFATE and FATE is supported latest 2 major versions, so that v1.4.2 is not in the support list. Could you update to the latest version and try again?

**Comment by windyalsy** [comment]
> This is more like a FATE issue. And both KubeFATE and FATE support latest 2 major versions, so that v1.4.2 is not in the support list. Could you update to the latest version and try again?

Yeah, I will try on the recent version. Thanks for the reply.

**Comment by JingChen23** [comment]
Feel free to reopen if you can reproduce in the latest version, thanks.
