### ISSUE TITLE
modify the fateboard port

### ISSUE THREAD

**Issue by mide123** [FederatedAI/KubeFATE#544]
I hope we can modify the fateboard port, thanks

**Comment by LaynePeng** [comment]
Hi, @mide123 for k8s or docker-compose way?

**Comment by mide123** [comment]
Hi,&nbsp;
&nbsp; &nbsp; &nbsp; I'm for k8s.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/KubeFATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午12:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/KubeFATE] modify the fateboard port (Issue #544)





 
Hi, @mide123 for k8s or docker-compose way?

**Comment by LaynePeng** [comment]
For k8s, FATE-Board service is exposed by Ingress or LB, so the port exposing depend on the ingress controller setting or LB. Or could you introduce some details of how you deploying the services (how the k8s setting)?

**Comment by mide123** [comment]
I deploy fate by KubeFATE, it will involved by Ingress? I sorry,&nbsp; i&nbsp;don't know much about&nbsp;Ingress




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FederatedAI/KubeFATE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午1:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FederatedAI/KubeFATE] modify the fateboard port (Issue #544)





 
For k8s, FATE-Board service is exposed by Ingress or LB, so the port exposing depend on the ingress controller setting or LB. Or could you introduce some details of how you deploying the services (how the k8s setting)?

**Comment by royukira** [comment]
> 
Same question.
I deployed KubeFATE in docker-compose way. 
Before running docker_deploy.sh, I have already changed the port to 10080 in /KubeFATE/docker-deploy/training_template/public/fateboard/conf/application.properties. Howerver, I still cannot access the FateBoard. 

application.properties
```
server.port=10080
fateflow.url=
spring.datasource.driver-Class-Name=com.mysql.cj.jdbc.Driver
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
server.tomcat.uri-encoding=UTF-8
fateboard.datasource.jdbc-url=<jdbc.url>
fateboard.datasource.username=<jdbc.username>
fateboard.datasource.password=<jdbc.password>
server.tomcat.max-threads=1000
server.tomcat.max-connections=20000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
spring.datasource.druid.filter.config.enabled=false
spring.datasource.druid.web-stat-filter.enabled=false
spring.datasource.druid.stat-view-servlet.enabled=false
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.board.login.username=<fateboard.username>
server.board.login.password=<fateboard.password>
management.endpoints.web.exposure.exclude=*
#server.ssl.key-store=classpath:
#server.ssl.key-store-password=
#server.ssl.key-password=
#server.ssl.key-alias=
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
#HTTP_APP_KEY=
#HTTP_SECRET_KEY=
```

**Comment by JingChen23** [comment]
Hi @royukira and @mide123 , could you please give a justification what is the necessary reason for supporting that? Please understand each requirement needs effort to achieve, so that we need to evaluate the requirements.

**Comment by JingChen23** [comment]
I think after you changed the /KubeFATE/docker-deploy/training_template/public/fateboard/conf/application.properties

You need to firstly run generate_config.sh
Then run docker_deploy.sh
