### ISSUE TITLE
cluster-serving部署中，ingress配置不生效

### ISSUE THREAD

**Issue by magic-hya** [FederatedAI/KubeFATE#546]
**What deployment mode you are use?  **
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
kubefate v1.4.3，fate1.7.1

**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: [e.g. iOS]   CentOS Linux release 7.6.1810
 - Version [e.g. 22]Red Hat 4.8.5-36

**Desktop (please complete the following information):**

**To Reproduce**

Clear how to reproduce your problem.

**What happen?**
cluster-serving部署中，ingress配置不生效

Clear the unexpected response.

**Screenshots**
![1646303463(1)](https://user-images.githubusercontent.com/85269941/156547646-c91dfcb4-2bc0-45c2-8a69-f7b2db929f7e.png)

**Additional context**

**Comment by owlet42** [comment]
Please use FATE-Serving v2.0.4（https://github.com/FederatedAI/KubeFATE/blob/gh-pages/package/fate-serving-v2.0.4.tgz）

**Comment by magic-hya** [comment]
> Please use FATE-Serving v2.0.4（[https://github.com/FederatedAI/KubeFATE/blob/gh-pages/package/fate-serving-v2.0.4.tgz）](https://github.com/FederatedAI/KubeFATE/blob/gh-pages/package/fate-serving-v2.0.4.tgz%EF%BC%89)

版本是用的V2.0.4
![1646709822(1)](https://user-images.githubusercontent.com/85269941/157160140-26feb272-0392-4e77-8815-4c9ae221d46a.png)

**Comment by caihy05** [comment]
提了issue才发现你已经提过了，我们的问题一样，不我的版本确实低，我换一下高版本

**Comment by magic-hya** [comment]
已经解决了，就是下载他新的chart，覆盖系统自动下的chart




***@***.***
 
发件人： caihy05
发送时间： 2022-04-14 17:41
收件人： FederatedAI/KubeFATE
抄送： magic-hya; Author
主题： Re: [FederatedAI/KubeFATE] cluster-serving部署中，ingress配置不生效 (Issue #546)
相同的问题请问解决了吗
