### ISSUE TITLE
homo lr testing failed at the data upload phase

### ISSUE THREAD

**Issue by hubingquan** [FederatedAI/KubeFATE#554]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.7.0 KubeFATE

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
Kernel 5.10.60 
docker-compose version 1.29.2, build 5becea4c

 - OS: [e.g. iOS] CentOS Linux release 
 - Version [e.g. 22] 7.9.2009 (Core)

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] Centos

**To Reproduce**
cd examples/pipeline/homo_logistic_regression
python pipeline-homo-lr-train.py

**What happen?**
job failed with the follow errors from the fate board:
[ERROR] [2022-03-11 06:16:38,995] [202203110616255637660] [20831:139880587167552] - [task_executor._run_] [line:258]: can not found table name: breast_homo_guest namespace: experiment
174 Traceback (most recent call last):
175   File "./fate/fateflow/python/fate_flow/worker/task_executor.py", line 201, in _run_
176     cpn_output = run_object.run(cpn_input)
176     cpn_output = run_object.run(cpn_input)
177   File "./fate/fateflow/python/fate_flow/components/_base.py", line 149, in run
178     method(cpn_input)
179   File "./fate/fateflow/python/fate_flow/components/reader.py", line 93, in _run
180     output_storage_address=output_storage_address,
181   File "./fate/fateflow/python/fate_flow/components/reader.py", line 219, in convert_check
182     f"can not found table name: {input_name} namespace: {input_namespace}"
183 RuntimeError: can not found table name: breast_homo_guest namespace: experiment

**Screenshots**
![image](https://user-images.githubusercontent.com/8966776/157813887-e8ed3279-8df5-4fe7-8843-9931627a5c58.png)

**Additional context**
Running "fate_test bq -i examples/benchmark_quality/homo_lr" got a same error at the data reader phase. While running hetero_sbt benchmarking succeeded.

**Comment by owlet42** [comment]
According to the log information, you need to upload the data first.
>183 RuntimeError: can not found table name: breast_homo_guest namespace: experiment

**Comment by JingChen23** [comment]
Close this issue as this is a usage error
