### ISSUE TITLE
While running jobs, it would silently lose some python module files within the egg service

### ISSUE THREAD

**Issue by raohuaming** [FederatedAI/KubeFATE#56]
As titled, which leads to job stuck there forever without any errors on the fateboard ui.

![791574913259_ pic_hd](https://user-images.githubusercontent.com/1218550/69782158-37d64f00-11eb-11ea-9c9e-c4c169c0fd3f.jpg)

![image](https://user-images.githubusercontent.com/1218550/69792021-ae317c00-1200-11ea-84df-8725d2774ae8.png)

![image](https://user-images.githubusercontent.com/1218550/69791921-7cb8b080-1200-11ea-9665-fa03bce4f2bc.png)

All the logs were also attached. 

[party-9999-2.tar.gz](https://github.com/FederatedAI/KubeFATE/files/3900751/party-9999-2.tar.gz)
[party-9999-1.tar.gz](https://github.com/FederatedAI/KubeFATE/files/3900752/party-9999-1.tar.gz)
[party-9999-0.tar.gz](https://github.com/FederatedAI/KubeFATE/files/3900753/party-9999-0.tar.gz)
[party-10000-2.tar.gz](https://github.com/FederatedAI/KubeFATE/files/3900754/party-10000-2.tar.gz)
[party-10000-1.tar.gz](https://github.com/FederatedAI/KubeFATE/files/3900755/party-10000-1.tar.gz)
[party-10000-0.tar.gz](https://github.com/FederatedAI/KubeFATE/files/3900756/party-10000-0.tar.gz)

**Comment by LaynePeng** [comment]
Close as this is an error of old version.
