### ISSUE TITLE
v1.7.2 版本 toy_examples.py文件在哪

### ISSUE THREAD

**Issue by jeanP-zhang** [FederatedAI/KubeFATE#564]
**What deployment mode you are use?  **

2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
v1.7.2    &  1.4.3.codker
**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
Ubuntu 20.04 LTS 

**Desktop (please complete the following information):**
NONE 

**To Reproduce**

Clear how to reproduce your problem.

**What happen?**
版本1.7.2 为什么我找不到toy_examples.py这个文件进行测试。
Clear the unexpected response.

**Screenshots**
  
![image](https://user-images.githubusercontent.com/54132884/159439738-48b615b8-df3a-46e7-8c98-4a5136252ba9.png)

**Additional context**
想要测试网络，但是为什么1.7.2版本中没有名为toy_example.py的测试文件。
 
同时也没有找到图中的ipynb文件。是不是1.7.2改变了测试方法
![image](https://user-images.githubusercontent.com/54132884/159440215-69366844-86be-43a9-a6dc-ef09f7593823.png)

**Comment by JingChen23** [comment]
Hi, could you please tell us why you are expecting toy_example.py should be somewhere in the directory? Which document are you refering? Thanks.

**Comment by jeanP-zhang** [comment]
> Hi, could you please tell us why you are expecting toy_example.py should be somewhere in the directory? Which document are you refering? Thanks.

你好，参考的是B站视频，基于k8s搭建kubeFate框架.

**Comment by JingChen23** [comment]
Well, that video could be based on a previous version of FATE. Could you please check the readme document of v1.7.2? Please find some toy examples there.

Actually Kubefate is an infrastructure of FATE, but your question relate more with FATE, so perhaps you could raise an issue in the FATE repo.

Close the issue, feel free to reopen it if there is any other concerns.
