### ISSUE TITLE
v1.7.2通过pipeline测试kubefate部署情况，结果显示 ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started

### ISSUE THREAD

**Issue by jeanP-zhang** [FederatedAI/KubeFATE#567]
**What deployment mode you are use?  **

Kuberentes.

**What KubeFATE and FATE version you are using?  **
v1.7.2    and v1.4.3.docker
**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
ubuntu 20.04TLS

**Desktop (please complete the following information):**
UBUNRU firefox

**To Reproduce**

Clear how to reproduce your problem.
部署好Fate后，进入part9999.notebook.example.com中，运行pipeline中的pipeline_tutorial_upload 。第一次显示，name "os"不存在；加入  import os后，显示路径错误：  please check path /workspace/FATE/examples/data/breast_hetero_guest.csv,重新查询.csv文件路径后，再次运动，显示：  ValueError: job submit failed, err msg: {'retcode': 100, 'retmsg': 'Connection refused, Please check if the fate flow service is started'}

Clear the unexpected response.

**Screenshots**
如图：
![image](https://user-images.githubusercontent.com/54132884/159489068-ec1f2708-04a5-48d0-a1ab-a1dcbad889ee.png)

**Additional context**
新人学习fate不容易，之前已经踩了很多坑了，但是到最后一步却依旧困难重重，目前关于fate资料确实很少，尤其是错误修正这方面，所以还请大佬们指导以下，我在这里不胜感激
none

**Comment by jeanP-zhang** [comment]
![350b81be18274e6fd077e9d3c771e76](https://user-images.githubusercontent.com/54132884/159606631-6756e601-3659-4e91-b9bc-32eefca0da8c.png)
在指定目录下启动server.sh，结果又不存在init_env.sh文件。大佬救救孩子吧

**Comment by JingChen23** [comment]
Hi, please check the status of all your pods, to see if any of them is not in a running status.
If anyone of them showing abnormal status, please paste the log of the pod here, thanks.

**Comment by jeanP-zhang** [comment]
> 

您好，我按照您的教导进行了查询。这是我两个集群pod的运行状态，均显示running。如下图
![image](https://user-images.githubusercontent.com/54132884/159643557-7fe2f48c-5198-470f-9c9a-a5de64e1ddb2.png)

而且与https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube_zh.md  这个教程中的pod镜像进行了对比，发现所需模块均能够匹配上，但是确实缺少文件，正如我上述两个问题所示。麻烦您了。，谢谢您的我的帮助，若您发现我程序的问题，请您务必告诉我，非常感激。

**Comment by JingChen23** [comment]
![Screen Shot 2022-03-24 at 11 09 35 AM](https://user-images.githubusercontent.com/15973672/159834364-57c4fa73-bc96-405b-b3ca-5e336a64473d.png)

It says "assume", you need to change it to your real fateflow service.

NAMESPACE       NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
fate-10000      fateflow-client                      NodePort    10.102.166.124   <none>        9360:30102/TCP,9380:30107/TCP   12h

For example, in my case, my fateflow client has the 9380 port mapping to 30107 node port.
So my fateflow service should be <my_host_ip:30107>

For the 9360, it is for grpc, which is not widely used now.
For the 9380, it is for http, which should be what you care about.

**Comment by jeanP-zhang** [comment]
> ![Screen Shot 2022-03-24 at 11 09 35 AM](https://user-images.githubusercontent.com/15973672/159834364-57c4fa73-bc96-405b-b3ca-5e336a64473d.png)
> 
> It says "assume", you need to change it to your real fateflow service.
> 
> NAMESPACE NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE fate-10000 fateflow-client NodePort 10.102.166.124 9360:30102/TCP,9380:30107/TCP 12h
> 
> For example, in my case, my fateflow client has the 9380 port mapping to 30107 node port. So my fateflow service should be <my_host_ip:30107>
> 
> For the 9360, it is for grpc, which is not widely used now. For the 9380, it is for http, which should be what you care about.

谢谢。我试试，感谢您的帮助，非常感谢❀❀❀

**Comment by JingChen23** [comment]
https://github.com/FederatedAI/KubeFATE/pull/570/files

Hi, I have carefully looked into the issue and has made a code change here, this is to optimize the tutorial and make sure the basic python scripts can pass. Please check this pr carefully, read the new tutorial, and change your Python notebook script as what I did in my PR. 

Feel free to leave a msg if there is still an issue, thanks.

**Comment by jeanP-zhang** [comment]
收到，感谢答复。感谢您给予我们新人的指导。



At 2022-03-28 13:25:25, "Chen" ***@***.***> wrote:

https://github.com/FederatedAI/KubeFATE/pull/570/files

Hi, I have carefully looked into the issue and has made a code change here, this is to optimize the tutorial and make sure the basic python scripts can pass. Please check this pr carefully, read the new tutorial, and change your Python notebook script as what I did in my PR.

Feel free to leave a msg if there is still an issue, thanks.

**Comment by JingChen23** [comment]
Close for now, fell free to reopen if there is still an issue.
