### ISSUE TITLE
Reduce the images' sizes

### ISSUE THREAD

**Issue by LaynePeng** [FederatedAI/KubeFATE#581]
**Summary**

**User Story**

As a user, most of our use case is PSI, or the PSI as the first step of the federated learning collaboration, I would like a smaller/thinner edition of FATE to support only PSI functionality

**Details**

The design detail, such as which libs need will be given by FATE's team. To KubeFATE:
1. A PSI-only edition of FATE image/images;
2. The deployment commands (or maybe an option) for deploying PSI-only edition

**Intake type**

Ticket: https://github.com/FederatedAI/FATE/issues/3854

**Comment by JingChen23** [comment]
Per our investigation, creating an image for PSI only cannot help to obviously reduce the images' sizes. However, there are still other ways to help reduce the image sizes. This issue will track this task.
