### ISSUE TITLE
export fate-serving server variable cacheType 

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/KubeFATE#583]
**Is your feature request related to a problem? Please describe.**
When deploy fate-serving by kubefate, the cacheType is not configured. So the cacheType should always be`local`,  even the Redis is deployed.

**Describe the solution you'd like**
export variable cacheType, config this variable before execute `cluster install`

**Describe alternatives you've considered**

**Additional context**

**Comment by JingChen23** [comment]
The reporter has fixed the issue, close the issue, thanks for your contribution!
https://github.com/FederatedAI/KubeFATE/pull/584
