### ISSUE TITLE
KubeFATE got "service connection error"

### ISSUE THREAD

**Issue by fangxiaoran** [FederatedAI/KubeFATE#598]
**What deployment mode you are use?**
Kuberentes/MiniKube

**What KubeFATE and FATE version you are using?**
KubeFATE: v1.8.0, FATE: N/A

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.**
Ubuntu 20.04, kernel: 5.4.0-91-generic

**To Reproduce**
Follow instructions in [Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube](https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube.md) to this [step](https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube.md#5-optional-add-examplecom-to-host-file).

**What happen?**
`kubefate version` returned "service connection error", after creating kubefate ingress.

**Screenshots**
![image](https://user-images.githubusercontent.com/33336732/164429673-5f6a7842-c194-46c0-ac6f-bdf822412620.png)

**Additional context**
Resources and ingress under namespace `kube-fate` seems to be working fine.
![image](https://user-images.githubusercontent.com/33336732/164429549-9cd5fb97-bbfb-4852-800b-d7ff84ccdee9.png)

Please let me know if anything needed. Hope we can fix this issue.

**Comment by JingChen23** [comment]
> sudo -- sh -c "echo \"192.168.49.2 example.com\"  >> /etc/hosts"

Have you run this to add the alias into the host file?
This is not optional if you don't have a DNS service setup.

**Comment by fangxiaoran** [comment]
Yes, and `example.com` can be pinged.

> > sudo -- sh -c "echo "192.168.49.2 example.com"  >> /etc/hosts"
> 
> Have you run this to add the alias into the host file? This is not optional if you don't have a DNS service setup.

**Comment by JingChen23** [comment]
I'm not sure if your ingress controller is working properly.
Please check if you have the ingress controller configured like mine:
```
$ kubectl get all -n ingress-nginx
NAME                                            READY   STATUS      RESTARTS   AGE
pod/ingress-nginx-admission-create-7hk7p        0/1     Completed   0          27d
pod/ingress-nginx-admission-patch-gv697         0/1     Completed   0          27d
pod/ingress-nginx-controller-5d88495688-n8f8c   1/1     Running     0          27d

NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/ingress-nginx-controller             NodePort    10.99.23.155     <none>        80:30646/TCP,443:30884/TCP   27d
service/ingress-nginx-controller-admission   ClusterIP   10.102.148.200   <none>        443/TCP                      27d

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   1/1     1            1           27d

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-5d88495688   1         1         1       27d

NAME                                       COMPLETIONS   DURATION   AGE
job.batch/ingress-nginx-admission-create   1/1           4s         27d
job.batch/ingress-nginx-admission-patch    1/1           4s         27d
```

**Comment by fangxiaoran** [comment]
Here is the status of `ingress-nginx`.
![image](https://user-images.githubusercontent.com/33336732/165129377-35e45120-b2b2-4a50-9a98-8bb0aef8a869.png)

**Comment by JingChen23** [comment]
Could you please also show me your config.yaml?
I guess there should be a `serviceurl: example.com`,
try to change it to `serviceurl: example.com:31483`

**Comment by fangxiaoran** [comment]
After I changed `serviceurl`, connection error still existed but with another info, "**kubefate service connection error, 503 Service Temporarily Unavailable. Please try again later or check the pod status of kubefate**", while `kubefate` pod worked fine.

For my understanding, `kubefate version` command tried to access `service/ingress-nginx-controller`, and the backend of this service is `pod/ingress-nginx-controller`. I checked the log of this pod as attached.

![image](https://user-images.githubusercontent.com/33336732/165260197-e56b1fa8-f408-4dc1-903f-c49092d39d12.png)

**Comment by JingChen23** [comment]
OK, your ingress controller log seems similar with mine. How about the log of your kubefate pod?

**Comment by fangxiaoran** [comment]
Pod `kubefate` got a database initialization error at first as following.
![image](https://user-images.githubusercontent.com/33336732/165268399-ff28079f-afba-4c2c-8203-62fbca27068e.png)

Other logs seemed to be fine.
![image](https://user-images.githubusercontent.com/33336732/165268650-9016553e-7393-4bc6-ba3c-15e7b370d36e.png)

Logs of database `mariadb` pod are also attached.
![image](https://user-images.githubusercontent.com/33336732/165269114-b9b4e610-65f3-49bb-84cb-fedcc8914ffd.png)

**Comment by JingChen23** [comment]
This also looks normal, could you please show us the content of your `/etc/hosts` file?

**Comment by fangxiaoran** [comment]
Sure, please let me know anything need to be checked.
![image](https://user-images.githubusercontent.com/33336732/165368480-b81c3f96-6d1e-4e3a-b90e-3c8d726afd83.png)

**Comment by JingChen23** [comment]
Seems like your host file is mapping `example.com` to `10.165.9.125`, however, your ingress for kubefate is on `192.168.49.2`, I think this could be the reason. For me, my these two places are the same ip address, which is the address of my virtual machine where I install minikube and everything.

**Comment by fangxiaoran** [comment]
Oh, that's my bad. Ingress for kubefate is on `10.165.9.125` actually.
![image](https://user-images.githubusercontent.com/33336732/165427396-01155497-e8a0-46ed-97b8-2f014d58e146.png)

I started MiniKube with `--driver=docker` before, `192.168.49.2` was the address at that time. Then I recreated MiniKube with `--driver=none`, so the address changed to the bare metal's.

**Comment by JingChen23** [comment]
So it still doesn't work? I mean `kubefate version`

**Comment by fangxiaoran** [comment]
Yes, still got an error, "**kubefate service connection error, 503 Service Temporarily Unavailable. Please try again later or check the pod status of kubefate**". 😥

**Comment by JingChen23** [comment]
We cannot reproduce the issue, need you to check what is the difference between your steps and the tutorial's. If you find any other clue you can post here, thanks.

**Comment by bitdaocao** [comment]
hello，i meet the same problem，i installe ingress-nginx from deploy.yaml,and use thirdpary images replaced k8s.gcr.io/ingress-nginx/controller:v1.2.0。

**Comment by fangxiaoran** [comment]
> hello，i meet the same problem，i installe ingress-nginx from deploy.yaml,and use thirdpary images replaced k8s.gcr.io/ingress-nginx/controller:v1.2.0。

And has it been fixed? @bitdaocao

**Comment by bitdaocao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JingChen23** [comment]
@fangxiaoran  I just come up with something, could you please show your ingressclass by `kubectl get ingressclass`?

As @bitdaocao mentioned, he can make things work by using the ingress controller installed by minikube addons. This is also what we do in the tutorial. Actually the ingress controller is of version "v0.44.0", and this old version will not install an ingressclass for us but can actually take control all of the dangling ingresses, by default.

Now as you install a very new version ingress controller, this controller may need you to setup an ingress class or has set up an ingress class for you already. So you need to make sure in kubefate.yaml, line 245, the ingress class name is the expected one. Currently it should be:

`ingressClassName: nginx`

**Comment by fangxiaoran** [comment]
> > > hello，i meet the same problem，i installe ingress-nginx from deploy.yaml,and use thirdpary images replaced k8s.gcr.io/ingress-nginx/controller:v1.2.0。
> > 
> > 
> > And has it been fixed? @bitdaocao
> 
> yes，i had fix it，in my opinion，please start minikube with --driver=none, and please enable ingress-nginx with this "sudo minikube addons enable ingress".

Thanks for replying. I did exactly the same steps. So weird.

**Comment by fangxiaoran** [comment]
> @fangxiaoran I just come up with something, could you please show your ingressclass by `kubectl get ingressclass`?
> 
> As @bitdaocao mentioned, he can make things work by using the ingress controller installed by minikube addons. This is also what we do in the tutorial. Actually the ingress controller is of version "v0.44.0", and this old version will not install an ingressclass for us but can actually take control all of the dangling ingresses, by default.
> 
> Now as you install a very new version ingress controller, this controller may need you to setup an ingress class or has set up an ingress class for you already. So you need to make sure in kubefate.yaml, line 245, the ingress class name is the expected one. Currently it should be:
> 
> `ingressClassName: nginx`

Hi, I checked `ingressclass` and got "**No resources found**". Btw, I think the version of ingress controller in my side is also "**v0.44.0**". Am I right?

![image](https://user-images.githubusercontent.com/33336732/167246704-b56407e1-3569-4390-8ccb-ad06dd20d8d1.png)

**Comment by fangxiaoran** [comment]
@JingChen23 I think I found the reason. It's a proxy issue. My machine is behind a corporate proxy and after adding `export no_proxy=${no_proxy},example.com`, `kubefate version` works fine.

We can close the issue. Thanks for the patience and kind help.

**Comment by shivaylamba** [comment]
I followed all these steps but still doesn't work for me @fangxiaoran @JingChen23 @bitdaocao 

* kubefate commandLine version=v1.4.4
* kubefate service connection error, Post "http://example.com/v1/user/login": dial tcp 192.168.100.123:80: i/o timeout
* 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19529592/186046494-389e6ebc-f60d-49c1-8fff-16da7bca8e3c.png">


[root@centos kubefate]# kubectl get ingress -A
NAMESPACE   NAME       CLASS   HOSTS         ADDRESS        PORTS   AGE
kube-fate   kubefate   nginx   example.com   192.168.49.2   80      11m

I did set minikube start -driver=none 
and minikube addons enable ingress

**Comment by bitdaocao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shivaylamba** [comment]
@JingChen23 I am supposed to present a recording demo for running FATE Cluster at a conference tomorrow. But having been facing error in running Fate Cluster on a CentOS machine on DigitalOcean.  is there any publicly accessible example where I could run it. I really need to be able to run the demo. But I am consistently facing error with running the kubefate command.

**Comment by JingChen23** [comment]
@shivaylamba Please show me the content of your config.yaml file.
Also please print all the services in your K8s cluster, thanks.

**Comment by bitdaocao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
