### ISSUE TITLE
kubefate是否有mac版本？

### ISSUE THREAD

**Issue by ghl116** [FederatedAI/KubeFATE#599]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **

**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

**Desktop (please complete the following information):**

**To Reproduce**

Clear how to reproduce your problem.

**What happen?**

Clear the unexpected response.

**Screenshots**

**Additional context**

**Comment by JingChen23** [comment]
Mac is the same with linux, you can install Kubefate if you can install Kubernetes (for example, minikube) on Mac.
