### ISSUE TITLE
what should i  do when the third party or fourth party or even more parties want to join into current env when i use docker-compose deploying environment？

### ISSUE THREAD

**Issue by HelloLadsAndGents** [FederatedAI/KubeFATE#60]
Hi , i have succesfully deployed the FATE env with this parties.conf and it runs well when i only use this two nodes:
user=app
dir=/data/projects/fate
partylist=(10000 9999)
partyiplist=(172.40.20.3 172.40.20.5)
venvdir=/data/projects/fate/venv

**i meet this problem when i use when i'm trying to add another host to this current env**
first i update parties.conf:
user=app
dir=/data/projects/fate
partylist=(10000 9999 9998)
partyiplist=(172.40.20.3 172.40.20.5 172.40.20.7)
venvdir=/data/projects/fate/venv

and i execute : bash generate_config.sh

then : bash docker_deploy.sh 9998

and i got the successful deployment info

but this problem occurred to me
![question](https://user-images.githubusercontent.com/25575793/70035723-68085e00-15ee-11ea-9fd6-6daf55eb578c.png)
when i'm using party 10000  and party 9998 to run a job

can you tell me how to add the third and fourth or more parties to current docker env and how should i use them ? thanks

**Comment by jiahaoc1993** [comment]
@HelloLadsAndGents Hi, basically you have two options to make it works:
1. Redeploy the exchange with the newly generated configuration.
2. Add route rule to the routeing table of the exchange manually, a sample is a followed :
```
9998: {
    "default" : [
    { "ip" :  "172.40.20.7"
      "port": 9371
    } ]
}
```

**Comment by HelloLadsAndGents** [comment]
thanks,but i'm still wondering that

1.does "redeploy the exchange with the newly generated configuration" means: use the new conf to deploy all three servers? and the conf is like:
user=app
dir=/data/projects/fate
partylist=(10000 9999 9998)
partyiplist=(172.40.20.3 172.40.20.5 172.40.20.7)
venvdir=/data/projects/fate/venv


2.how can i "add route rule to the routing table of the exchange"
i have searched mysql tables in docker and did't find any tables related to routing table
can u tell me where is the file that i should change ? and should i change all the files in three servers?

**Comment by jiahaoc1993** [comment]
@HelloLadsAndGents for question 1, run the following command to redeploy exchange:
```bash docker_deploy.sh exchange```.
as for question 2, you could log in to the exchange container to update the routing table which locates at "/data/projects/fate/proxy/conf/route_table.json". You don't need to update the rule on all three servers, only need to update the exchange.

**Comment by HelloLadsAndGents** [comment]
@jiahaoc1993 thank you so much,i tried the second way and succeed
