### ISSUE TITLE
by docker compose  installation  Fate1.7.2  job got stuck when intersection step

### ISSUE THREAD

**Issue by ghl116** [FederatedAI/KubeFATE#605]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  FATE 1.7.2

**MUST** Please state the KubeFATE and FATE version you found the issue  FATE1.7.2

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: [e.g. iOS]   centos
 - Version [e.g. 22]  7.9

**Desktop (please complete the following information):**

**To Reproduce**

 follow the step  "Submit a training task"(https://fate.readthedocs.io/en/latest/tutorial/dsl_conf/dsl_conf_tutorial/#submit-a-training-task)   https://fate.readthedocs.io/en/latest/tutorial/dsl_conf/dsl_conf_tutorial/  
**What happen?**
intersection step get stuck

**Screenshots**

![image](https://user-images.githubusercontent.com/19288752/165774067-660df8c4-0b3e-4ced-b177-53864311baed.png)

**Additional context**

I tried a lot of examples ，and get the same result.
and I checked the job and docker resource,  It was not busy.  I think the job gets stuck with intersection step.

**Comment by JingChen23** [comment]
https://github.com/FederatedAI/FATE-Board
You need to find information here to learn about how to check the log of the intersection component.

**Comment by ghl116** [comment]
I find the answer. I start the job from the host.  When I start job from guest, It is resoveld
