### ISSUE TITLE
processor in session meta is not valid ERROR

### ISSUE THREAD

**Issue by zhanhtCN** [FederatedAI/KubeFATE#607]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.7.0

os:
 - OS: centos 7
 - docker 20.10.7

已经将docker升级到20.10版本，但是依然有如下报错
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/96578077/167078150-44204f59-c2ed-4172-a5d7-410c928a8a80.png">

<img width="681" alt="image" src="https://user-images.githubusercontent.com/96578077/167078313-171da4b7-fa1e-4546-a6f4-c910c334c1cf.png">

**Comment by owlet42** [comment]
@zhanhtCN Which FATE version did you deploy and how did you get this error?

**Comment by JingChen23** [comment]
@zhanhtCN Do we still have this issue?
