### ISSUE TITLE
How can i get the parameters transferred between Party A and Party B , so i can prove it is safe ?

### ISSUE THREAD

**Issue by HelloLadsAndGents** [FederatedAI/KubeFATE#61]
when we are running jobs ， we can only get the information of gradient descent rate and some other info , we really want to get some more info like parameters so we can prove that info transferred between two partis can be safe

 and how can i print out these two part?
![para](https://user-images.githubusercontent.com/25575793/70036613-0ea12e80-15f0-11ea-9ba0-c46c5209a81e.png)

thanks

**Comment by LaynePeng** [comment]
No this feature in FATE, but we can hack in algorithms, and try to log. But please note these data is sensitives.
