### ISSUE TITLE
kubernates 1.24.0上部署1.5.0的examples中的cluster.yaml和1.8.0的examples中的cluster-serving.yaml报错：no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by xinsibo** [FederatedAI/KubeFATE#618]
**What deployment mode you are use?  **
 Kuberentes.1.24.0

**What KubeFATE and FATE version you are using?  **
1.8.0，1.5.0

**MUST** Please state the KubeFATE and FATE version you found the issue
1.8.0，1.5.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: [ubuntu on windows wsl2,]
 - Version [20.04]

**Desktop (please complete the following information):**

 - OS: [ubuntu on windows wsl2,]
 - Browser [edge]
 - Version [100]

**To Reproduce**

kubfate 1.8.0版本下部署example中的/party-9999/cluster-serving.yaml和kubfate 1.5.0版本下部署example中的/party-9999/cluster.yaml失败，kubefate job describe显示原因： no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

**What happen?**

kubfate 1.8.0版本下部署example中的/party-9999/cluster-serving.yaml和kubfate 1.5.0版本下部署example中的/party-9999/cluster.yaml失败，kubefate job describe显示原因： no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

**Screenshots**

![image](https://user-images.githubusercontent.com/31228992/169194395-9e6b06f1-6a78-4be5-94d4-75d814478c41.png)

**Additional context**

**Comment by JingChen23** [comment]
This is because `networking.k8s.io/v1beta1` is not compatible with k8s 1.24.0, you need to lower down the k8s version.
The k8s version should be >=1.19 and < 1.22, not 100% sure, you need to check it on k8s document.
