### ISSUE TITLE
1.8.0和1.5.3版本中的notebook的example缺失toy_example

### ISSUE THREAD

**Issue by xinsibo** [FederatedAI/KubeFATE#619]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
1.8.0和1.5.3
**MUST** Please state the KubeFATE and FATE version you found the issue
1.8.0和1.5.3
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: [ubuntu on windows wsl2]
 - Version [20.04]

**Desktop (please complete the following information):**

 - OS: [ubuntu on windows wsl2]
 - Browser [edge]
 - Version [100]

**To Reproduce**

party-9999.notebook.example.com中缺失toy_test.sh中的toy_example例子

**What happen?**

party-9999.notebook.example.com中缺失toy_test.sh中的toy_example例子

![333109e2ce8c9ccc603fed57c718303](https://user-images.githubusercontent.com/31228992/169193759-970a40a7-1e74-437e-8306-b56c8e0c9d94.png)

**Additional context**

**Comment by JingChen23** [comment]
Could you please post here the readme file you are refering to?

**Comment by xinsibo** [comment]
> Could you please post here the readme file you are refering to?

![image](https://user-images.githubusercontent.com/31228992/169195007-5021bb27-e0aa-42ab-a517-9c25f9c29bc2.png)

**Comment by JingChen23** [comment]
That file only exist in docker-compose mode. There are other ways for you to try FATE in k8s mode, such as:
1. Run the examples in the `Pipeline` directory.
2. Run the "toy_examoke_submit_job" script in the Toy_example directory.

**Comment by xinsibo** [comment]
notebook中没有toy_example这个文件夹
