### ISSUE TITLE
Version number is wrong

### ISSUE THREAD

**Issue by xinfang52013141** [FederatedAI/KubeFATE#62]
https://github.com/FederatedAI/FATE/blob/master/docker-build/build_cluster_docker.sh
from https://github.com/FederatedAI/FATE/blob/master/cluster-deploy/scripts/default_configurations.sh
version=1.1.1  ---Represents all .tar.gz version numbers
egg_version=1.1
meta_service_version=1.1
roll_version=1.1
federation_version=1.1
proxy_version=1.1
fateboard_version=1.1
fateflow_version=1.1
These represent the version number of the jar package

**Comment by jiahaoc1993** [comment]
Will be fixed later.
