### ISSUE TITLE
希望将fate-Serving的Ingress的api由networking.k8s.io/v1beta1升级到networking.k8s.io/v1，以适配kubernates-1.22以上版本

### ISSUE THREAD

**Issue by xinsibo** [FederatedAI/KubeFATE#621]
**Is your feature request related to a problem? Please describe.**
最新版本的k8s安装cluster-serving时报错：https://github.com/FederatedAI/KubeFATE/issues/618

**Describe the solution you'd like**
支持最新的k8s，由networking.k8s.io/v1beta1升级到networking.k8s.io/v1

**Describe alternatives you've considered**

**Additional context**

**Comment by JingChen23** [comment]
Has been done: https://github.com/FederatedAI/KubeFATE/pull/606/files

Will be released in FATE-Serving v2.1.5

**Comment by JingChen23** [comment]
When it released, I will close this issue, please stay tuned, thanks.
