### ISSUE TITLE
how to install fate_test in docker-compose deployment mode ?

### ISSUE THREAD

**Issue by ghl116** [FederatedAI/KubeFATE#623]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
Fate1.8
**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: [e.g. iOS]  centos7.9

**Comment by owlet42** [comment]
First use exec to enter python's container
```bash
docker-compose exec python bash
```
Then use pip to install
```bash
cd fate
pip install -e python/fate_client
pip install -e python/fate_test
```
Next：https://fate.readthedocs.io/en/latest/tutorial/fate_test_tutorial/

**Comment by JingChen23** [comment]
@ghl116 Could we close this issue now?

**Comment by ghl116** [comment]
Sorry for my late response. 
I follow the instruction ,but get the error below:

`(app-root) bash-4.2# pip install -e python/fate_client
ERROR: python/fate_client is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

(app-root) bash-4.2# pip install -e python/fate_test
ERROR: python/fate_test is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
(app-root) bash-4.2#
`

**Comment by owlet42** [comment]
@ghl116 Please check your `workdir`(command pwd), it should be `/data/projects/fate/fate`

**Comment by ghl116** [comment]
Thank you. In the dir about  "/data/projects/fate/fate" , I succeed in installing the fate_test and fate_client.

But when I test the fate_test command,
```
fate_test suite -i /data/projects/fate/examples/dsl/v2/hetero_linear_regression/hetero_linr_testsuite.json
```
I get the following error.
```
ModuleNotFoundError: No module named 'torchvision'
```
And I use pip command to  install the module  but  failed.

**Comment by owlet42** [comment]
@ghl116 Upgrade pip to the latest version and try again.
