### ISSUE TITLE
The party ID should change to 1, 2, 3, 4, etc., rather than 9999, 8888...;

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/KubeFATE#633]
The party ID should change to 1, 2, 3, 4, etc., rather than 9999, 8888...;
1,2,3,4 look more concise and convenient for voice communication.

**Comment by asdfsx** [comment]
right now, we're using 10000、20000、30000 instead

**Comment by JingChen23** [comment]
This cannot be done easily, because in our scripts, we use sed .... too much.

For example, after this change, the opereation like   

```
sed -i 's/9999/10000/g' fate-10000.yaml
```

will become

```
sed -i 's/1/2/g' fate-2.yaml
```

This will be a disaster because this will change v1.9.0 to v2.9.0

Close this issue as won't fix.
