### ISSUE TITLE
Kubernetes pod evicted state

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#64]
I am using Kube deploy. During the training, the egg service pod status becomes 'evicted' after running for sometime. I think this is due to low memory. Is anyone else experience this?

**Comment by jiahaoc1993** [comment]
It seems the only solution is to increase your memory size.

**Comment by cometta** [comment]
what is the recommended memory for each party? Is this due to memory leak, if yes, then increase memory size won't help

**Comment by cometta** [comment]
here is the exact log 

```
4m11s       Warning   Evicted               pod/egg-<id here>    The node was low on resource: memory. Container egg was using 5053216Ki, which exceeds its request of 0.
4m11s       Normal    Killing               pod/egg-<id here>    Stopping container egg
4m          Warning   ExceededGracePeriod   pod/egg-<id here>    Container runtime did not kill the pod within specified grace period.
4m7s        Normal    Scheduled             pod/egg-<id2 here>    Successfully assigned fate-10000/egg-<id2 here> to aks-nodepool1-<id>
4m7s        Warning   Evicted               pod/egg-<id2 here>    The node had condition: [MemoryPressure].
```

**Comment by jiahaoc1993** [comment]
@cometta  checkout 3.1 for server configuration: https://github.com/FederatedAI/FATE/tree/master/cluster-deploy

**Comment by cometta** [comment]
there is option to allocated cpu/memory for each pod running in kubernetes. from the link that you shared, it 16gb is for all the services running one a machine. Any advice on how do i set it per pod?

**Comment by LaynePeng** [comment]
Close the issue cuz new k8s deployment have been release. The customized resource setting will be supported soon.
