### ISSUE TITLE
When using docker-deploy, add the SSH port configuration to solve the problem that the SSH port is not 22

### ISSUE THREAD

**Issue by magic-hya** [FederatedAI/KubeFATE#648]
**Is your feature request related to a problem? Please describe.**
When docker-deploy is used, the SSH port is not 22, so docker_deploy.sh cannot be used to realize automatic deployment

**Describe the solution you'd like**
I added the "ssh_port" variable to the ".Env" file, and then modified the "docker_deploy.sh" file. I don't know if this change is reasonable

**Describe alternatives you've considered**

**Additional context**

**Comment by JingChen23** [comment]
Hi, I cannot have a clear understanding for this issue, and I have a couple of questions:
1. What do you mean by "cannot be used to realize automatic deployment", on which line your automation broke?
2. Why port is not 22 will make the automation fail?
3. Why the port is not 22, how do you know that?
4. How do you modify the docker_deploy.sh file, if you don' t tell that clearly, we cannot judge if that is reasonable.

**Comment by magic-hya** [comment]
> Hi, I cannot have a clear understanding for this issue, and I have a couple of questions:
> 
> 1. What do you mean by "cannot be used to realize automatic deployment", on which line your automation broke?
> 2. Why port is not 22 will make the automation fail?
> 3. Why the port is not 22, how do you know that?
> 4. How do you modify the docker_deploy.sh file, if you don' t tell that clearly, we cannot judge if that is reasonable.

Thank you for your question:
1.Broke when sending config TAR to another server.
2.Because the script command uses port 22 by default
3.Some machines have changed the default port 22 to another port,Machine login information notified by the administrator
4.Change like follows:
```bash
scp -P ${SSH_PORT} ${WORKINGDIR}/outputs/confs-$target_party_id.tar $user@$target_party_ip:~/
ssh -p ${SSH_PORT} -tt $user@$target_party_ip <<eeooff
```

**Comment by magic-hya** [comment]
OK!
I am currently using version 1.7.2. I will test it under 1.9.0, and then contributing a pull request.
