### ISSUE TITLE
generate_config minor error

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#65]
for this line

> sed -i.bak "/'host':.*/{x;s/^/./;/^\.\{2\}$/{x;s/.*/    'host': '${redis_ip}',/;x};x;}" ./confs-$party_id/confs/fate_flow/conf/settings.py
	    
i get error

> sed: 1: "/'host':.*/{x;s/^/./;/^ ...": extra characters at the end of x command

on macos

**Comment by jiahaoc1993** [comment]
The `Bash` in linux is different from the macos, and we have not supported macos yet.

**Comment by cometta** [comment]
thanks for the info
