### ISSUE TITLE
min_test_task error in docker cluster version

### ISSUE THREAD

**Issue by Hyberlion** [FederatedAI/KubeFATE#66]
The toy example can run correctly in my docker cluster version, but when I run the min_test_task in guest, got error as followed:

![image](https://user-images.githubusercontent.com/18738030/71435586-95938380-2724-11ea-8026-a695262626c4.png)

**Comment by jiahaoc1993** [comment]
How did you run your mini_test? please provide more detials about your command.

**Comment by Hyberlion** [comment]
Thanks for your reply!
In host:
![image](https://user-images.githubusercontent.com/18738030/71436045-962d1980-2726-11ea-974e-9916ebdfe592.png)
In guest:
![image](https://user-images.githubusercontent.com/18738030/71436085-beb51380-2726-11ea-95d6-119efde0b835.png)

**Comment by Hyberlion** [comment]
I mix the party id of guest and host in run_task.py.
