### ISSUE TITLE
<_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "failed to connect to all addresses"

### ISSUE THREAD

**Issue by SnakeCN21** [FederatedAI/KubeFATE#664]
**What deployment mode you are use?  **
docker-compose

**What KubeFATE and FATE version you are using?  **
1.8.0

**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: CentOS
 - Version 7.9.2009

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome
 - Version: 102.0.5005.115

**To Reproduce**

我是按照 https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md 这份帖子操作的，在进行到 <加载模型>的环节的时候 Guest 机器报出了错误。内容如下:

<_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "failed to connect to all addresses" debug_error_string = "{"created": "@1655193881.341454837", "description": "Failed to pick subchannel", "file": "src/core/ext/filters/client_channel/client_channel.cc", "file_line":3876, "referenced_errors":[{"created": "@1655193881.341427428", "description": "failed to connect to all addresses", "file": "src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc", "file_line":395, "grpc_status":14}]}

**Screenshots**

![微信图片_20220614160521](https://user-images.githubusercontent.com/49633350/173533757-2b01fea1-ee8f-4b5a-acde-8471b006ecdb.png)

**Comment by JingChen23** [comment]
Please share the parties.conf file you used.

**Comment by SnakeCN21** [comment]
> Please share the parties.conf file you used.

Thanks for your reply, here you are.

My deployment is configured as
192.168.201.163 (host)
192.168.201.164 (guest)

I edited the parties.conf file on the host machine, and then executed the "bash ./docker_deploy.sh all" command to complete the deployment of KubeFATE on the two machines. If the IP setting is wrong, why did the previous steps pass smoothly until the step <load model> failed?

![163](https://user-images.githubusercontent.com/49633350/173974838-43c0adf8-681e-427d-b4f3-968446baf79d.png)

![164](https://user-images.githubusercontent.com/49633350/173974845-3555b92b-41e3-47db-9cbf-8c863670e8ff.png)

![Untitled picture](https://user-images.githubusercontent.com/49633350/173975871-2af36f3c-3f02-40d6-9891-2ef54c203fbf.png)

**Comment by owlet42** [comment]
@SnakeCN21 It looks like FATE-Serving isn't starting, you can clean up the deployed FATE and FATE-Serving and redeploy, or start it manually to make sure both FATE and FATE-Serving are running fine.

**Comment by SnakeCN21** [comment]
> @SnakeCN21 It looks like FATE-Serving isn't starting, you can clean up the deployed FATE and FATE-Serving and redeploy, or start it manually to make sure both FATE and FATE-Serving are running fine.

Hi owlet,
According to your reply, I have redeployed KubeFATE again after totally clearing FATE, and all the services have been started successfully.
But when I go to the step "model load", the same error is still reported. I don't know what the error is that caused this phenomenon to happen.

![1](https://user-images.githubusercontent.com/49633350/174040056-e0131995-98a8-4042-845f-419e37affc4d.png)
![2](https://user-images.githubusercontent.com/49633350/174040079-b209df1d-9b0e-479e-b0ba-b4ce161a5991.png)
![Untitled picture](https://user-images.githubusercontent.com/49633350/174040156-593910a6-133e-4ca8-8f69-c01ea53015df.png)

**Comment by SnakeCN21** [comment]
> Hi, I tried to reproduce this issue, while it worked well and I passed every step on the document.

Hi n063h,
That's what I feel really weird.
I did all the previous steps and passed well, only the error occurred when I move to "model load". Is there any other possible that could cause the failure? If you need other log information, I will provide them as much as possible.

**Comment by SnakeCN21** [comment]
I did the whole tasks after I tried many times and here is my advice. I'm not sure if I can solve this problem perfectly on other machines.

1. stop and disable firewalld.
2. docker-compose down all containers.
3. restart OS.
4. docker-compose up all containers.
5. restart steps at "model deploy" on guest server.
6. done, all passed.

**Comment by JingChen23** [comment]
Glad to know that things work now. Thanks for providing the solution. This will be we a valuable guidance for other people, thanks @SnakeCN21 !
