### ISSUE TITLE
client镜像中查询output_data_summary_count_limit变量出错

### ISSUE THREAD

**Issue by wanglg007** [FederatedAI/KubeFATE#665]
（1）在联通云的服务器上使用kubefate1.8版本中的docker-deploy进行部署，其相关版本信息为：
![4b4d6666b3c9061993f5321d847178a](https://user-images.githubusercontent.com/40556406/173764788-35ccf503-e594-46a3-a78b-2616a095db1d.png)
（2）所有服务启动；
（3）修改/data/projects/fate/conf-10000/confs/fate_flow/conf/job_default_config.yaml中的output_data_summary_count_limit为150；
![2e2bbbcdb7d190c7fc0ed4b18695ad0](https://user-images.githubusercontent.com/40556406/173765593-f0b97978-e8ea-4482-8b56-ad80304f9120.png)

（4）进入client镜像执行flow server reload查看output_data_summary_count_limit变量为100
![55e2a2a81335501bf58660249d02c8f](https://user-images.githubusercontent.com/40556406/173765647-7cdd5fbb-673d-4481-b16f-316df2bd088e.png)

备注：在FATE1.8源码中进行单步跟踪，可以看到该值为150。但是使用kubefate.18的docker-deploy部署后，该值在client镜像中的值与配置文件不一致；

**Comment by JingChen23** [comment]
有一种可能性是，你没有重启fateflow的容器，导致那个配置虽然在fateflow容器mount的volumn上变成了150，但是fateflow内存中的值还是100，这就导致你在client端掉fateflow的API拿到的还是100。麻烦重启fateflow的容器之后再试一下。

**Comment by owlet42** [comment]
容器内修改这个文件`/data/projects/fate/fateflow/conf/job_default_config.yaml`就可以生效。目前job_default_config.yaml mount目录错误。

**Comment by JingChen23** [comment]
@wanglg007 
Thanks for reporting this issue, we will release the fix with v1.9.0, not the fix is on the develop-v1.9.0 branch.
Close this issue for now.
