### ISSUE TITLE
版本1.8中的k8s-deploy/kubefate.yaml中kubefate镜像版本为1.4.4

### ISSUE THREAD

**Issue by wanglg007** [FederatedAI/KubeFATE#673]
（1）从GitHub中将kubetate1.8版本进行下载后，通过查看k8s-deploy/kubefate.yaml中的kubefate镜像版本依然为1.4.4，不知道是Bug吗？截图如下：
![1656037031496(1)](https://user-images.githubusercontent.com/40556406/175449147-df6b58c4-90cd-4082-9464-4159b12547f2.jpg)

**Comment by gps949** [comment]
我不认为这是个bug，你可以看一下docker hub的tag记录：https://hub.docker.com/r/federatedai/kubefate/tags
不考虑latest，1.4.4是kubefate镜像最新版本号（同时也是kubefate cli的最新版本号）。
1.8.0实质上是能支持部署的fate的最新版本号。

不过这样两边版本号不一致，kubefate release版本号和镜像版本号不一致，确实很容易让人迷惑。
出于何种考量可能需要kubefate团队解释一下，或者最好在之后能解决这种版本割裂/不对齐的问题。

**Comment by JingChen23** [comment]
kubefate一开始是给fate准备的运维工具，其工作包含两方面：
1. FATE各组件容器化+开发helm chart
2. Kubefate CLI工具和Kubefate Service.

对于1，版本是1.8，版本跟着FATE走，我们release也以这个版本为准。
对于2，版本是1.4.4，是Kubefate CLI和service的version。

**Comment by JingChen23** [comment]
当然，版本可以进行组合，比如，你可以用1.4.4的kubefate cli，去操控1.4.3的kubefate service，然后去管理FATE 1.7的cluster。

**Comment by JingChen23** [comment]
Close the issue as this is not a bug.
