### ISSUE TITLE
KubeFate部署后，报错

### ISSUE THREAD

**Issue by lvying0019** [FederatedAI/KubeFATE#682]
![a2aac599c4c232ada4c76fe98f5fe4c](https://user-images.githubusercontent.com/62459458/177275590-5b3c619d-986e-4683-9c89-38d637446ff2.jpg)

**Comment by JingChen23** [comment]
Sorry, cannot support you with just such a screenshot. More information is needed.

**Comment by owlet42** [comment]
@lvying0019 These few warnings of FATE-Serving do not affect usage.

**Comment by lvying0019** [comment]
谢谢，的确不影响使用。不过，如果需要更多信息用于排查该问题，需要提供哪些信息？

**Comment by JingChen23** [comment]
Forget about my previous reply, no information is needed, these 2 warnings (not errors) should be expected and do not affect the usage.

For getting more information with regarding to these 2 warnings, I would suggest to take a look at the doc of the FATE serving project, or raise an issue in the repo of FATE-Serving.
