### ISSUE TITLE
容器内的时间不对

### ISSUE THREAD

**Issue by lvying0019** [FederatedAI/KubeFATE#684]
用docker方式部署的kubefate，容器中的时间是标准时间，与宿主机时间不一致，建议在docker-compose.yml中增加与宿主机的时区和时间文件夹的映射关系~

**Comment by JingChen23** [comment]
Is there any easy way to reproduce the time-insync scenario?


I just find a solution here:
https://stackoverflow.com/questions/24551592/how-to-make-sure-dockers-time-syncs-with-that-of-the-host

Just need some info for making it easier for the testing.

If you need this feature urgently, it is recommendated that you help us to do this improvement by a pull request.
