### ISSUE TITLE
通信 SSL 加密

### ISSUE THREAD

**Issue by hqsh** [FederatedAI/KubeFATE#695]
docker compose 方式部署的，是不是没有通信 SSL 加密？如果想加密的话，有办法通过修改部署的配置文件来实现吗？

**Comment by LaynePeng** [comment]
Docker-compose is positioned as a dev environment, so to reduce the complexity we won't support SSL right now. And the community is planning a standalone version, which may fit in one-machine requirement. If you are going to use a cluster environment, suggest using K8s version which supports SSL.

**Comment by owlet42** [comment]
This may be supported in 1.9.0. #588

**Comment by owlet42** [comment]
Any suggestions or comments can be made on #588 . This issue will be closed.
