### ISSUE TITLE
Can kubeFate deploy old fate version?

### ISSUE THREAD

**Issue by hqsh** [FederatedAI/KubeFATE#702]
**Is your feature request related to a problem? Please describe.**
I need use v1.9 kubeFATE new features. But I need to deploy fate v1.7.1.1.
Whether kubeFATE can support this deployment way?
If it is supported. Is it just modify the "TAG" value in "docker-deploy/.env" ?
Thank you!

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by JingChen23** [comment]
> If it is supported. Is it just modify the "TAG" value in "docker-deploy/.env" ?

Yes you can.

**Comment by JingChen23** [comment]
Hi, WRT to the TLS of rollsite in docker compose mode, I have prepared a [doc](https://github.com/FederatedAI/KubeFATE/blob/develop-1.9.0/docs/Eggroll_with_TLS.md#docker-compose-mode) for you.

BTW, may I know which organizaiton you work for?
