### ISSUE TITLE
请问，kubefate现在支持backend=eggroll的时候，多个nodemanager的部署吗？

### ISSUE THREAD

**Issue by lvying0019** [FederatedAI/KubeFATE#716]
同题目

**Comment by JingChen23** [comment]
https://github.com/FederatedAI/KubeFATE/blob/d710a7dd448bad6f6c6caf59581bf251ecbb45bf/helm-charts/FATE/values-template-example.yaml#L101

Yes, you can configure the number of node managers in k8s mode, check above example to know how to modify the cluster.yaml file.

**Comment by lvying0019** [comment]
> https://github.com/FederatedAI/KubeFATE/blob/d710a7dd448bad6f6c6caf59581bf251ecbb45bf/helm-charts/FATE/values-template-example.yaml#L101
> 
> 
> 
> Yes, you can configure the number of node managers in k8s mode, check above example to know how to modify the cluster.yaml file.

我不能在docker deploy方式实现吗

**Comment by JingChen23** [comment]
Sorry, you can't.
