### ISSUE TITLE
Generate TLS files for docker compose failed: ERROR:There is already a certificate for /CN=fate9999.fl.xxxxx.com

### ISSUE THREAD

**Issue by hqsh** [FederatedAI/KubeFATE#728]
Issue 707 (https://github.com/FederatedAI/KubeFATE/issues/707) 

Follow [JingChen23](https://github.com/JingChen23) suggestion (delete all files and use the command in the documents), I found it failed again.
openssl ca -config openssl.cnf -days 10000 -extensions server_cert -notext -md sha256 -in fate-9999/server.csr -out fate-9999/server.crt
Using configuration from openssl.cnf
Enter pass phrase for /home/credit/my-ca/private/ca.key.pem:
Check that the request matches the signature
Signature ok
ERROR:There is already a certificate for /CN=fate9999.fl.xxxxx.com
The matching entry has the following details
Type          :Valid
Expires on    :20500106142524Z
Serial Number :1000
File name     :unknown
Subject Name  :/CN=fate9999.fl.xxxxx.com

This is my commands, same as the documents. Three CNs are: fl.xxxxx.com, fate9999.fl.xxxxx.com,  fate9999.fl.xxxxx.com

mkdir my-ca
cd my-ca
wget https://raw.githubusercontent.com/apache/pulsar/master/tests/certificate-authority/openssl.cnf
export CA_HOME=$(pwd)
mkdir certs crl newcerts private
chmod 700 private/
touch index.txt
echo 1000 > serial

openssl genrsa -aes256 -out private/ca.key.pem 4096
chmod 400 private/ca.key.pem

openssl req -config openssl.cnf -key private/ca.key.pem \
    -new -x509 -days 7300 -sha256 -extensions v3_ca \
    -out certs/ca.cert.pem                                (CN: fl.xxxxx.com)
chmod 444 certs/ca.cert.pem

mkdir fate-9999
openssl genrsa -out fate-9999/client_rsa.key 2048
openssl pkcs8 -topk8 -inform PEM -in fate-9999/client_rsa.key -outform PEM -out fate-9999/client.key -nocrypt

openssl req -config openssl.cnf -key fate-9999/client.key -new -sha256 -out fate-9999/client.csr                  (CN: fate9999.fl.xxxxx.com)

openssl ca -config openssl.cnf -days 10000 -notext -md sha256 -in fate-9999/client.csr -out fate-9999/client.crt

openssl genrsa -out fate-9999/server_rsa.key 2048
openssl pkcs8 -topk8 -inform PEM -in fate-9999/server_rsa.key -outform PEM -out fate-9999/server.key -nocrypt
openssl req -config openssl.cnf -key fate-9999/server.key -new -sha256 -out fate-9999/server.csr                  (CN: fate9999.fl.xxxxx.com)

openssl ca -config openssl.cnf -days 10000 -extensions server_cert -notext -md sha256 -in fate-9999/server.csr -out fate-9999/server.crt

**Comment by JingChen23** [comment]
```
mkdir fate-9999
openssl genrsa -out fate-9999/client_rsa.key 2048
openssl pkcs8 -topk8 -inform PEM -in fate-9999/client_rsa.key -outform PEM -out fate-9999/client.key -nocrypt

openssl req -config openssl.cnf -key fate-9999/client.key -new -sha256 -out fate-9999/client.csr (CN: fate9999.fl.xxxxx.com)

openssl ca -config openssl.cnf -days 10000 -notext -md sha256 -in fate-9999/client.csr -out fate-9999/client.crt

openssl genrsa -out fate-9999/server_rsa.key 2048
openssl pkcs8 -topk8 -inform PEM -in fate-9999/server_rsa.key -outform PEM -out fate-9999/server.key -nocrypt
openssl req -config openssl.cnf -key fate-9999/server.key -new -sha256 -out fate-9999/server.csr (CN: fate9999.fl.xxxxx.com)
```
You generate the csr for "fate9999.fl.xxxxx.com" twice right?

**Comment by hqsh** [comment]
> ```
> mkdir fate-9999
> openssl genrsa -out fate-9999/client_rsa.key 2048
> openssl pkcs8 -topk8 -inform PEM -in fate-9999/client_rsa.key -outform PEM -out fate-9999/client.key -nocrypt
> 
> openssl req -config openssl.cnf -key fate-9999/client.key -new -sha256 -out fate-9999/client.csr (CN: fate9999.fl.xxxxx.com)
> 
> openssl ca -config openssl.cnf -days 10000 -notext -md sha256 -in fate-9999/client.csr -out fate-9999/client.crt
> 
> openssl genrsa -out fate-9999/server_rsa.key 2048
> openssl pkcs8 -topk8 -inform PEM -in fate-9999/server_rsa.key -outform PEM -out fate-9999/server.key -nocrypt
> openssl req -config openssl.cnf -key fate-9999/server.key -new -sha256 -out fate-9999/server.csr (CN: fate9999.fl.xxxxx.com)
> ```
> 
> You generate the csr for "fate9999.fl.xxxxx.com" twice right?

Yes sir. I know it maybe not right. But I don't know this 3 parties as following should create how many client keys and server keys, and their CNs to type when creating keys.

|party_id|domain name|
---
|10001|fate10001.fl.xxxxx.com|
|10000|fate10001.fl.xxxxx.com|
|9999|fate9999.fl.xxxxx.com|
|none|fl.xxxxx.com|

**Comment by hqsh** [comment]
I found the CNs of ssl client files can be random.

**Comment by JingChen23** [comment]
Yes, but you cannot create 2 pairs of keys with the duplicate CN.

In this case the secrests will be registered as K8s secrets for each FATE cluster.

Because the rollsite doesn't have a UI with domain name, so the CN can be random, that's my understanding.

**Comment by yuanbw** [comment]
假设有两个参与方party-9999 和 party-10000，应该如何配置TLS通信呢？@hqsh@JingChen23 

> Yes, but you cannot create 2 pairs of keys with the duplicate CN.
> 
> In this case the secrests will be registered as K8s secrets for each FATE cluster.
> 
> Because the rollsite doesn't have a UI with domain name, so the CN can be random, that's my understanding.
