### ISSUE TITLE
duplicate zookeeper configuration

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/KubeFATE#739]
I deploy fate 1.8 by kubefate. After the cluster installed, pod python failed to start, and the error log is
```
Traceback (most recent call last):
  File "fateflow/python/fate_flow/fate_flow_server.py", line 29, in <module>
    from fate_flow.utils.base_utils import get_fate_flow_directory
  File "/data/projects/fate/fateflow/python/fate_flow/utils/__init__.py", line 16, in <module>
    from fate_flow.utils.base_utils import jprint
  File "/data/projects/fate/fateflow/python/fate_flow/utils/base_utils.py", line 18, in <module>
    from fate_arch.common.base_utils import json_dumps
  File "/data/projects/fate/fate/python/fate_arch/common/base_utils.py", line 31, in <module>
    use_deserialize_safe_module = get_base_config('use_deserialize_safe_module', False)
  File "/data/projects/fate/fate/python/fate_arch/common/conf_utils.py", line 36, in get_base_config
    config = file_utils.load_yaml_conf(conf_realpath(conf_name))
  File "/data/projects/fate/fate/python/fate_arch/common/file_utils.py", line 127, in load_yaml_conf
    "loading yaml file config from {} failed:".format(conf_path), e
OSError: [Errno loading yaml file config from /data/projects/fate/conf/service_conf.yaml failed:] while constructing a mapping
  in "/data/projects/fate/conf/service_conf.yaml", line 1, column 1
found duplicate key "zookeeper" with value "{}" (original value: "{}")
  in "/data/projects/fate/conf/service_conf.yaml", line 126, column 1
```
So I check the configmap, and find 2 zookeeper configuration, one is here https://github.com/FederatedAI/KubeFATE/blob/eb7af4bd5fb3120e15bd17d77859eaa3e6105b88/helm-charts/FATE/templates/core/fateflow/configmap.yaml#L85-L90 

another one is here
https://github.com/FederatedAI/KubeFATE/blob/eb7af4bd5fb3120e15bd17d77859eaa3e6105b88/helm-charts/FATE/templates/core/fateflow/configmap.yaml#L192-L197

the second one is added by by me in pr https://github.com/FederatedAI/KubeFATE/pull/399

To solve the problem one of them should be deleted. @LaynePeng @owlet42

**Comment by JingChen23** [comment]
Thanks for reporting the issue.

**Comment by asdfsx** [comment]
And the zookeeper can be setup in values.yaml, like below @JingChen23 

https://github.com/FederatedAI/KubeFATE/blob/a7d88399541606410b85eb6dd7da9c1abc9291e5/helm-charts/FATE/values-template-example.yaml#L246-L253

**Comment by asdfsx** [comment]
Since the #756 have been merged, this issue can be closed
