### ISSUE TITLE
docker-compose 部署集群，serving-admin报错

### ISSUE THREAD

**Issue by KJ-DS** [FederatedAI/KubeFATE#750]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
KubeFATE : 1.9.0
**MUST** Please state the KubeFATE and FATE version you found the issue

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 centos 7

**To Reproduce**
所有容器状态正常运行
![image](https://user-images.githubusercontent.com/85089771/189297195-b4f752f4-fa01-4924-b3f4-cc053332332f.png)

serving-9999-serving-adminron容器中日志文件
![image](https://user-images.githubusercontent.com/85089771/189297494-f7dfb22e-141d-4031-904d-04b1112ffcf6.png)

浏览器中serve端Cluster Checkup警告
![image](https://user-images.githubusercontent.com/85089771/189297946-1673f689-f6f8-49b2-bc80-c8159ff1e202.png)

**Comment by KJ-DS** [comment]
serving-admin中报错ip，都可以ping通

**Comment by owlet42** [comment]
@KJ-DS How did you get this error and what steps did you perform?

**Comment by KJ-DS** [comment]
安装kubefate v1.9.0版本中README_zh.md文档部署，当验证在线服务时，发现这个错误。然后就查看下serving-admin容器中的日志信息，在日志中发现了这个报错

**Comment by KJ-DS** [comment]
实际部署时，步骤如下
1、安装docker、docker-compose
2、配置fate用户免密登录
3、修改parties.conf中ip地址
4、配置env(.env)
5、生成安装包generate_config.sh
6、部署docker_deploy.sh all

然后在后续打开浏览器中serving-admin就提示warning警告，"fateflow is not found in zookeeper"

**Comment by JingChen23** [comment]
Checked with FATE-Serving folks:

This warning has no effect on usage.

FATE-Serving will firstly try to find the fateflow service in the zookeeper, if cannot get it, then will find the fateflow service from its configuration files.

In docker-compose mode we have put the fateflow service info in the config file of serving-server, so this warning can be ignored.

**Comment by KJ-DS** [comment]
感谢@https://github.com/owlet42 @https://github.com/JingChen23，这个问题困扰了我好久，多次重装都会提示，既然不影响使用，那就先不纠结了。建议在后续版本中官方可以优化下。
