### ISSUE TITLE
Kubefate发生错误MaxRetryError

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/KubeFATE#761]
发生异常断电，重启服务之后上传数据发生以下错误：
` "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='python', port=9380): Max retries exceeded with url: /v1/data/upload?%7B%22file%22:%20%22examples/data/breast_hetero_host.csv%22,%20%22id_delimiter%22:%20%22,%22,%20%22head%22:%201,%20%22partition%22:%2010,%20%22namespace%22:%20%22experiment%22,%20%22table_name%22:%20%22breast_hetero_host%22,%20%22conf_path%22:%20%22fateflow/examples/upload/upload_host.json%22,%20%22verbose%22:%200,%20%22drop%22:%200%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe458b52128>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))\n",`
请问应该怎么解决呢

**Comment by oceanqdu** [comment]
已经解决了，docker ps 与另一台虚拟机对比发现python_1这个容器没有启动。
解决办法：
1、在confs-9999和server-9999里执行docker-compose down 
2、在confs-9999和server-9999里执行docker-compose up
3、docker ps 查看发现conf_python_1这个容器已经成功启动，再次上传数据不再出现错误。

**Comment by JingChen23** [comment]
👍
