### ISSUE TITLE
啥时候能出个Kuberentes的部署教程啊，新版的

### ISSUE THREAD

**Issue by wlj521** [FederatedAI/KubeFATE#772]
啥时候能出个Kuberentes的部署教程啊，新版的
教程写的详细一些啊，如果可以，能加入二次开发的内容吗

**Comment by owlet42** [comment]
https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by wlj521** [comment]
> https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

不是，是使用Kuberentes部署kubeFATE的教程

**Comment by owlet42** [comment]
https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube_zh.md
