### ISSUE TITLE
为什么projects/fate/confs-10000/shared_dir下的federatedml是root用户生成的

### ISSUE THREAD

**Issue by wlj521** [FederatedAI/KubeFATE#775]
使用fate用户操作，部署之后projects/fate/confs-10000/shared_dir下的federatedml和examples是root用户生成的呢？
![图片](https://user-images.githubusercontent.com/20828594/195810053-470ee4a1-f22f-4c6a-979d-e58a186c1ff0.png)

**Comment by JingChen23** [comment]
@wlj521 If you ask why, then the answer is here: https://stackoverflow.com/questions/52917695/docker-compose-volume-permissions-linux
We do not have added the user configuration in the docker compose yaml file.
We can improve this part, thanks for reporting this issue.

BTW, is this a blocking issue for you?

**Comment by wlj521** [comment]
> 
没有什么阻断，如果开始部署失败的话，需要删除文件夹
