### ISSUE TITLE
v1.9.0 (FATE on Spark):data upload error

### ISSUE THREAD

**Issue by FranisiL** [FederatedAI/KubeFATE#779]
> The deployment process has used the environment and other information to refer to: https://github.com/FederatedAI/KubeFATE/issues/778#issue-1415860892

**To Reproduce**
> After docker-compose starts F ATE V1.9.0, refer to : [Uploading data of host](https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README.md) relevant data

**What happen?**

> [ERROR] [2022-10-20 15:34:37,804] [202210201534368855920] [8:139730149570304] - [task_controller.start_task] [line:104]: [Errno 2] No such file or directory: '/data/projects/spark-3.1.2-bin-hadoop3.2/bin/spark-submit'
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/controller/task_controller.py", line 93, in start_task
    run_info = backend_engine.run(task=task,
  File "/data/projects/fate/fateflow/python/fate_flow/controller/engine_controller/spark.py", line 79, in run
    return WorkerManager.start_task_worker(worker_name=WorkerName.TASK_EXECUTOR, task=task,
  File "/data/projects/fate/fateflow/python/fate_flow/manager/worker_manager.py", line 206, in start_task_worker
    p = process_utils.run_subprocess(job_id=task.f_job_id, config_dir=config_dir, process_cmd=process_cmd,
  File "/data/projects/fate/fateflow/python/fate_flow/utils/process_utils.py", line 57, in run_subprocess
    p = subprocess.Popen(process_cmd,
  File "/opt/python3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/python3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/data/projects/spark-3.1.2-bin-hadoop3.2/bin/spark-submit'

**Additional context**

You need to modify the configuration file of the fate_flow service, and change the `SPARK_HOME` in the service_conf.yaml file to `/data/projects/spark-3.1.3-bin-hadoop3.2/`, and then you can perform data uploading

**Question: Why does the image of `fateflow-spark:1.9.0-release` contain both `spark-3.1.2-bin-hadoop3.2` and `spark-3.1.3-bin-hadoop3.2` versions**

**Comment by JingChen23** [comment]
Yes, we did have this but and has been fix now.

You Kubefate should be installed before the fix so you have this issue.

To fix this issue in your environment. you just need to:
1. run `kubefate chart ls` to see the uuid of your v1.9.0 helm chart
2. run `kubefate chart delete <uuid>` to remove that chart.
3. download the updated chart from ["here"](https://github.com/FederatedAI/KubeFATE/blob/gh-pages/package/fate-v1.9.0.tgz)
4. run `kubefate chart upload -f fate-v1.9.0.tgz`

Then this will be fixed in your environment.
