### ISSUE TITLE
Expose SSH service from the python container

### ISSUE THREAD

**Issue by jiahaoc1993** [FederatedAI/KubeFATE#78]
For developers who design their own algorithm, it is inconvenient to code and debug inside the python container.
A solution to address this situation is to setup a SHH service inside the python container and then expose it. So that developer could view or debug code through code viewer like `vscode` with ssh plugin.

**Comment by LaynePeng** [comment]
Will be a solution on FATE side.

**Comment by LaynePeng** [comment]
Fixed in v1.4 with Notebook integration.
