### ISSUE TITLE
v1.9.0 (FATE on Spark):Submitting a job error

### ISSUE THREAD

**Issue by FranisiL** [FederatedAI/KubeFATE#780]
> The deployment process has used the environment and other information to refer to: https://github.com/FederatedAI/KubeFATE/issues/778#issue-1415860892

**To Reproduce**

After docker-compose starts F ATE V1.9.0, refer to : [Submitting a job](https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README.md) relevant data

**What happen?**

> [ERROR] [2022-10-20 16:51:29,434] [202210201650102483120] [2178:140031658874688] - [task_executor._run_] [line:265]: In Fate-v1.9 or later version, DataIO is deprecated, use DataTransform instead.
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 209, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 239, in run
    self._run(cpn_input=cpn_input)
  File "/data/projects/fate/fate/python/federatedml/model_base.py", line 315, in _run
    this_data_output = func(*real_param)
  File "/data/projects/fate/fate/python/federatedml/util/data_io.py", line 1135, in fit
    raise ValueError("In Fate-v1.9 or later version, DataIO is deprecated, use DataTransform instead.")
ValueError: In Fate-v1.9 or later version, DataIO is deprecated, use DataTransform instead.

**Comment by JingChen23** [comment]
has been fixed in https://github.com/FederatedAI/KubeFATE/commit/9e5c55a24d245bccfd91c418a9050db46384b7c1

Check https://github.com/FederatedAI/KubeFATE/blob/develop-1.10.0/docker-deploy/README.md
