### ISSUE TITLE
v1.9.0验证失败

### ISSUE THREAD

**Issue by wlj521** [FederatedAI/KubeFATE#781]
**What deployment mode you are use?  **
1. docker-compose;

![图片](https://user-images.githubusercontent.com/20828594/197094732-2a574210-f281-4177-bbcf-ae1bf975b21a.png)

运行
`docker exec -it confs-10000_client_1 bash
flow test toy --guest-party-id 10000 --host-party-id 9999`

{
    "jobId": "202210211010348589110",
    "retcode": 103,
    "retmsg": "Traceback (most recent call last):\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py\", line 142, in submit\n    raise Exception(\"create job failed\", response)\nException: ('create job failed', {'guest': {10000: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, <_InactiveRpcError of RPC that terminated with:\\n\\tstatus = StatusCode.UNKNOWN\\n\\tdetails = \"\\n[Roll Site Error TransInfo] \\n location msg=com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z \\n stack info=java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Task.getSerializedSize(Proxy.java:1120)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Metadata.getSerializedSize(Proxy.java:4893)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Packet.getSerializedSize(Proxy.java:7465)\\n\\tat io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)\\n\\tat io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)\\n\\tat io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)\\n\\tat io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)\\n\\tat io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)\\n\\tat io.grpc.internal.RetriableStream$1SendMessageEntry.runWith(RetriableStream.java:490)\\n\\tat io.grpc.internal.RetriableStream.delayOrExecute(RetriableStream.java:467)\\n\\tat io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:494)\\n\\tat io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:542)\\n\\tat io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:528)\\n\\tat io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:289)\\n\\tat io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)\\n\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\n\\tat com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\n\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\n\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\n\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\n\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\n\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\n\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\n\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)\\n\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\n\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:750)\\n \\n\\nexception trans path: rollsite(10000)\"\\n\\tdebug_error_string = \"{\"created\":\"@1666318240.924441281\",\"description\":\"Error received from peer ipv4:192.167.0.5:9370\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":952,\"grpc_message\":\"\\\\n[Roll Site Error TransInfo] \\\\n location msg=com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z \\\\n stack info=java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Task.getSerializedSize(Proxy.java:1120)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Metadata.getSerializedSize(Proxy.java:4893)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Packet.getSerializedSize(Proxy.java:7465)\\\\n\\\\tat io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)\\\\n\\\\tat io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)\\\\n\\\\tat io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)\\\\n\\\\tat io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)\\\\n\\\\tat io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)\\\\n\\\\tat io.grpc.internal.RetriableStream$1SendMessageEntry.runWith(RetriableStream.java:490)\\\\n\\\\tat io.grpc.internal.RetriableStream.delayOrExecute(RetriableStream.java:467)\\\\n\\\\tat io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:494)\\\\n\\\\tat io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:542)\\\\n\\\\tat io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:528)\\\\n\\\\tat io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:289)\\\\n\\\\tat io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)\\\\n\\\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\\\n\\\\tat com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\\\n\\\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\\\n\\\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\\\n\\\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\\\n\\\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\\\n\\\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\\\n\\\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\\\n\\\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)\\\\n\\\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\\\n\\\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\\\n\\\\tat java.lang.Thread.run(Thread.java:750)\\\\n \\\\n\\\\nexception trans path: rollsite(10000)\",\"grpc_status\":2}\"\\n>'}}, 'host': {9999: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, <_InactiveRpcError of RPC that terminated with:\\n\\tstatus = StatusCode.UNKNOWN\\n\\tdetails = \"\\n[Roll Site Error TransInfo] \\n location msg=com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z \\n stack info=java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Task.getSerializedSize(Proxy.java:1120)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Metadata.getSerializedSize(Proxy.java:4893)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\n\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Packet.getSerializedSize(Proxy.java:7465)\\n\\tat io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)\\n\\tat io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)\\n\\tat io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)\\n\\tat io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)\\n\\tat io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)\\n\\tat io.grpc.internal.RetriableStream$1SendMessageEntry.runWith(RetriableStream.java:490)\\n\\tat io.grpc.internal.RetriableStream.delayOrExecute(RetriableStream.java:467)\\n\\tat io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:494)\\n\\tat io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:542)\\n\\tat io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:528)\\n\\tat io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:289)\\n\\tat io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)\\n\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\n\\tat com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\n\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\n\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\n\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\n\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\n\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\n\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\n\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\n\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)\\n\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\n\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:750)\\n \\n\\nexception trans path: rollsite(10000)\"\\n\\tdebug_error_string = \"{\"created\":\"@1666318246.944426540\",\"description\":\"Error received from peer ipv4:192.167.0.5:9370\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":952,\"grpc_message\":\"\\\\n[Roll Site Error TransInfo] \\\\n location msg=com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z \\\\n stack info=java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Task.getSerializedSize(Proxy.java:1120)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Metadata.getSerializedSize(Proxy.java:4893)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)\\\\n\\\\tat com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Packet.getSerializedSize(Proxy.java:7465)\\\\n\\\\tat io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)\\\\n\\\\tat io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)\\\\n\\\\tat io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)\\\\n\\\\tat io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)\\\\n\\\\tat io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)\\\\n\\\\tat io.grpc.internal.RetriableStream$1SendMessageEntry.runWith(RetriableStream.java:490)\\\\n\\\\tat io.grpc.internal.RetriableStream.delayOrExecute(RetriableStream.java:467)\\\\n\\\\tat io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:494)\\\\n\\\\tat io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:542)\\\\n\\\\tat io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:528)\\\\n\\\\tat io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:289)\\\\n\\\\tat io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)\\\\n\\\\tat io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348)\\\\n\\\\tat com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138)\\\\n\\\\tat com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:406)\\\\n\\\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)\\\\n\\\\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\\\\n\\\\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\\\\n\\\\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\\\\n\\\\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\\\\n\\\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)\\\\n\\\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)\\\\n\\\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\\\n\\\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\\\n\\\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\\\n\\\\tat java.lang.Thread.run(Thread.java:750)\\\\n \\\\n\\\\nexception trans path: rollsite(10000)\",\"grpc_status\":2}\"\\n>'}}})\n"
}

**Comment by JingChen23** [comment]
You need to show:

1. The parties.conf file content.
2. The container status of both parties, not only 1000

Then we can start the triage.

**Comment by wlj521** [comment]
> You need to show:
> 
>     1. The parties.conf file content.
> 
>     2. The container status of both parties, not only 1000
> 
> 
> Then we can start the triage.

![图片](https://user-images.githubusercontent.com/20828594/197098272-5b8d3378-4e02-4479-a896-8577ab75bb5e.png)

**Comment by wlj521** [comment]
> The parties.conf file content.
> 
> 2. The container status of both parties, not only 1000

user=fate
dir=/opt/kubeFATE/projects/fate
party_list=(10000 9999)
party_ip_list=(10.xx.xx.55 10.xx.xx.56)
serving_ip_list=(10.xx.xx.55 10.xx.xx.56)

# Engines:
# Computing : Eggroll, Spark, Spark_local
computing=Eggroll
# Federation: Eggroll(computing: Eggroll), Pulsar/RabbitMQ(computing: Spark/Spark_local)
federation=Eggroll
# Storage: Eggroll(computing: Eggroll), HDFS(computing: Spark), LocalFS(computing: Spark_local)
storage=Eggroll
# Algorithm: Basic, NN
algorithm=Basic
# Device: IPCL, CPU
device=CPU

# spark and eggroll
compute_core=4

# default
exchangeip=

# modify if you are going to use an external db
mysql_ip=mysql
mysql_user=fate
mysql_password=fate_dev
mysql_db=fate_flow

name_node=hdfs://namenode:9000

# Define fateboard login information
fateboard_username=admin
fateboard_password=admin

# Define serving admin login information
serving_admin_username=admin
serving_admin_password=admin

**Comment by wlj521** [comment]
> > You need to show:
> > ```
> > 1. The parties.conf file content.
> > 
> > 2. The container status of both parties, not only 1000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then we can start the triage.
> 
> ![图片](https://user-images.githubusercontent.com/20828594/197098272-5b8d3378-4e02-4479-a896-8577ab75bb5e.png)

```
user=fate
dir=/opt/kubeFATE/projects/fate
party_list=(10000 9999)
party_ip_list=(10.xx.xx.55 10.xx.xx.56)
serving_ip_list=(10.xx.xx.55 10.xx.xx.56)

computing=Eggroll
federation=Eggroll
storage=Eggroll
algorithm=Basic
device=CPU

compute_core=4

exchangeip=

mysql_ip=mysql
mysql_user=fate
mysql_password=fate_dev
mysql_db=fate_flow

name_node=hdfs://namenode:9000

fateboard_username=admin
fateboard_password=admin

serving_admin_username=admin
serving_admin_password=admin
```

**Comment by wlj521** [comment]
这个问题，通过修改device=IPCL 解决了，可以跑通`docker exec -it confs-10000_client_1 bash
flow test toy --guest-party-id 10000 --host-party-id 9999`
但是`flow job submit -d fateflow/examples/lr/test_hetero_lr_job_dsl.json -c fateflow/examples/lr/test_hetero_lr_job_conf.json` 失败
{
    "jobId": "202210211439124395200",
    "retcode": 103,
    "retmsg": "Traceback (most recent call last):\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py\", line 142, in submit\n    raise Exception(\"create job failed\", response)\nException: ('create job failed', {'guest': {9999: {'retcode': 100, 'retmsg': 'Exception(\\'Traceback (most recent call last):\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py\", line 111, in run\\\\n    result = self._run()\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/worker/task_initializer.py\", line 51, in _run\\\\n    parameters, user_specified_parameters = ProviderManager.get_component_parameters(dsl_parser=dsl_parser,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/manager/provider_manager.py\", line 152, in get_component_parameters\\\\n    parameters = dsl_parser.parse_component_parameters(component_name,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py\", line 370, in parse_component_parameters\\\\n    parameters = self._init_component_setting(component_name,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py\", line 335, in _init_component_setting\\\\n    role_parameters = RuntimeConfParserUtil.get_component_parameters(provider,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/utils/runtime_conf_parse_util.py\", line 102, in get_component_parameters\\\\n    conf[\"CodePath\"] = provider.get(module, provider_components).get_run_obj_name(\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/components.py\", line 133, in get_run_obj_name\\\\n    return self._get_runner(role).__name__\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/components.py\", line 120, in _get_runner\\\\n    runner_class = self._role_to_runner_cls_getter[role]()\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/hetero_lr.py\", line 32, in hetero_lr_runner_guest\\\\n    from federatedml.linear_model.coordinated_linear_model.logistic_regression.hetero_logistic_regression.hetero_lr_guest import (\\\\n  File \"/data/projects/fate/fate/python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py\", line 22, in <module>\\\\n    from federatedml.linear_model.coordinated_linear_model.logistic_regression.hetero_logistic_regression.hetero_lr_base import \\\\\\\\\\\\n  File \"/data/projects/fate/fate/python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py\", line 21, in <module>\\\\n    from federatedml.optim.gradient.hetero_sqn_gradient import sqn_factory\\\\n  File \"/data/projects/fate/fate/python/federatedml/optim/gradient/hetero_sqn_gradient.py\", line 24, in <module>\\\\n    from federatedml.optim.gradient import hetero_linear_model_gradient\\\\n  File \"/data/projects/fate/fate/python/federatedml/optim/gradient/hetero_linear_model_gradient.py\", line 22, in <module>\\\\n    from python.federatedml.secureprotol.encrypt import IpclPaillierEncrypt\\\\nModuleNotFoundError: No module named \\\\\\'python\\\\\\'\\\\n\\')'}}, 'host': {10000: {'retcode': 100, 'retmsg': 'Exception(\\'Traceback (most recent call last):\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py\", line 111, in run\\\\n    result = self._run()\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/worker/task_initializer.py\", line 51, in _run\\\\n    parameters, user_specified_parameters = ProviderManager.get_component_parameters(dsl_parser=dsl_parser,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/manager/provider_manager.py\", line 152, in get_component_parameters\\\\n    parameters = dsl_parser.parse_component_parameters(component_name,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py\", line 370, in parse_component_parameters\\\\n    parameters = self._init_component_setting(component_name,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py\", line 335, in _init_component_setting\\\\n    role_parameters = RuntimeConfParserUtil.get_component_parameters(provider,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/utils/runtime_conf_parse_util.py\", line 102, in get_component_parameters\\\\n    conf[\"CodePath\"] = provider.get(module, provider_components).get_run_obj_name(\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/components.py\", line 133, in get_run_obj_name\\\\n    return self._get_runner(role).__name__\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/components.py\", line 120, in _get_runner\\\\n    runner_class = self._role_to_runner_cls_getter[role]()\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/hetero_lr.py\", line 40, in hetero_lr_runner_host\\\\n    from federatedml.linear_model.coordinated_linear_model.logistic_regression.hetero_logistic_regression.hetero_lr_host import (\\\\n  File \"/data/projects/fate/fate/python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py\", line 22, in <module>\\\\n    from federatedml.linear_model.coordinated_linear_model.logistic_regression.hetero_logistic_regression.hetero_lr_base import \\\\\\\\\\\\n  File \"/data/projects/fate/fate/python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py\", line 21, in <module>\\\\n    from federatedml.optim.gradient.hetero_sqn_gradient import sqn_factory\\\\n  File \"/data/projects/fate/fate/python/federatedml/optim/gradient/hetero_sqn_gradient.py\", line 24, in <module>\\\\n    from federatedml.optim.gradient import hetero_linear_model_gradient\\\\n  File \"/data/projects/fate/fate/python/federatedml/optim/gradient/hetero_linear_model_gradient.py\", line 22, in <module>\\\\n    from python.federatedml.secureprotol.encrypt import IpclPaillierEncrypt\\\\nModuleNotFoundError: No module named \\\\\\'python\\\\\\'\\\\n\\')'}}, 'arbiter': {10000: {'retcode': 100, 'retmsg': 'Exception(\\'Traceback (most recent call last):\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py\", line 111, in run\\\\n    result = self._run()\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/worker/task_initializer.py\", line 51, in _run\\\\n    parameters, user_specified_parameters = ProviderManager.get_component_parameters(dsl_parser=dsl_parser,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/manager/provider_manager.py\", line 152, in get_component_parameters\\\\n    parameters = dsl_parser.parse_component_parameters(component_name,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py\", line 370, in parse_component_parameters\\\\n    parameters = self._init_component_setting(component_name,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py\", line 335, in _init_component_setting\\\\n    role_parameters = RuntimeConfParserUtil.get_component_parameters(provider,\\\\n  File \"/data/projects/fate/fateflow/python/fate_flow/utils/runtime_conf_parse_util.py\", line 102, in get_component_parameters\\\\n    conf[\"CodePath\"] = provider.get(module, provider_components).get_run_obj_name(\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/components.py\", line 133, in get_run_obj_name\\\\n    return self._get_runner(role).__name__\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/components.py\", line 120, in _get_runner\\\\n    runner_class = self._role_to_runner_cls_getter[role]()\\\\n  File \"/data/projects/fate/fate/python/federatedml/components/hetero_lr.py\", line 48, in hetero_lr_runner_arbiter\\\\n    from federatedml.linear_model.coordinated_linear_model.logistic_regression.hetero_logistic_regression.hetero_lr_arbiter import (\\\\n  File \"/data/projects/fate/fate/python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_arbiter.py\", line 19, in <module>\\\\n    from federatedml.linear_model.coordinated_linear_model.logistic_regression.hetero_logistic_regression.hetero_lr_base import \\\\\\\\\\\\n  File \"/data/projects/fate/fate/python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py\", line 21, in <module>\\\\n    from federatedml.optim.gradient.hetero_sqn_gradient import sqn_factory\\\\n  File \"/data/projects/fate/fate/python/federatedml/optim/gradient/hetero_sqn_gradient.py\", line 24, in <module>\\\\n    from federatedml.optim.gradient import hetero_linear_model_gradient\\\\n  File \"/data/projects/fate/fate/python/federatedml/optim/gradient/hetero_linear_model_gradient.py\", line 22, in <module>\\\\n    from python.federatedml.secureprotol.encrypt import IpclPaillierEncrypt\\\\nModuleNotFoundError: No module named \\\\\\'python\\\\\\'\\\\n\\')'}}})\n"
}

**Comment by JingChen23** [comment]
@wlj521 Thanks for the further info, we are investigating and will give a solution today.

**Comment by wlj521** [comment]
algorithm=Basic或者NN，这两者有什么区别啊？

**Comment by JingChen23** [comment]
1. IPCL是Intel的一个加速库，你不需要用这个。
2. 带NN的镜像比较大，包含一些神经网络的python包
3. 你碰到的问题是因为我们eggroll的镜像有问题，我们已经重新打包并上传到dockerhub和163了。 https://github.com/FederatedAI/KubeFATE/issues/783 也是同样的问题。麻烦清空本地镜像后重新部署再试一次。

**Comment by wlj521** [comment]
> 1. IPCL是Intel的一个加速库，你不需要用这个。
> 
>     2. 带NN的镜像比较大，包含一些神经网络的python包
> 
>     3. 你碰到的问题是因为我们eggroll的镜像有问题，我们已经重新打包并上传到dockerhub和163了。 [problem with 1.9.0-release images #783](https://github.com/FederatedAI/KubeFATE/issues/783) 也是同样的问题。麻烦清空本地镜像后重新部署再试一次。

```
algorithm=NN
device=CPU
```
可以验证通过
`flow test toy --guest-party-id 10000 --host-party-id 9999`和
`flow job submit -d fateflow/examples/lr/test_hetero_lr_job_dsl.json -c fateflow/examples/lr/test_hetero_lr_job_conf.json`
