### ISSUE TITLE
v1.9.0 (FATE on Spark):After stopping the Spark-master and Spark-Work containers, the federated tasks can still run normally

### ISSUE THREAD

**Issue by FranisiL** [FederatedAI/KubeFATE#782]
> The deployment process has used the environment and other information to refer to: https://github.com/FederatedAI/KubeFATE/issues/778#issue-1415860892

**To Reproduce**

After stopping the Spark-master and Spark-Work containers, the federated tasks can still run normally, which is not normal in my understanding

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/45416982/197099654-e3a40d1e-e36e-4b36-91cb-8c285a0889e0.png">

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/45416982/197099750-7d758f7f-1bac-4ae9-82b8-c92f96fc49a9.png">

**Comment by JingChen23** [comment]
你是下面两个意思中的哪一个？
1. 任务真成功了
2. 任务没成功但是fateboard上显示成功了

可以查看一下evaluation_0模块的具体输出，判断是真成功还是假成功。

**Comment by FranisiL** [comment]
> 你是下面两个意思中的哪一个？
> 
> 1. 任务真成功了
> 2. 任务没成功但是fateboard上显示成功了
> 
> 可以查看一下evaluation_0模块的具体输出，判断是真成功还是假成功。

**The first one, the task is really successful**

**Comment by JingChen23** [comment]
This is obviously impossible, please double check your environment.
I have just tried and the first step, reader_0, will fail.
