### ISSUE TITLE
support setting password for jupyter notebook

### ISSUE THREAD

**Issue by HelloJeremy** [FederatedAI/KubeFATE#787]
通过docker-compose部署kubeFATE，怎么设置浏览器访问 jupyter notebook（http://ip:20000）的登录密码
如果jupyter notebook没有访问密码，jupyter notebook会有安全漏洞

**Comment by n063h** [comment]
> 通过docker-compose部署kubeFATE，怎么设置浏览器访问 jupyter notebook（[http://ip:20000）的登录密码](http://ip:20000%EF%BC%89%E7%9A%84%E7%99%BB%E5%BD%95%E5%AF%86%E7%A0%81) 如果jupyter notebook没有访问密码，jupyter notebook会有安全漏洞

@HelloJeremy We have no such proposal at present, you can manage it manually by
1.  enter the client container.
2. generate a hashed passwd {P} by `from notebook.auth import passwd;passwd()"` with python.
3. `ps -aux | grep jupyter` to find the args to start the jupyter notebook server.
4. kill the process and rerun the command with replaced --NotebookApp.password={P} 

We will appreciate it if you're interested in it and propose a pr to the issue.

**Comment by HelloJeremy** [comment]
> @n063h Jupyter notebook port is 20000，Killing jupyter process triggers client container restart .So this doesn't solve my problem

**Comment by HelloJeremy** [comment]
@n063h Can NotebookApp.password be designed to be configurable? For example, NotebookApp.password can be specified in parties.conf

**Comment by n063h** [comment]
> > @n063h Jupyter notebook port is 20000，Killing jupyter process triggers client container restart .So this doesn't solve my problem

@HelloJeremy Yes. I'm aware of this problem. It's probably related to the entrypoint in dockerfile. I will submit a patch to fix it sooner.

**Comment by HelloJeremy** [comment]
> @HelloJeremy Yes. I'm aware of this problem. It's probably related to the entrypoint in dockerfile. I will submit a patch to fix it soon.

@n063h  It's fixed, please let me know, thanks

**Comment by n063h** [comment]
@HelloJeremy Hi, I fixed this issue in PR #790 .If you're using 1.9.0, you may refer to my changes to solve your problem.

**Comment by HelloJeremy** [comment]
> @HelloJeremy Hi, I fixed this issue in PR #790 .If you're using 1.9.0, you may refer to my changes to solve your problem.

@n063h Hi, Does the client docker image need to be updated?

**Comment by n063h** [comment]
> > @HelloJeremy Hi, I fixed this issue in PR #790 .If you're using 1.9.0, you may refer to my changes to solve your problem.
> 
> @n063h Hi, Does the client docker image need to be updated?

To avoid such different behavior between images of different versions, I choose to write extra entrypoint command rather than modify it. Now the entrypoint in dockerfile has been overwritten in docker-compose.yaml or statefulset.yaml, so you don't need to update the image.

**Comment by HelloJeremy** [comment]
>command: ["bash", "-c", "flow init --ip ${FATE_FLOW_IP} --port ${FATE_FLOW_PORT} && pipeline init --ip ${FATE_FLOW_IP} --port ${FATE_FLOW_PORT} && jupyter notebook --ip=0.0.0.0 --port=20000 --allow-root --debug --NotebookApp.notebook_dir='/data/projects/fate/' --no-browser --NotebookApp.token='' --NotebookApp.password='${NOTEBOOK_HASHED_PASSWORD}'"]

Are ${FATE_FLOW_IP}, ${FATE_FLOW_PORT}, ${NOTEBOOK_HASHED_PASSWORD} to be changed to $${FATE_FLOW_IP}, $${FATE_FLOW_PORT}, $${NOTEBOOK_HASHED_PASSWORD}. $$ allows you to refer to environment variables that you don’t want processed by Compose.

**Comment by HelloJeremy** [comment]
![image](https://user-images.githubusercontent.com/23650729/199671827-587c0585-ae36-47b8-bc4f-7e8fb2b9f69d.png)

@n063h Do you need to use $$?

**Comment by n063h** [comment]
> ![image](https://user-images.githubusercontent.com/23650729/199671827-587c0585-ae36-47b8-bc4f-7e8fb2b9f69d.png)
> 
> @n063h Do you need to use $$?

I have test it, and it works. I don't think it's necessary. Is there any hidden issue with ${val} ?

**Comment by HelloJeremy** [comment]
![0098646d1c1aae3739d8e52ea760c3e](https://user-images.githubusercontent.com/23650729/199676241-84677fd9-3162-4aa6-b13a-154781f49fd1.jpg)

@n063h Hi, I also overridden the entrypoint in docker-compose.yaml, I run /bin/sh -c flow init --ip ${FATE_FLOW_IP}......
But flow init failed，Because I can't get the value of FATE_FLOW_IP, FATE_FLOW_PORT. 
Is it because I use /bin/sh you use bash?

**Comment by n063h** [comment]
> ![0098646d1c1aae3739d8e52ea760c3e](https://user-images.githubusercontent.com/23650729/199676241-84677fd9-3162-4aa6-b13a-154781f49fd1.jpg)
> 
> @n063h Hi, I also overridden the entrypoint in docker-compose.yaml, I run /bin/sh -c flow init --ip ${FATE_FLOW_IP}...... But flow init failed，Because I can't get the value of FATE_FLOW_IP, FATE_FLOW_PORT. I'm afraid you have the same problem so suggest you use $$. You have no problem, Is it because I use /bin/sh you use bash?

@HelloJeremy Thx for your comment!
I realize it's different behavior between docker-compose and helm-chart. Under testing in k8s mode, \$\$ is correct one. I will submit a patch to fix that.
