### ISSUE TITLE
kubefate连接自己的mysql数据库，在执行upload时报错

### ISSUE THREAD

**Issue by KAgBMan** [FederatedAI/KubeFATE#793]
**What deployment mode you are use?  **
1. docker-compose;
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
fate_version=v1.9.0  
kubefate_version=v1.4.5

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: centeros
 - Version 7.8

**To Reproduce**
python /data/projects/fate/fateflow/python/fate_flow/fate_flow_client.py -f upload -c /data/projects/fate/fateflow/examples/upload/upload_host.json 

**What happen?**

```
111
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 148, in _run_
112
    sess.init_computing(computing_session_id=args.session_id, options=session_options)
113
  File "/data/projects/fate/fate/python/fate_arch/session/_session.py", line 118, in init_computing
114
    self._computing_session = CSession(
115
  File "/data/projects/fate/fate/python/fate_arch/computing/eggroll/_csession.py", line 38, in __init__
116
    self._rp_session = session_init(session_id=session_id, options=options)
117
  File "/data/projects/fate/eggroll/python/eggroll/core/session.py", line 42, in session_init
118
    er_session = ErSession(session_id=session_id, options=options)
119
  File "/data/projects/fate/eggroll/python/eggroll/core/session.py", line 199, in __init__
120
    self.__session_meta = self._cluster_manager_client.get_or_create_session(session_meta)
121
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 185, in get_or_create_session
122
    return self.__check_processors(
123
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 243, in __check_processors
124
    raise ValueError(f"processor in session meta is not valid: {session_meta}")
125
ValueError: processor in session meta is not valid: <ErSessionMeta(id=202211040933435208290_upload_0_0_local_0, name=, status=NEW, tag=, processors=[***, len=2], options=[{'python.venv': '', 'eggroll.session.deploy.mode': 'cluster', 'eggroll.session.processors.per.node': '2', 'python.path': '/data/projects/fate/fateflow/python:$PYTHONPATH:/data/projects/fate/fate/python:/data/projects/fate/eggroll/python:/data/projects/fate/fateflow/python:/data/projects/fate/fate/python/fate_client', 'eggroll.rollpair.inmemory_output': 'True'}]) at 0x7f2135059d00>
126
[INFO] [2022-11-04 09:39:53,445] [202211040933435208290] [20144:139781218481984] - [task_executor._run_] [line:267]: start destroy sessions
127
[INFO] [2022-11-04 09:39:53,445] [202211040933435208290] [20144:139781218481984] - [_session.destroy_all_sessions] [line:446]: start destroy manager session 202211040933435208290_upload_0_0_local_0 all sessions
128
[INFO] [2022-11-04 09:39:53,449] [202211040933435208290] [20144:139781218481984] - [_session.get_session_from_record] [line:390]: query by manager session id 202211040933435208290_upload_0_0_local_0
129
[INFO] [2022-11-04 09:39:53,452] [202211040933435208290] [20144:139781218481984] - [_session.get_session_from_record] [line:392]: ['202211040933435208290_upload_0_0_local_0']
```

**Screenshots**

![image](https://user-images.githubusercontent.com/22344179/199943356-a9b8c58d-f39e-4848-95b7-cc20006ae81e.png)

**Additional context**

我使用了外部的mysql，且已经执行了两个sql文件，增加了对应的数据表及数据
server_node数据
![image](https://user-images.githubusercontent.com/22344179/199943472-31f1d31a-6003-428f-b81f-2d3a3d02f42b.png)

**Comment by JingChen23** [comment]
Try to change the ip address of cluster manager and node manager to the nodeIp or loadbalancerIp of you K8s cluster, because your cluster manager and node manager are on the K8s cluster.

The reason why you see this err msg is because the 2 services: cluster manager and node manager, are not accessible.

**Comment by KAgBMan** [comment]
是将server_node表中的CLUSTER_MANAGER和NODE_MANAGER的host改成nodeip吗？
我使用kubectl describe node <name>获取InternalIP后，将server_node中两条数据的host都改成此InternalIP后，问题依旧没有解决，烦请老师详细说一下，万分感谢

**Comment by JingChen23** [comment]
先把cluster manager和node manager的服务修改成nodeport形式，然后把数据库中的两条host改成node ip。internal ip不行，那只有在k8s cluster内部能访问。

参考：https://kubernetes.io/docs/concepts/services-networking/service/#service-nodeport-custom-listen-address

**Comment by KAgBMan** [comment]
问题已解决
使用kubectl describe pod <clustermanager_name> -n <namespace> 获取clustermanager ip
使用kubectl describe pod <nodemanager_name> -n <namespace> 获取nodemanager ip
分别填入server_node表中host
