### ISSUE TITLE
Docker-compose进行集群部署：Intersection模块跑了很久也没有结果

### ISSUE THREAD

**Issue by longranger2** [FederatedAI/KubeFATE#799]
**What deployment mode you are use?**  
1. docker-compose;

**What KubeFATE and FATE version you are using?**  

KubeFATE version:v1.8.0
FATE version :v1.8.0.

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.** 

 - OS: Centos 7.9 8核16G 硬盘40G

**To Reproduce**
[官方文档教程](https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md)

**What happen?**

我想跑通官方文档的教程：利用[docker-compose进行集群的部署](https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md)，在验证Serving-Service功能的时候出现问题。我任务可以正常提交：
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/52858395/201826689-d14fb4cd-1f6b-449e-bbdc-e44b6fe21315.png">
但Intersection模块似乎有问题，我跑了几个小时还是卡在那里，我不知道哪里出错了，我重新提交了几次任务也是一样的结果。
![image](https://user-images.githubusercontent.com/52858395/201826847-c743350b-e08a-4e10-aa37-469259c6ee0a.png)

**Comment by owlet42** [comment]
把dataio修改成DataTransform。

**Comment by owlet42** [comment]
Documentation and version mismatch. This issue(https://github.com/FederatedAI/KubeFATE/issues/800) will update the documentation.

**Comment by longranger2** [comment]
应该不是这个问题，我修改成DataTransform模块后还是会卡在intersection模块那里
![image](https://user-images.githubusercontent.com/52858395/201846222-61333d69-2da5-4a97-ad52-f03ff36eb7f9.png)

**Comment by longranger2** [comment]
datatransform模块那里的数据我看了下，guest节点的数据是可以正常加载的
![image](https://user-images.githubusercontent.com/52858395/201847629-8dd606d4-0555-43a2-a998-56274cf09570.png)
但host节点的那里似乎没有加载，是这里的问题吗？
![image](https://user-images.githubusercontent.com/52858395/201848236-58c37a01-c4cc-441d-ae0a-42887a829299.png)

**Comment by owlet42** [comment]
开启fateflow等debug日志，然后贴下任务日志。
修改docker-compose.yaml文件
```bash
services:
  fateflow:
    environment:
      FATE_LOG_LEVEL: "DEBUG"
```
运行docker-compose up -d，再运行下FAT任务。

**Comment by longranger2** [comment]
我解决了，我在另一个guest节点提交任务就可以了
`flow job submit -d fateflow/examples/lr/test_hetero_lr_job_dsl.json -c fateflow/examples/lr/test_hetero_lr_job_conf.json`
为什么会这样呢？难道在host节点就不能提交任务吗？他们不是互通的吗？

**Comment by owlet42** [comment]
要部署fate-serving，并确保fate-serving组件运行正常。

> 我现在遇到另一个问题，在加载模型时报一下错误： `flow model load -c fateflow/examples/model/publish_load_model.json`
> 
> ![image](https://user-images.githubusercontent.com/52858395/201959356-16e19e4d-6909-46eb-adbc-908f58886c3a.png)

**Comment by longranger2** [comment]
我已经解决了这个问题，我是通过这里的方法解决的：https://github.com/FederatedAI/KubeFATE/issues/664

> 要部署fate-serving，并确保fate-serving组件运行正常。
> 
> > 我现在遇到另一个问题，在加载模型时报一下错误： `flow model load -c fateflow/examples/model/publish_load_model.json`
> > ![image](https://user-images.githubusercontent.com/52858395/201959356-16e19e4d-6909-46eb-adbc-908f58886c3a.png)

**Comment by JingChen23** [comment]
Glad to know the problem has been solved.

**Comment by liuhaichaogithub** [comment]
> 我明白了，我在另外一个嘉宾节点提供交务就可以了 `flow job submit -d fateflow/examples/lr/test_hetero_lr_job_dsl.json -c fateflow/examples/lr/test_hetero_lr_job_conf.json` 为什么会这样呢？难在主播节就不能提交务吗？他们不是互通的吗？

我也是，在另一个节点提交就好了，为什么呢？

**Comment by owlet42** [comment]
FATE提及任务必须在guest方提交，也就是运行flow job submit的party方必须是guest。
