### ISSUE TITLE
Issues found in docker-compose deployment

### ISSUE THREAD

**Issue by magic-hya** [FederatedAI/KubeFATE#837]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.9.2

Issues：
1.When using 'delete' to stop the container, the following errors will occur, causing subsequent operations to be interrupted.
I suspect that the stop sequence causes this problem
![image](https://user-images.githubusercontent.com/85269941/209097348-3a0c60b8-663f-44e1-b0fd-a0d45722b3ed.png)
2.The following question is the warning of the new version of 'docker compose'. Does this need to be fixed?
My version is v2.9.0
![image](https://user-images.githubusercontent.com/85269941/209100333-3d117896-fe3f-439e-929a-9cf5ad948c3e.png)

**Comment by magic-hya** [comment]
If PR is to be submitted, which branch to submit to？

**Comment by JingChen23** [comment]
hi @magic-hya , is this understanding right:

After your fix, the docker_deploy.sh delete all command will work properly and will delete the network successfully?

https://github.com/FederatedAI/KubeFATE/pull/838

With regarding to this pr, could you please do one more test following below steps:
1. install FATE on docker-compose, by `bash ./docker_deploy.sh all`
2. destroy it by `docker_deploy.sh delete all` command
3. install FATE again by `bash ./docker_deploy.sh all` and check if this time we can install it propely

Thank you!

**Comment by magic-hya** [comment]
> hi @magic-hya , is this understanding right:
> 
> After your fix, the docker_deploy.sh delete all command will work properly and will delete the network successfully?
> 
> #838
> 
> With regarding to this pr, could you please do one more test following below steps:
> 
> 1. install FATE on docker-compose, by `bash ./docker_deploy.sh all`
> 2. destroy it by `docker_deploy.sh delete all` command
> 3. install FATE again by `bash ./docker_deploy.sh all` and check if this time we can install it propely
> 
> Thank you!

Test process：
step1: test OK！
![image](https://user-images.githubusercontent.com/85269941/210329914-20ecc229-dbda-4339-8dd1-a710d804f7a3.png)
![image](https://user-images.githubusercontent.com/85269941/210330085-2878281f-c73f-4e82-b332-5a668b5be34f.png)
step2: test OK！delete all command work properly and delete the network successfully and no warning.
![image](https://user-images.githubusercontent.com/85269941/210330426-26ff7f9a-9e4f-48ee-9f4b-d571b8960ab9.png)
step3: test OK！
![image](https://user-images.githubusercontent.com/85269941/210331772-8a9ceaef-e08c-456d-87ee-1ef6e02d6fcb.png)

**Comment by TomsyPaul** [comment]
1. Why is the PR [https://github.com/FederatedAI/KubeFATE/pull/838] not merged to the releases..? 
2. The following question is the warning of the new version of 'docker compose'. Does this need to be fixed?
![image](https://github.com/FederatedAI/KubeFATE/assets/16011229/a0313606-1265-4511-8382-4a55c176b796)

**Comment by owlet42** [comment]
Sorry, due to the temporary change of the FATE release plan, this modification was not released in time, and this part of the contribution will be released in the next version.
