### ISSUE TITLE
有关防火墙的问题

### ISSUE THREAD

**Issue by oceanqdu** [FederatedAI/KubeFATE#842]
在使用docker-compose和k8s部署kubeFATE的过程中前置条件都需要关闭防火墙，请问这是为什么呢？关闭防火墙操作是必须的吗？如果不关闭需要做哪些额外的其他操作吗？期望能够得到您的回答。

**Comment by owlet42** [comment]
作为参考实例关闭防火墙可以简化部署操作，降低初学者的使用门槛。
关闭防火墙并不是必须操作，在正式的生成环境建议不应该关闭防火墙。
如果不关闭防火墙那么就需要保证FATE各个party之间通信端口打开，并且可以正常访问，例如rollsite的9370和fateboard的8080等。

**Comment by oceanqdu** [comment]
> 作为参考示例关闭防火墙可以简化部署操作，降低初学者的使用门槛。 关闭防火墙并不是必须操作，在正式的生成环境建议不应该关闭防火墙。 如果不关闭防火墙那么就需要保证FATE各个party之间通信端口打开，并且可以正常访问，例如rollsite的9370和fateboard的8080等。

@owlet42 非常感谢您的回答。假如我用docker compose的方式部署了kubefate，那么我只需要将所有docker容器映射到宿主机所对应的端口在防火墙规则中设置开发就可以不用关闭防火墙了对吗？不知道我理解的对不对



例如以下情况：
`CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                   PORTS                                                                                                                                           NAMES
5d2e84ba4c77   federatedai/serving-server:2.1.5-release   "/bin/sh -c 'java -c…"   5 minutes ago   Up 5 minutes             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                       serving-9999_serving-server_1
3dca43f3c9d5   federatedai/serving-admin:2.1.5-release    "/bin/sh -c 'java -c…"   5 minutes ago   Up 5 minutes             0.0.0.0:8350->8350/tcp, :::8350->8350/tcp                                                                                                       serving-9999_serving-admin_1
fe924918509b   federatedai/serving-proxy:2.1.5-release    "/bin/sh -c 'java -D…"   5 minutes ago   Up 5 minutes             0.0.0.0:8059->8059/tcp, :::8059->8059/tcp, 0.0.0.0:8869->8869/tcp, :::8869->8869/tcp, 8879/tcp                                                  serving-9999_serving-proxy_1
b62ed8ba42b7   bitnami/zookeeper:3.7.0                    "/opt/bitnami/script…"   5 minutes ago   Up 5 minutes             0.0.0.0:2181->2181/tcp, :::2181->2181/tcp, 8080/tcp, 0.0.0.0:49226->2888/tcp, :::49226->2888/tcp, 0.0.0.0:49225->3888/tcp, :::49225->3888/tcp   serving-9999_serving-zookeeper_1
3c643324066f   federatedai/client:1.10.0-release           "/bin/sh -c 'flow in…"   5 minutes ago   Up 5 minutes             0.0.0.0:20000->20000/tcp, :::20000->20000/tcp                                                                                                   confs-9999_client_1
3fe0af1ebd71   federatedai/fateboard:1.10.0-release        "/bin/sh -c 'java -D…"   5 minutes ago   Up 5 minutes             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                                                                       confs-9999_fateboard_1
635b7d99357e   federatedai/fateflow:1.10.0-release         "container-entrypoin…"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:9360->9360/tcp, :::9360->9360/tcp, 8080/tcp, 0.0.0.0:9380->9380/tcp, :::9380->9380/tcp                                                  confs-9999_fateflow_1
8b515f08add3   federatedai/eggroll:1.10.0-release          "/tini -- bash -c 'j…"   5 minutes ago   Up 5 minutes             8080/tcp, 0.0.0.0:9370->9370/tcp, :::9370->9370/tcp                                                                                             confs-9999_rollsite_1
108cc061c191   federatedai/eggroll:1.10.0-release          "/tini -- bash -c 'j…"   5 minutes ago   Up 5 minutes             4670/tcp, 8080/tcp                                                                                                                              confs-9999_clustermanager_1
f10575e76899   federatedai/eggroll:1.10.0-release          "/tini -- bash -c 'j…"   5 minutes ago   Up 5 minutes             4671/tcp, 8080/tcp                                                                                                                              confs-9999_nodemanager_1
aa0a0002de93   mysql:8.0.28                               "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes             3306/tcp, 33060/tcp                                                                                                                             confs-9999_mysql_1`

  在上述情况中我是不是只要在防火墙规则中设置开放PORTS中所有的映射就可以不用关闭防火墙了？

**Comment by tigflanker** [comment]
> 作为参考示例关闭防火墙可以简化部署操作，降低初学者的使用门槛。 关闭防火墙并不是必须操作，在正式的生成环境建议不应该关闭防火墙。 如果不关闭防火墙那么就需要保证FATE各个party之间通信端口打开，并且可以正常访问，例如rollsite的9370和fateboard的8080等。

@owlet42 Hi owlet，想问下我们生产环境使用KubeFATE的时候，假如我们最终想要开启防火墙。那么我们应该 “在安装之前和安装之后都保持打开防火墙”、还是 “安装之前可以关闭，安装之后再打开”？我试过第二种方案，防火墙打开以后提交建模两边通信报错

这中间好像少一个操作来联通两边的ip信息互访
