### ISSUE TITLE
v1.9.2 configmap error in "job_default_config.yaml"

### ISSUE THREAD

**Issue by wood-j** [FederatedAI/KubeFATE#873]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **

- v1.9.2
- eggroll

**MUST** Please state the KubeFATE and FATE version you found the issue

- v1.9.2

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: rhel
 - Version: 8.6

**To Reproduce**

1. install fate cluster `fate-10001` with official image and chart
2. use command to see the cm created: `kubectl edit cm python-config -n fate-10001`
3. in the chapter of file `job_default_config.yaml`, shows:
![image](https://user-images.githubusercontent.com/12793366/230274185-c43e9e5d-dd96-4f20-b47c-8bb061e90fd0.png)
4. according to the file(fateflow/conf/job_default_config.yaml) from fate version 1.9.2, it should be:
![image](https://user-images.githubusercontent.com/12793366/230274576-2072ce24-2441-496c-ab95-4199d8a8baaa.png)
5. it could lead to oom happen when upload big dataset file to eggroll

**What happen?**

OOM happened when uploading big dataset file

![image](https://user-images.githubusercontent.com/12793366/230275402-029d6402-4da2-42e5-a0ac-f64e76e53f25.png)

code reading file `fateflow/python/fate_flow/components/upload.py`:

![image](https://user-images.githubusercontent.com/12793366/230277146-0e29592b-a041-470b-b11e-e207dde8d644.png)

`None` value from config will read all lines.

**Comment by owlet42** [comment]
Thanks for your feedback, this bug will be fixed in v1.11
