### ISSUE TITLE
KubeFate Ingress not showing IP address

### ISSUE THREAD

**Issue by PaulKMandal** [FederatedAI/KubeFATE#894]
**What deployment mode you are use?**
1. docker-compose; N/A
2. Kuberentes. 
Client Version: 1.19.0
Server Version: 1.24.6

**What KubeFATE and FATE version you are using?**
develop-1.11.1 and 1.11.1 respectively

**To Reproduce**
I am currently trying to go through the install guide to deploy KubeFATE to an Azure instance. You're kubernetes docs say to reference the miniKube install guide which say to enable the ingress via

`minikube addons enable ingress`

However, whenever I look up how to do this on azure, it says I need to create an nginx server which I am not quite sure how to do. (I'm generally more on the ML side of things than the DevOps side of things, so any direction here would be much appreciated).

**Screenshots**
![Ingress](https://github.com/FederatedAI/KubeFATE/assets/40133940/d72d39fd-7616-420a-84cc-bab1d1cfab8b)

**Comment by owlet42** [comment]
It seems that your k8s needs to deploy an Ingress-Nginx Controller, you can refer to this document deployment: https://kubernetes.github.io/ingress-nginx/deploy/#azure

**Comment by PaulKMandal** [comment]
> It seems that your k8s needs to deploy an Ingress-Nginx Controller, you can refer to this document deployment: https://kubernetes.github.io/ingress-nginx/deploy/#azure

Thanks for the response. Those were the documents I was referencing. I was a bit confused about whether I need to modify anything in those docs, (e.g. do I need to specify the Nginx controller to deploy to the kubefate namespace? Is any additional configuration necessary?).

Sorry if this is a simple question, as I mentioned I am new to the DevOps/Infrastructure side of things.

**Comment by owlet42** [comment]
@PaulKMandal No need to configure Ingress-Nginx Controller, the default installation can be used by kubeFATE. After the installation is successful, you can see the pods of the Ingress-Nginx Controller.

**Comment by PaulKMandal** [comment]
Thanks for the help. I'm closing this issue.
