### ISSUE TITLE
docker-compose for fate-serving

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#95]
Can share the reason why fate-serving has a new docker-compose-serving.yml file instead of re-use existing docker-compose.yml file? In the new docker-compose-serving.yml file, it has separate redis and serving-proxy services? Why not re-use existing Redis and proxy? Otherwise, we have 2 redis and 2 proxy for each party

**Comment by jiahaoc1993** [comment]
@cometta Actually, we design this according to "FATE Serving is an online part that is different from the offline training part". To split them in different `docker-compose` file could make this logic more explicit. After the splitting, we need to make sure that every deployment launched by the `docker-compose` is a functional entity.  So we add redis and proxy to the `docker-compose-serving.yml`

**Comment by cometta** [comment]
@jiahaoc1993 , with a different docker-compose-serving.yml , we need another machine to run this ? each party with need 2 VMs to run?

**Comment by jiahaoc1993** [comment]
@cometta no we don't, we can deploy both training and serving service on the same machine

**Comment by cometta** [comment]
@jiahaoc1993  May i know if i have party 1000,9999, 9998 on 3 different machines, then fate serving and zookeeper need to installed on each party 1000,9999, 9998?

**Comment by LaynePeng** [comment]
Yes. We should understand that, **one party is one organization and no data exchange between them allow**. This is what Federated Learning.
