### ISSUE TITLE
docker-deploy/docker_deploy.sh当中的一段代码问题

### ISSUE THREAD

**Issue by zkzhu0110** [FederatedAI/KubeFATE#97]
您好，可以方便提一个问题吗：我今天在重新部署FATE的时候发现了docker-deploy/docker_deploy.sh当中的2行代码有问题，具体代码在文件的第156-157行（详情如下）
```
docker volume rm confs-${target_party_id}_shared_dir_examples
docker volume rm confs-${target_party_id}_shared_dir_federatedml
```
从我在机器上测试的效果来看，confs与${target_party_id}之间应该没有“-”，我部署了FATE之后再重新部署的时候就报错了，说没有这个volume。

在我机器上，我运行了命令`sudo docker volume ls`之后的结果如下，可以发现，confs与${target_party_id}之间并没有“-”。

![image](https://user-images.githubusercontent.com/40782501/76395675-d5c4e280-63b2-11ea-8ae8-50c2f2f1be49.png)

**Comment by zkzhu0110** [comment]
图片上传不了，我把结果的文本复制一下吧：
leinao@GA040:~$ sudo docker volume ls
DRIVER              VOLUME NAME
local               confs10000_fate_flow_logs
local               confs10000_shared_dir_examples
local               confs10000_shared_dir_federatedml

感谢！

**Comment by jiahaoc1993** [comment]
@zkzhu0110 请问你的系统是什么？

**Comment by LaynePeng** [comment]
Close issue since no more response over 3 months.
